/******************************************************************************
** moxaclassbased_devicetypebase.cpp
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#include "moxaclassbased_devicetypebase.h"
#include "moxaclassbased_devicetype.h"
#include "uagenericnodes.h"
#include "nodemanagerroot.h"
#include "methodhandleuanode.h"
#include "moxaclassbased_nodemanagermoxaclassbasedns.h"

#include "instancefactory.h"
#include "moxaclassbased_connectionaccounttype.h"
#include "moxaclassbased_deviceinformationtype.h"
#include "moxaclassbased_instancefactory_moxaclassbasedns.h"
#include "moxaclassbased_ipsettingtype.h"
#include "moxaclassbased_netconftype.h"
#include "moxaclassbased_restfultype.h"
#include "moxaclassbased_snmptype.h"
#include "opcua_extensionobject.h"
// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

bool DeviceTypeBase::s_typeNodesCreated = false;
MoxaClassBased::ConnectionAccountType* DeviceTypeBase::s_pConnectionAccount = NULL;
MoxaClassBased::DeviceInformationType* DeviceTypeBase::s_pDeviceInformation = NULL;
MoxaClassBased::IpSettingType* DeviceTypeBase::s_pIpSetting = NULL;
MoxaClassBased::NETCONFType* DeviceTypeBase::s_pNETCONF = NULL;
MoxaClassBased::RESTfulType* DeviceTypeBase::s_pRESTful = NULL;
MoxaClassBased::SNMPType* DeviceTypeBase::s_pSNMP = NULL;
OpcUa::BaseDataVariableType* DeviceTypeBase::s_pAlias = NULL;
OpcUa::BaseDataVariableType* DeviceTypeBase::s_pDeviceProfileName = NULL;
OpcUa::BaseDataVariableType* DeviceTypeBase::s_pMacAddress = NULL;

/** Constructs an DeviceType object using an instance declaration node as base
*/
DeviceTypeBase::DeviceTypeBase(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: OpcUa::BaseObjectType(nodeId, pInstanceDeclarationObject, pNodeConfig, pSharedMutex)
{
    initialize();
}

/** Constructs an DeviceType object
*/
DeviceTypeBase::DeviceTypeBase(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: OpcUa::BaseObjectType(nodeId, name, browseNameNameSpaceIndex, pNodeConfig, pSharedMutex)
{
    initialize();
}

/**  Constructs an instance of the class DeviceTypeBase with all components
*/
DeviceTypeBase::DeviceTypeBase(
    UaBase::Object*    pBaseNode,    //!< [in] The "tree" of nodes that specifies the attributes of the instance and its children
    XmlUaNodeFactoryManager* pFactory, //!< [in] The factory to create the children
    NodeManagerConfig* pNodeConfig,  //!< [in] Interface pointer to the NodeManagerConfig interface used to add and delete node and references in the address space
    UaMutexRefCounted* pSharedMutex) //!< [in] Shared mutex object used to synchronize access to the variable. Can be NULL if no shared mutex is provided
: OpcUa::BaseObjectType(pBaseNode, pFactory, pNodeConfig, pSharedMutex)
{
    UaStatus      addStatus;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }

    m_pConnectionAccount = NULL;
    m_pDeviceInformation = NULL;
    m_pIpSetting = NULL;
    m_pNETCONF = NULL;
    m_pRESTful = NULL;
    m_pSNMP = NULL;
    m_pAlias = NULL;
    m_pDeviceProfileName = NULL;
    m_pMacAddress = NULL;

    std::list<UaBase::BaseNode*> lstReferencedNodes = pBaseNode->hierarchicallyReferencedNodes();
    for (std::list<UaBase::BaseNode*>::const_iterator it = lstReferencedNodes.begin(); it != lstReferencedNodes.end(); it++)
    {
        UaBase::BaseNode *pChild = *it;
        if (pChild->browseName() == UaQualifiedName("Alias", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pAlias)
            {
                m_pAlias = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pAlias, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pAlias->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("DeviceProfileName", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pDeviceProfileName)
            {
                m_pDeviceProfileName = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pDeviceProfileName, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pDeviceProfileName->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("MacAddress", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pMacAddress)
            {
                m_pMacAddress = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pMacAddress, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pMacAddress->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("ConnectionAccount", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pConnectionAccount)
            {
                m_pConnectionAccount = (MoxaClassBased::ConnectionAccountType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pConnectionAccount, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pConnectionAccount->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("DeviceInformation", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pDeviceInformation)
            {
                m_pDeviceInformation = (MoxaClassBased::DeviceInformationType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pDeviceInformation, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pDeviceInformation->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("IpSetting", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pIpSetting)
            {
                m_pIpSetting = (MoxaClassBased::IpSettingType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pIpSetting, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pIpSetting->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("NETCONF", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pNETCONF)
            {
                m_pNETCONF = (MoxaClassBased::NETCONFType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pNETCONF, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pNETCONF->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("RESTful", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pRESTful)
            {
                m_pRESTful = (MoxaClassBased::RESTfulType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pRESTful, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pRESTful->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("SNMP", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pSNMP)
            {
                m_pSNMP = (MoxaClassBased::SNMPType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pSNMP, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pSNMP->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
    }
    UA_ASSERT(m_pConnectionAccount);
    UA_ASSERT(m_pDeviceInformation);
    UA_ASSERT(m_pIpSetting);
    UA_ASSERT(m_pNETCONF);
    UA_ASSERT(m_pRESTful);
    UA_ASSERT(m_pSNMP);
    UA_ASSERT(m_pAlias);
    UA_ASSERT(m_pDeviceProfileName);
    UA_ASSERT(m_pMacAddress);
}

/** Initialize the object with all member nodes
*/
void DeviceTypeBase::initialize()
{
    OpcUa_Int16 nsIdx = m_pNodeConfig->getNameSpaceIndex();
    UaStatus      addStatus;
    UaVariant     defaultValue;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }
    m_pConnectionAccount = NULL;
    m_pDeviceInformation = NULL;
    m_pIpSetting = NULL;
    m_pNETCONF = NULL;
    m_pRESTful = NULL;
    m_pSNMP = NULL;
    m_pAlias = NULL;
    m_pDeviceProfileName = NULL;
    m_pMacAddress = NULL;
    // Mandatory variable Alias
    m_pAlias = new OpcUa::BaseDataVariableType(this, s_pAlias, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pAlias, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

    // Object ConnectionAccount
    m_pConnectionAccount = new MoxaClassBased::ConnectionAccountType(UaNodeId(UaString("%1.ConnectionAccount").arg(nodeId().toString()), nsIdx), s_pConnectionAccount, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pConnectionAccount, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Object DeviceInformation
    m_pDeviceInformation = new MoxaClassBased::DeviceInformationType(UaNodeId(UaString("%1.DeviceInformation").arg(nodeId().toString()), nsIdx), s_pDeviceInformation, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pDeviceInformation, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Mandatory variable DeviceProfileName
    m_pDeviceProfileName = new OpcUa::BaseDataVariableType(this, s_pDeviceProfileName, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pDeviceProfileName, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

    // Object IpSetting
    m_pIpSetting = new MoxaClassBased::IpSettingType(UaNodeId(UaString("%1.IpSetting").arg(nodeId().toString()), nsIdx), s_pIpSetting, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pIpSetting, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Mandatory variable MacAddress
    m_pMacAddress = new OpcUa::BaseDataVariableType(this, s_pMacAddress, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pMacAddress, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

    // Object NETCONF
    m_pNETCONF = new MoxaClassBased::NETCONFType(UaNodeId(UaString("%1.NETCONF").arg(nodeId().toString()), nsIdx), s_pNETCONF, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pNETCONF, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Object RESTful
    m_pRESTful = new MoxaClassBased::RESTfulType(UaNodeId(UaString("%1.RESTful").arg(nodeId().toString()), nsIdx), s_pRESTful, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pRESTful, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Object SNMP
    m_pSNMP = new MoxaClassBased::SNMPType(UaNodeId(UaString("%1.SNMP").arg(nodeId().toString()), nsIdx), s_pSNMP, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pSNMP, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

}

/** Destruction
*/
DeviceTypeBase::~DeviceTypeBase()
{
}

/** Create the related type nodes
*/
void DeviceTypeBase::createTypes()
{
    if ( s_typeNodesCreated == false )
    {
        s_typeNodesCreated = true;

        UaStatus      addStatus;
        UaVariant     defaultValue;
        NodeManagerRoot* pNodeManagerRoot = NodeManagerRoot::CreateRootNodeManager();
        OpcUa_Int16 nsTypeIdx = NodeManagerMoxaClassBasedNS::getTypeNamespace();
        OpcUa_Int16 nsSuperTypeIdx = NodeManagerRoot::getTypeNamespace();
        NodeManagerConfig* pTypeNodeConfig = pNodeManagerRoot->getNodeManagerByNamespace(nsTypeIdx)->getNodeManagerConfig();

        OpcUa::GenericObjectType* pObjectType;
        pObjectType = new OpcUa::GenericObjectType(
            UaNodeId(MoxaClassBasedId_DeviceType, nsTypeIdx),
            UaQualifiedName("DeviceType", nsTypeIdx),
            UaLocalizedText("", "DeviceType"),
            UaLocalizedText("", ""),
            OpcUa_False,
            &DeviceType::clearStaticMembers);
        addStatus = pTypeNodeConfig->addNodeAndReference(UaNodeId(OpcUaId_BaseObjectType, nsSuperTypeIdx), pObjectType, OpcUaId_HasSubtype);
        UA_ASSERT(addStatus.isGood());
        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_DeviceType_ConnectionAccount, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("ConnectionAccount", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "ConnectionAccount"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_ConnectionAccount_UserName, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("UserName", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "UserName"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_String);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;
        MoxaClassBased::InstanceFactoryMoxaClassBasedNS factoryMoxaClassBasedNS(MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace());
        factory.addNamespace(&factoryMoxaClassBasedNS);

            s_pConnectionAccount = new MoxaClassBased::ConnectionAccountType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pConnectionAccount, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pConnectionAccount->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_DeviceType_DeviceInformation, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("DeviceInformation", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "DeviceInformation"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_DeviceInformation_FirmwareVersion, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("FirmwareVersion", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "FirmwareVersion"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_String);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;
        MoxaClassBased::InstanceFactoryMoxaClassBasedNS factoryMoxaClassBasedNS(MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace());
        factory.addNamespace(&factoryMoxaClassBasedNS);

            s_pDeviceInformation = new MoxaClassBased::DeviceInformationType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pDeviceInformation, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pDeviceInformation->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_DeviceType_IpSetting, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("IpSetting", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "IpSetting"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_IpSetting_DNS1, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("DNS1", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "DNS1"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_String);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_IpSetting_DNS2, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("DNS2", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "DNS2"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_String);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_IpSetting_Gateway, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("Gateway", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "Gateway"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_String);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_IpSetting_IpAddress, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("IpAddress", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "IpAddress"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_String);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_IpSetting_SubnetMask, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("SubnetMask", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "SubnetMask"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_String);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;
        MoxaClassBased::InstanceFactoryMoxaClassBasedNS factoryMoxaClassBasedNS(MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace());
        factory.addNamespace(&factoryMoxaClassBasedNS);

            s_pIpSetting = new MoxaClassBased::IpSettingType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pIpSetting, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pIpSetting->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_DeviceType_NETCONF, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("NETCONF", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "NETCONF"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_NETCONF_SSHPort, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("SSHPort", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "SSHPort"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt16);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_NETCONF_Status, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("Status", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "Status"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_Boolean);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;
        MoxaClassBased::InstanceFactoryMoxaClassBasedNS factoryMoxaClassBasedNS(MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace());
        factory.addNamespace(&factoryMoxaClassBasedNS);

            s_pNETCONF = new MoxaClassBased::NETCONFType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pNETCONF, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pNETCONF->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_DeviceType_RESTful, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("RESTful", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "RESTful"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_RESTful_Port, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("Port", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "Port"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt16);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_RESTful_Status, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("Status", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "Status"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_Boolean);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;
        MoxaClassBased::InstanceFactoryMoxaClassBasedNS factoryMoxaClassBasedNS(MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace());
        factory.addNamespace(&factoryMoxaClassBasedNS);

            s_pRESTful = new MoxaClassBased::RESTfulType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pRESTful, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pRESTful->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_DeviceType_SNMP, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("SNMP", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "SNMP"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_SNMP_Port, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("Port", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "Port"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt16);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_SNMP_Status, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("Status", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "Status"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_Boolean);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_DeviceType_SNMP_Version, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("Version", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
                pChild2->setDisplayName(UaLocalizedText("", "Version"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(3);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(UaNodeId(MoxaClassBasedId_SNMPVersion, nsTypeIdx));
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_BaseDataVariableType);
                reference.setReferenceTypeId(OpcUaId_HasComponent);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;
        MoxaClassBased::InstanceFactoryMoxaClassBasedNS factoryMoxaClassBasedNS(MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace());
        factory.addNamespace(&factoryMoxaClassBasedNS);

            s_pSNMP = new MoxaClassBased::SNMPType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pSNMP, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pSNMP->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }


        // Mandatory variable Alias
        defaultValue.setString("");
        s_pAlias = new OpcUa::BaseDataVariableType(UaNodeId(MoxaClassBasedId_DeviceType_Alias, nsTypeIdx), "Alias", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pAlias->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pAlias->setValueRank(-1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pAlias, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

        // Mandatory variable DeviceProfileName
        defaultValue.setString("");
        s_pDeviceProfileName = new OpcUa::BaseDataVariableType(UaNodeId(MoxaClassBasedId_DeviceType_DeviceProfileName, nsTypeIdx), "DeviceProfileName", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pDeviceProfileName->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pDeviceProfileName->setValueRank(-1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pDeviceProfileName, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

        // Mandatory variable MacAddress
        defaultValue.setString("");
        s_pMacAddress = new OpcUa::BaseDataVariableType(UaNodeId(MoxaClassBasedId_DeviceType_MacAddress, nsTypeIdx), "MacAddress", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pMacAddress->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pMacAddress->setValueRank(-1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pMacAddress, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

    }
}

/** Clear the static members of the class
*/
void DeviceTypeBase::clearStaticMembers()
{
    s_typeNodesCreated = false;

    s_pConnectionAccount = NULL;
    s_pDeviceInformation = NULL;
    s_pIpSetting = NULL;
    s_pNETCONF = NULL;
    s_pRESTful = NULL;
    s_pSNMP = NULL;
    s_pAlias = NULL;
    s_pDeviceProfileName = NULL;
    s_pMacAddress = NULL;
}

/** Returns the type definition NodeId for the DeviceType
*/
UaNodeId DeviceTypeBase::typeDefinitionId() const
{
    UaNodeId ret(MoxaClassBasedId_DeviceType, NodeManagerMoxaClassBasedNS::getTypeNamespace());
    return ret;
}

/**
 *  Sets the Alias value
 */
void DeviceTypeBase::setAlias(const UaString& Alias)
{
    UaVariant value;
    value.setString(Alias);
    UaDataValue dataValue;
    dataValue.setValue(value, OpcUa_True, OpcUa_True);
    m_pAlias->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Returns the value of Alias
 */
UaString DeviceTypeBase::getAlias() const
{
    UaVariant defaultValue;
    UaString ret;
    UaDataValue dataValue(m_pAlias->value(NULL));
    defaultValue = *dataValue.value();
    ret = defaultValue.toString();
    return ret;
}

/**
 *  Sets the DeviceProfileName value
 */
void DeviceTypeBase::setDeviceProfileName(const UaString& DeviceProfileName)
{
    UaVariant value;
    value.setString(DeviceProfileName);
    UaDataValue dataValue;
    dataValue.setValue(value, OpcUa_True, OpcUa_True);
    m_pDeviceProfileName->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Returns the value of DeviceProfileName
 */
UaString DeviceTypeBase::getDeviceProfileName() const
{
    UaVariant defaultValue;
    UaString ret;
    UaDataValue dataValue(m_pDeviceProfileName->value(NULL));
    defaultValue = *dataValue.value();
    ret = defaultValue.toString();
    return ret;
}

/**
 *  Sets the MacAddress value
 */
void DeviceTypeBase::setMacAddress(const UaString& MacAddress)
{
    UaVariant value;
    value.setString(MacAddress);
    UaDataValue dataValue;
    dataValue.setValue(value, OpcUa_True, OpcUa_True);
    m_pMacAddress->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Returns the value of MacAddress
 */
UaString DeviceTypeBase::getMacAddress() const
{
    UaVariant defaultValue;
    UaString ret;
    UaDataValue dataValue(m_pMacAddress->value(NULL));
    defaultValue = *dataValue.value();
    ret = defaultValue.toString();
    return ret;
}

/** Returns the Alias node.
 */
OpcUa::BaseDataVariableType* DeviceTypeBase::getAliasNode()
{
    return m_pAlias;
}

/** Returns the Alias node.
 */
const OpcUa::BaseDataVariableType* DeviceTypeBase::getAliasNode() const
{
    return m_pAlias;
}

/** Returns the ConnectionAccount node.
 */
MoxaClassBased::ConnectionAccountType* DeviceTypeBase::getConnectionAccount()
{
    return m_pConnectionAccount;
}

/** Returns the ConnectionAccount node.
 */
const MoxaClassBased::ConnectionAccountType* DeviceTypeBase::getConnectionAccount() const
{
    return m_pConnectionAccount;
}

/** Returns the DeviceInformation node.
 */
MoxaClassBased::DeviceInformationType* DeviceTypeBase::getDeviceInformation()
{
    return m_pDeviceInformation;
}

/** Returns the DeviceInformation node.
 */
const MoxaClassBased::DeviceInformationType* DeviceTypeBase::getDeviceInformation() const
{
    return m_pDeviceInformation;
}

/** Returns the DeviceProfileName node.
 */
OpcUa::BaseDataVariableType* DeviceTypeBase::getDeviceProfileNameNode()
{
    return m_pDeviceProfileName;
}

/** Returns the DeviceProfileName node.
 */
const OpcUa::BaseDataVariableType* DeviceTypeBase::getDeviceProfileNameNode() const
{
    return m_pDeviceProfileName;
}

/** Returns the IpSetting node.
 */
MoxaClassBased::IpSettingType* DeviceTypeBase::getIpSetting()
{
    return m_pIpSetting;
}

/** Returns the IpSetting node.
 */
const MoxaClassBased::IpSettingType* DeviceTypeBase::getIpSetting() const
{
    return m_pIpSetting;
}

/** Returns the MacAddress node.
 */
OpcUa::BaseDataVariableType* DeviceTypeBase::getMacAddressNode()
{
    return m_pMacAddress;
}

/** Returns the MacAddress node.
 */
const OpcUa::BaseDataVariableType* DeviceTypeBase::getMacAddressNode() const
{
    return m_pMacAddress;
}

/** Returns the NETCONF node.
 */
MoxaClassBased::NETCONFType* DeviceTypeBase::getNETCONF()
{
    return m_pNETCONF;
}

/** Returns the NETCONF node.
 */
const MoxaClassBased::NETCONFType* DeviceTypeBase::getNETCONF() const
{
    return m_pNETCONF;
}

/** Returns the RESTful node.
 */
MoxaClassBased::RESTfulType* DeviceTypeBase::getRESTful()
{
    return m_pRESTful;
}

/** Returns the RESTful node.
 */
const MoxaClassBased::RESTfulType* DeviceTypeBase::getRESTful() const
{
    return m_pRESTful;
}

/** Returns the SNMP node.
 */
MoxaClassBased::SNMPType* DeviceTypeBase::getSNMP()
{
    return m_pSNMP;
}

/** Returns the SNMP node.
 */
const MoxaClassBased::SNMPType* DeviceTypeBase::getSNMP() const
{
    return m_pSNMP;
}


/** Uses the NodeAccessInfo of pOther and its children. */
void DeviceTypeBase::useAccessInfoFromInstance(DeviceTypeBase *pOther)
{
    OpcUa::BaseObjectType::useAccessInfoFromInstance(pOther);

    // children
    m_pConnectionAccount->useAccessInfoFromInstance(pOther->m_pConnectionAccount);
    m_pDeviceInformation->useAccessInfoFromInstance(pOther->m_pDeviceInformation);
    m_pIpSetting->useAccessInfoFromInstance(pOther->m_pIpSetting);
    m_pNETCONF->useAccessInfoFromInstance(pOther->m_pNETCONF);
    m_pRESTful->useAccessInfoFromInstance(pOther->m_pRESTful);
    m_pSNMP->useAccessInfoFromInstance(pOther->m_pSNMP);
    m_pAlias->useAccessInfoFromInstance(pOther->m_pAlias);
    m_pDeviceProfileName->useAccessInfoFromInstance(pOther->m_pDeviceProfileName);
    m_pMacAddress->useAccessInfoFromInstance(pOther->m_pMacAddress);
}

/** Set the NodeAccessInfo for this node and all of its children. */
void DeviceTypeBase::setAccessInfoWithChildren(NodeAccessInfo* pNodeAccessInfo)
{
    OpcUa::BaseObjectType::setAccessInfoWithChildren(pNodeAccessInfo);

    // children
    m_pConnectionAccount->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pDeviceInformation->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pIpSetting->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pNETCONF->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pRESTful->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pSNMP->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pAlias->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pDeviceProfileName->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pMacAddress->setAccessInfoWithChildren(pNodeAccessInfo);
}


} // End namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/


