/******************************************************************************
** moxaclassbased_restfuldatatype.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/


#ifndef __MOXACLASSBASED_RESTFULDATATYPE_H__
#define __MOXACLASSBASED_RESTFULDATATYPE_H__

#include <opcua_proxystub.h>

#include "uabase.h"
#include "uaarraytemplates.h"
#include "moxaclassbased_identifiers.h"
#include "moxaclassbased_datatypes.h"

class UaExtensionObject;
class UaVariant;
class UaDataValue;

// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

class MoxaClassBased_EXPORT RESTfulDataTypePrivate;

/**
 *  @brief Wrapper class for the UA stack structure MoxaClassBased_RESTfulDataType.
 *
 *  This class encapsulates the native MoxaClassBased_RESTfulDataType structure
 *  and handles memory allocation and cleanup for you.
 *  RESTfulDataType uses implicit sharing to avoid needless copying and to boost the performance.
 *  Only if you modify a shared RESTfulDataType it creates a copy for that (copy-on-write).
 *  So assigning another RESTfulDataType or passing it as parameter needs constant time and is nearly as fast as assigning a pointer.
 */
class MoxaClassBased_EXPORT RESTfulDataType
{
    MOXACLASSBASED_DECLARE_PRIVATE(RESTfulDataType)
public:
    RESTfulDataType();
    RESTfulDataType(const RESTfulDataType &other);
    RESTfulDataType(const MoxaClassBased_RESTfulDataType &other);
    RESTfulDataType(const UaExtensionObject &extensionObject);
    RESTfulDataType(const OpcUa_ExtensionObject &extensionObject);
    RESTfulDataType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach);
    RESTfulDataType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach);
    ~RESTfulDataType();

    void clear();

    bool operator==(const RESTfulDataType &other) const;
    bool operator!=(const RESTfulDataType &other) const;

    RESTfulDataType& operator=(const RESTfulDataType &other);

    MoxaClassBased_RESTfulDataType* copy() const;
    void copyTo(MoxaClassBased_RESTfulDataType *pDst) const;

    static MoxaClassBased_RESTfulDataType* clone(const MoxaClassBased_RESTfulDataType& source);
    static void cloneTo(const MoxaClassBased_RESTfulDataType& source, MoxaClassBased_RESTfulDataType& copy);

    void attach(const MoxaClassBased_RESTfulDataType *pValue);
    MoxaClassBased_RESTfulDataType* detach(MoxaClassBased_RESTfulDataType* pDst);

    void toVariant(UaVariant &variant) const;
    void toVariant(OpcUa_Variant &variant) const;
    void toVariant(UaVariant &variant, OpcUa_Boolean bDetach);
    void toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach);

    void toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const;
    void toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const;
    void toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps);
    void toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps);

    void toExtensionObject(UaExtensionObject &extensionObject) const;
    void toExtensionObject(OpcUa_ExtensionObject &extensionObject) const;
    void toExtensionObject(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach);
    void toExtensionObject(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach);

    OpcUa_StatusCode setRESTfulDataType(const UaExtensionObject &extensionObject);
    OpcUa_StatusCode setRESTfulDataType(const OpcUa_ExtensionObject &extensionObject);
    OpcUa_StatusCode setRESTfulDataType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach);
    OpcUa_StatusCode setRESTfulDataType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach);

    bool isPortSet() const;
    OpcUa_UInt16 getPort(bool *ok = 0) const;

    void setPort(OpcUa_UInt16 Port);
    void unsetPort();
};

class MoxaClassBased_EXPORT RESTfulDataTypes
{
public:
    RESTfulDataTypes();
    RESTfulDataTypes(const RESTfulDataTypes &other);
    RESTfulDataTypes(OpcUa_Int32 length, MoxaClassBased_RESTfulDataType* data);
    virtual ~RESTfulDataTypes();

    RESTfulDataTypes& operator=(const RESTfulDataTypes &other);
    MoxaClassBased_RESTfulDataType& operator[](OpcUa_UInt32 index);
    const MoxaClassBased_RESTfulDataType& operator[](OpcUa_UInt32 index) const;

    void attach(OpcUa_UInt32 length, MoxaClassBased_RESTfulDataType* data);
    void attach(OpcUa_Int32 length, MoxaClassBased_RESTfulDataType* data);
    MoxaClassBased_RESTfulDataType* detach();

    bool operator==(const RESTfulDataTypes &other) const;
    bool operator!=(const RESTfulDataTypes &other) const;

    void create(OpcUa_UInt32 length);
    void resize(OpcUa_UInt32 length);
    void clear();

    inline OpcUa_UInt32 length() const {return m_noOfElements;}
    inline const MoxaClassBased_RESTfulDataType* rawData() const {return m_data;}
    inline MoxaClassBased_RESTfulDataType* rawData() {return m_data;}
    void toVariant(UaVariant &variant) const;
    void toVariant(OpcUa_Variant &variant) const;
    void toVariant(UaVariant &variant, OpcUa_Boolean bDetach);
    void toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach);

    void toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const;
    void toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const;
    void toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps);
    void toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps);

    OpcUa_StatusCode setRESTfulDataTypes(const UaVariant &variant);
    OpcUa_StatusCode setRESTfulDataTypes(const OpcUa_Variant &variant);
    OpcUa_StatusCode setRESTfulDataTypes(UaVariant &variant, OpcUa_Boolean bDetach);
    OpcUa_StatusCode setRESTfulDataTypes(OpcUa_Variant &variant, OpcUa_Boolean bDetach);
    OpcUa_StatusCode setRESTfulDataTypes(OpcUa_Int32 length, MoxaClassBased_RESTfulDataType* data);

    static RESTfulDataTypes empty;
private:
    OpcUa_UInt32 m_noOfElements;
    MoxaClassBased_RESTfulDataType* m_data;
};

} // namespace MoxaClassBased

#endif // __MOXACLASSBASED_RESTFULDATATYPE_H__

