/******************************************************************************
** moxaclassbased_programstatemachinetypebase.cpp
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#include "moxaclassbased_programstatemachinetypebase.h"
#include "moxaclassbased_programstatemachinetype.h"
#include "uagenericnodes.h"
#include "nodemanagerroot.h"
#include "methodhandleuanode.h"
#include "moxaclassbased_nodemanagermoxaclassbasedns.h"

#include "instancefactory.h"
#include "opcua_extensionobject.h"
#include "opcua_finitestatevariabletype.h"
#include "opcua_finitetransitionvariabletype.h"
// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

bool ProgramStateMachineTypeBase::s_typeNodesCreated = false;
OpcUa::StateType* ProgramStateMachineTypeBase::s_pCompleted = NULL;
OpcUa::TransitionType* ProgramStateMachineTypeBase::s_pCompletedToRunning = NULL;
OpcUa::StateType* ProgramStateMachineTypeBase::s_pFailed = NULL;
OpcUa::TransitionType* ProgramStateMachineTypeBase::s_pFailedToRunning = NULL;
OpcUa::StateType* ProgramStateMachineTypeBase::s_pReady = NULL;
OpcUa::TransitionType* ProgramStateMachineTypeBase::s_pReadyToRunning = NULL;
OpcUa::StateType* ProgramStateMachineTypeBase::s_pRunning = NULL;
OpcUa::TransitionType* ProgramStateMachineTypeBase::s_pRunningToCompleted = NULL;
OpcUa::TransitionType* ProgramStateMachineTypeBase::s_pRunningToFailed = NULL;
OpcUa::TransitionType* ProgramStateMachineTypeBase::s_pRunningToReady = NULL;
OpcUa::BaseDataVariableType* ProgramStateMachineTypeBase::s_pErrorCode = NULL;
OpcUa::BaseDataVariableType* ProgramStateMachineTypeBase::s_pErrorMessage = NULL;

/** Constructs an ProgramStateMachineType object using an instance declaration node as base
*/
ProgramStateMachineTypeBase::ProgramStateMachineTypeBase(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: OpcUa::FiniteStateMachineType(nodeId, pInstanceDeclarationObject, pNodeConfig, pSharedMutex)
{
    initialize();
}

/** Constructs an ProgramStateMachineType object
*/
ProgramStateMachineTypeBase::ProgramStateMachineTypeBase(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: OpcUa::FiniteStateMachineType(nodeId, name, browseNameNameSpaceIndex, pNodeConfig, pSharedMutex)
{
    initialize();
}

/**  Constructs an instance of the class ProgramStateMachineTypeBase with all components
*/
ProgramStateMachineTypeBase::ProgramStateMachineTypeBase(
    UaBase::Object*    pBaseNode,    //!< [in] The "tree" of nodes that specifies the attributes of the instance and its children
    XmlUaNodeFactoryManager* pFactory, //!< [in] The factory to create the children
    NodeManagerConfig* pNodeConfig,  //!< [in] Interface pointer to the NodeManagerConfig interface used to add and delete node and references in the address space
    UaMutexRefCounted* pSharedMutex) //!< [in] Shared mutex object used to synchronize access to the variable. Can be NULL if no shared mutex is provided
: OpcUa::FiniteStateMachineType(pBaseNode, pFactory, pNodeConfig, pSharedMutex)
{
    UaStatus      addStatus;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }

    m_pCompleted = NULL;
    m_pCompletedToRunning = NULL;
    m_pFailed = NULL;
    m_pFailedToRunning = NULL;
    m_pReady = NULL;
    m_pReadyToRunning = NULL;
    m_pRunning = NULL;
    m_pRunningToCompleted = NULL;
    m_pRunningToFailed = NULL;
    m_pRunningToReady = NULL;
    m_pErrorCode = NULL;
    m_pErrorMessage = NULL;

    std::list<UaBase::BaseNode*> lstReferencedNodes = pBaseNode->hierarchicallyReferencedNodes();
    for (std::list<UaBase::BaseNode*>::const_iterator it = lstReferencedNodes.begin(); it != lstReferencedNodes.end(); it++)
    {
        UaBase::BaseNode *pChild = *it;
        if (pChild->browseName() == UaQualifiedName("ErrorCode", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pErrorCode)
            {
                m_pErrorCode = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pErrorCode, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pErrorCode->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("ErrorMessage", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pErrorMessage)
            {
                m_pErrorMessage = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pErrorMessage, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pErrorMessage->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("Completed", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pCompleted)
            {
                m_pCompleted = (OpcUa::StateType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pCompleted, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pCompleted->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("CompletedToRunning", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pCompletedToRunning)
            {
                m_pCompletedToRunning = (OpcUa::TransitionType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pCompletedToRunning, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pCompletedToRunning->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("Failed", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pFailed)
            {
                m_pFailed = (OpcUa::StateType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pFailed, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pFailed->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("FailedToRunning", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pFailedToRunning)
            {
                m_pFailedToRunning = (OpcUa::TransitionType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pFailedToRunning, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pFailedToRunning->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("Ready", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pReady)
            {
                m_pReady = (OpcUa::StateType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pReady, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pReady->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("ReadyToRunning", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pReadyToRunning)
            {
                m_pReadyToRunning = (OpcUa::TransitionType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pReadyToRunning, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pReadyToRunning->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("Running", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pRunning)
            {
                m_pRunning = (OpcUa::StateType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pRunning, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pRunning->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("RunningToCompleted", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pRunningToCompleted)
            {
                m_pRunningToCompleted = (OpcUa::TransitionType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pRunningToCompleted, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pRunningToCompleted->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("RunningToFailed", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pRunningToFailed)
            {
                m_pRunningToFailed = (OpcUa::TransitionType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pRunningToFailed, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pRunningToFailed->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("RunningToReady", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pRunningToReady)
            {
                m_pRunningToReady = (OpcUa::TransitionType*) pFactory->createObject((UaBase::Object*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pRunningToReady, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Object*)pChild)->modellingRuleId().isNull())
                {
                    m_pRunningToReady->setModellingRuleId(((UaBase::Object*)pChild)->modellingRuleId());
                }
            }
        }
    }
    UA_ASSERT(m_pCompleted);
    UA_ASSERT(m_pCompletedToRunning);
    UA_ASSERT(m_pFailed);
    UA_ASSERT(m_pFailedToRunning);
    UA_ASSERT(m_pReady);
    UA_ASSERT(m_pReadyToRunning);
    UA_ASSERT(m_pRunning);
    UA_ASSERT(m_pRunningToCompleted);
    UA_ASSERT(m_pRunningToFailed);
    UA_ASSERT(m_pRunningToReady);
    UA_ASSERT(m_pErrorCode);
    UA_ASSERT(m_pErrorMessage);
}

/** Initialize the object with all member nodes
*/
void ProgramStateMachineTypeBase::initialize()
{
    OpcUa_Int16 nsIdx = m_pNodeConfig->getNameSpaceIndex();
    UaStatus      addStatus;
    UaVariant     defaultValue;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }
    m_pCompleted = NULL;
    m_pCompletedToRunning = NULL;
    m_pFailed = NULL;
    m_pFailedToRunning = NULL;
    m_pReady = NULL;
    m_pReadyToRunning = NULL;
    m_pRunning = NULL;
    m_pRunningToCompleted = NULL;
    m_pRunningToFailed = NULL;
    m_pRunningToReady = NULL;
    m_pErrorCode = NULL;
    m_pErrorMessage = NULL;
    // Object Completed
    m_pCompleted = new OpcUa::StateType(UaNodeId(UaString("%1.Completed").arg(nodeId().toString()), nsIdx), s_pCompleted, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pCompleted, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Object CompletedToRunning
    m_pCompletedToRunning = new OpcUa::TransitionType(UaNodeId(UaString("%1.CompletedToRunning").arg(nodeId().toString()), nsIdx), s_pCompletedToRunning, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pCompletedToRunning, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Mandatory variable ErrorCode
    m_pErrorCode = new OpcUa::BaseDataVariableType(this, s_pErrorCode, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pErrorCode, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

    // Mandatory variable ErrorMessage
    m_pErrorMessage = new OpcUa::BaseDataVariableType(this, s_pErrorMessage, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pErrorMessage, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

    // Object Failed
    m_pFailed = new OpcUa::StateType(UaNodeId(UaString("%1.Failed").arg(nodeId().toString()), nsIdx), s_pFailed, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pFailed, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Object FailedToRunning
    m_pFailedToRunning = new OpcUa::TransitionType(UaNodeId(UaString("%1.FailedToRunning").arg(nodeId().toString()), nsIdx), s_pFailedToRunning, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pFailedToRunning, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Object Ready
    m_pReady = new OpcUa::StateType(UaNodeId(UaString("%1.Ready").arg(nodeId().toString()), nsIdx), s_pReady, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pReady, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Object ReadyToRunning
    m_pReadyToRunning = new OpcUa::TransitionType(UaNodeId(UaString("%1.ReadyToRunning").arg(nodeId().toString()), nsIdx), s_pReadyToRunning, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pReadyToRunning, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Object Running
    m_pRunning = new OpcUa::StateType(UaNodeId(UaString("%1.Running").arg(nodeId().toString()), nsIdx), s_pRunning, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pRunning, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Object RunningToCompleted
    m_pRunningToCompleted = new OpcUa::TransitionType(UaNodeId(UaString("%1.RunningToCompleted").arg(nodeId().toString()), nsIdx), s_pRunningToCompleted, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pRunningToCompleted, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Object RunningToFailed
    m_pRunningToFailed = new OpcUa::TransitionType(UaNodeId(UaString("%1.RunningToFailed").arg(nodeId().toString()), nsIdx), s_pRunningToFailed, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pRunningToFailed, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // Object RunningToReady
    m_pRunningToReady = new OpcUa::TransitionType(UaNodeId(UaString("%1.RunningToReady").arg(nodeId().toString()), nsIdx), s_pRunningToReady, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pRunningToReady, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

    setCurrentState(s_pCompleted->displayName(NULL));
    getCurrentStateNode()->setIdNodeId(s_pCompleted->nodeId());
}

/** Destruction
*/
ProgramStateMachineTypeBase::~ProgramStateMachineTypeBase()
{
}

/** Create the related type nodes
*/
void ProgramStateMachineTypeBase::createTypes()
{
    if ( s_typeNodesCreated == false )
    {
        s_typeNodesCreated = true;

        // Check if supertype is already created
        OpcUa::FiniteStateMachineType::createTypes();

        UaStatus      addStatus;
        UaVariant     defaultValue;
        NodeManagerRoot* pNodeManagerRoot = NodeManagerRoot::CreateRootNodeManager();
        OpcUa_Int16 nsTypeIdx = NodeManagerMoxaClassBasedNS::getTypeNamespace();
        OpcUa_Int16 nsSuperTypeIdx = NodeManagerRoot::getTypeNamespace();
        NodeManagerConfig* pTypeNodeConfig = pNodeManagerRoot->getNodeManagerByNamespace(nsTypeIdx)->getNodeManagerConfig();

        OpcUa::GenericObjectType* pObjectType;
        pObjectType = new OpcUa::GenericObjectType(
            UaNodeId(MoxaClassBasedId_ProgramStateMachineType, nsTypeIdx),
            UaQualifiedName("ProgramStateMachineType", nsTypeIdx),
            UaLocalizedText("", "ProgramStateMachineType"),
            UaLocalizedText("", ""),
            OpcUa_False,
            &ProgramStateMachineType::clearStaticMembers);
        addStatus = pTypeNodeConfig->addNodeAndReference(UaNodeId(OpcUaId_FiniteStateMachineType, nsSuperTypeIdx), pObjectType, OpcUaId_HasSubtype);
        UA_ASSERT(addStatus.isGood());
        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_Completed, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("Completed", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "Completed"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_Completed_StateNumber, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("StateNumber", 0));
                pChild2->setDisplayName(UaLocalizedText("", "StateNumber"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(1);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt32);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_PropertyType);
                reference.setReferenceTypeId(OpcUaId_HasProperty);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;

            s_pCompleted = new OpcUa::StateType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pCompleted, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pCompleted->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_CompletedToRunning, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("CompletedToRunning", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "CompletedToRunning"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_CompletedToRunning_TransitionNumber, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("TransitionNumber", 0));
                pChild2->setDisplayName(UaLocalizedText("", "TransitionNumber"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(1);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt32);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_PropertyType);
                reference.setReferenceTypeId(OpcUaId_HasProperty);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;

            s_pCompletedToRunning = new OpcUa::TransitionType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pCompletedToRunning, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pCompletedToRunning->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_Failed, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("Failed", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "Failed"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_Failed_StateNumber, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("StateNumber", 0));
                pChild2->setDisplayName(UaLocalizedText("", "StateNumber"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(1);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt32);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_PropertyType);
                reference.setReferenceTypeId(OpcUaId_HasProperty);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;

            s_pFailed = new OpcUa::StateType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pFailed, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pFailed->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_FailedToRunning, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("FailedToRunning", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "FailedToRunning"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_FailedToRunning_TransitionNumber, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("TransitionNumber", 0));
                pChild2->setDisplayName(UaLocalizedText("", "TransitionNumber"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(1);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt32);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_PropertyType);
                reference.setReferenceTypeId(OpcUaId_HasProperty);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;

            s_pFailedToRunning = new OpcUa::TransitionType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pFailedToRunning, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pFailedToRunning->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_Ready, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("Ready", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "Ready"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_Ready_StateNumber, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("StateNumber", 0));
                pChild2->setDisplayName(UaLocalizedText("", "StateNumber"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(1);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt32);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_PropertyType);
                reference.setReferenceTypeId(OpcUaId_HasProperty);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;

            s_pReady = new OpcUa::StateType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pReady, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pReady->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_ReadyToRunning, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("ReadyToRunning", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "ReadyToRunning"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_ReadyToRunning_TransitionNumber, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("TransitionNumber", 0));
                pChild2->setDisplayName(UaLocalizedText("", "TransitionNumber"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(1);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt32);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_PropertyType);
                reference.setReferenceTypeId(OpcUaId_HasProperty);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;

            s_pReadyToRunning = new OpcUa::TransitionType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pReadyToRunning, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pReadyToRunning->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_Running, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("Running", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "Running"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_Running_StateNumber, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("StateNumber", 0));
                pChild2->setDisplayName(UaLocalizedText("", "StateNumber"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(1);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt32);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_PropertyType);
                reference.setReferenceTypeId(OpcUaId_HasProperty);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;

            s_pRunning = new OpcUa::StateType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pRunning, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pRunning->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_RunningToCompleted, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("RunningToCompleted", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "RunningToCompleted"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_RunningToCompleted_TransitionNumber, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("TransitionNumber", 0));
                pChild2->setDisplayName(UaLocalizedText("", "TransitionNumber"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(1);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt32);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_PropertyType);
                reference.setReferenceTypeId(OpcUaId_HasProperty);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;

            s_pRunningToCompleted = new OpcUa::TransitionType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pRunningToCompleted, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pRunningToCompleted->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_RunningToFailed, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("RunningToFailed", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "RunningToFailed"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_RunningToFailed_TransitionNumber, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("TransitionNumber", 0));
                pChild2->setDisplayName(UaLocalizedText("", "TransitionNumber"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(1);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt32);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_PropertyType);
                reference.setReferenceTypeId(OpcUaId_HasProperty);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;

            s_pRunningToFailed = new OpcUa::TransitionType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pRunningToFailed, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pRunningToFailed->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }

        {
            std::list<UaBase::BaseNode*> lstBaseNodes;
            UaBase::Object *pChild = new UaBase::Object(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_RunningToReady, nsTypeIdx));
            lstBaseNodes.push_back(pChild);
            pChild->setBrowseName(UaQualifiedName("RunningToReady", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
            pChild->setDisplayName(UaLocalizedText("", "RunningToReady"));
            {
                UaBase::BaseNode *pParent = pChild;
                UaBase::BaseNode *pChild2;
                UaBase::FullReference reference;
                pChild2 = new UaBase::Variable(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_RunningToReady_TransitionNumber, nsTypeIdx));
                lstBaseNodes.push_back(pChild2);
                pChild2->setBrowseName(UaQualifiedName("TransitionNumber", 0));
                pChild2->setDisplayName(UaLocalizedText("", "TransitionNumber"));
                ((UaBase::Variable*)pChild2)->setAccessLevel(1);
                ((UaBase::Variable*)pChild2)->setValueRank(-1);
                ((UaBase::Variable*)pChild2)->setDataTypeId(OpcUaId_UInt32);
                ((UaBase::Variable*)pChild2)->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
                ((UaBase::Variable*)pChild2)->setTypeDefinitionId(OpcUaId_PropertyType);
                reference.setReferenceTypeId(OpcUaId_HasProperty);
                reference.setSourceNode(pParent);
                reference.setTargetNode(pChild2);
                pParent->addFullReference(reference);
                pChild2->addFullReference(reference);
                pChild2->setParentNodeId(pParent->nodeId());
            }

            XmlUaNodeFactoryManager factory;

            s_pRunningToReady = new OpcUa::TransitionType(pChild, &factory, pTypeNodeConfig, NULL);
            addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pRunningToReady, OpcUaId_HasComponent);
            UA_ASSERT(addStatus.isGood());
            s_pRunningToReady->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
            std::list<UaBase::BaseNode*>::iterator it = lstBaseNodes.begin();
            while (it != lstBaseNodes.end())
            {
                delete *it;
                it++;
            }
        }


        // Mandatory variable ErrorCode
        defaultValue.setUInt32(0);
        s_pErrorCode = new OpcUa::BaseDataVariableType(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_ErrorCode, nsTypeIdx), "ErrorCode", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pErrorCode->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pErrorCode->setValueRank(-1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pErrorCode, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

        // Mandatory variable ErrorMessage
        defaultValue.setString("");
        s_pErrorMessage = new OpcUa::BaseDataVariableType(UaNodeId(MoxaClassBasedId_ProgramStateMachineType_ErrorMessage, nsTypeIdx), "ErrorMessage", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pErrorMessage->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pErrorMessage->setValueRank(-1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pErrorMessage, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

    }
}

/** Clear the static members of the class
*/
void ProgramStateMachineTypeBase::clearStaticMembers()
{
    s_typeNodesCreated = false;

    s_pCompleted = NULL;
    s_pCompletedToRunning = NULL;
    s_pFailed = NULL;
    s_pFailedToRunning = NULL;
    s_pReady = NULL;
    s_pReadyToRunning = NULL;
    s_pRunning = NULL;
    s_pRunningToCompleted = NULL;
    s_pRunningToFailed = NULL;
    s_pRunningToReady = NULL;
    s_pErrorCode = NULL;
    s_pErrorMessage = NULL;
}

/** Returns the type definition NodeId for the ProgramStateMachineType
*/
UaNodeId ProgramStateMachineTypeBase::typeDefinitionId() const
{
    UaNodeId ret(MoxaClassBasedId_ProgramStateMachineType, NodeManagerMoxaClassBasedNS::getTypeNamespace());
    return ret;
}

/**
 *  Sets the ErrorCode value
 */
void ProgramStateMachineTypeBase::setErrorCode(OpcUa_UInt32 ErrorCode)
{
    UaVariant value;
    value.setUInt32(ErrorCode);
    UaDataValue dataValue;
    dataValue.setValue(value, OpcUa_True, OpcUa_True);
    m_pErrorCode->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Returns the value of ErrorCode
 */
OpcUa_UInt32 ProgramStateMachineTypeBase::getErrorCode() const
{
    UaVariant defaultValue;
    OpcUa_UInt32 ret = 0;
    UaDataValue dataValue(m_pErrorCode->value(NULL));
    defaultValue = *dataValue.value();
    defaultValue.toUInt32(ret);
    return ret;
}

/**
 *  Sets the ErrorMessage value
 */
void ProgramStateMachineTypeBase::setErrorMessage(const UaString& ErrorMessage)
{
    UaVariant value;
    value.setString(ErrorMessage);
    UaDataValue dataValue;
    dataValue.setValue(value, OpcUa_True, OpcUa_True);
    m_pErrorMessage->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Returns the value of ErrorMessage
 */
UaString ProgramStateMachineTypeBase::getErrorMessage() const
{
    UaVariant defaultValue;
    UaString ret;
    UaDataValue dataValue(m_pErrorMessage->value(NULL));
    defaultValue = *dataValue.value();
    ret = defaultValue.toString();
    return ret;
}

/** Returns the Completed node.
 */
OpcUa::StateType* ProgramStateMachineTypeBase::getCompleted()
{
    return m_pCompleted;
}

/** Returns the Completed node.
 */
const OpcUa::StateType* ProgramStateMachineTypeBase::getCompleted() const
{
    return m_pCompleted;
}

/** Returns the CompletedToRunning node.
 */
OpcUa::TransitionType* ProgramStateMachineTypeBase::getCompletedToRunning()
{
    return m_pCompletedToRunning;
}

/** Returns the CompletedToRunning node.
 */
const OpcUa::TransitionType* ProgramStateMachineTypeBase::getCompletedToRunning() const
{
    return m_pCompletedToRunning;
}

/** Returns the ErrorCode node.
 */
OpcUa::BaseDataVariableType* ProgramStateMachineTypeBase::getErrorCodeNode()
{
    return m_pErrorCode;
}

/** Returns the ErrorCode node.
 */
const OpcUa::BaseDataVariableType* ProgramStateMachineTypeBase::getErrorCodeNode() const
{
    return m_pErrorCode;
}

/** Returns the ErrorMessage node.
 */
OpcUa::BaseDataVariableType* ProgramStateMachineTypeBase::getErrorMessageNode()
{
    return m_pErrorMessage;
}

/** Returns the ErrorMessage node.
 */
const OpcUa::BaseDataVariableType* ProgramStateMachineTypeBase::getErrorMessageNode() const
{
    return m_pErrorMessage;
}

/** Returns the Failed node.
 */
OpcUa::StateType* ProgramStateMachineTypeBase::getFailed()
{
    return m_pFailed;
}

/** Returns the Failed node.
 */
const OpcUa::StateType* ProgramStateMachineTypeBase::getFailed() const
{
    return m_pFailed;
}

/** Returns the FailedToRunning node.
 */
OpcUa::TransitionType* ProgramStateMachineTypeBase::getFailedToRunning()
{
    return m_pFailedToRunning;
}

/** Returns the FailedToRunning node.
 */
const OpcUa::TransitionType* ProgramStateMachineTypeBase::getFailedToRunning() const
{
    return m_pFailedToRunning;
}

/** Returns the Ready node.
 */
OpcUa::StateType* ProgramStateMachineTypeBase::getReady()
{
    return m_pReady;
}

/** Returns the Ready node.
 */
const OpcUa::StateType* ProgramStateMachineTypeBase::getReady() const
{
    return m_pReady;
}

/** Returns the ReadyToRunning node.
 */
OpcUa::TransitionType* ProgramStateMachineTypeBase::getReadyToRunning()
{
    return m_pReadyToRunning;
}

/** Returns the ReadyToRunning node.
 */
const OpcUa::TransitionType* ProgramStateMachineTypeBase::getReadyToRunning() const
{
    return m_pReadyToRunning;
}

/** Returns the Running node.
 */
OpcUa::StateType* ProgramStateMachineTypeBase::getRunning()
{
    return m_pRunning;
}

/** Returns the Running node.
 */
const OpcUa::StateType* ProgramStateMachineTypeBase::getRunning() const
{
    return m_pRunning;
}

/** Returns the RunningToCompleted node.
 */
OpcUa::TransitionType* ProgramStateMachineTypeBase::getRunningToCompleted()
{
    return m_pRunningToCompleted;
}

/** Returns the RunningToCompleted node.
 */
const OpcUa::TransitionType* ProgramStateMachineTypeBase::getRunningToCompleted() const
{
    return m_pRunningToCompleted;
}

/** Returns the RunningToFailed node.
 */
OpcUa::TransitionType* ProgramStateMachineTypeBase::getRunningToFailed()
{
    return m_pRunningToFailed;
}

/** Returns the RunningToFailed node.
 */
const OpcUa::TransitionType* ProgramStateMachineTypeBase::getRunningToFailed() const
{
    return m_pRunningToFailed;
}

/** Returns the RunningToReady node.
 */
OpcUa::TransitionType* ProgramStateMachineTypeBase::getRunningToReady()
{
    return m_pRunningToReady;
}

/** Returns the RunningToReady node.
 */
const OpcUa::TransitionType* ProgramStateMachineTypeBase::getRunningToReady() const
{
    return m_pRunningToReady;
}


/** Uses the NodeAccessInfo of pOther and its children. */
void ProgramStateMachineTypeBase::useAccessInfoFromInstance(ProgramStateMachineTypeBase *pOther)
{
    OpcUa::FiniteStateMachineType::useAccessInfoFromInstance(pOther);

    // children
    m_pCompleted->useAccessInfoFromInstance(pOther->m_pCompleted);
    m_pCompletedToRunning->useAccessInfoFromInstance(pOther->m_pCompletedToRunning);
    m_pFailed->useAccessInfoFromInstance(pOther->m_pFailed);
    m_pFailedToRunning->useAccessInfoFromInstance(pOther->m_pFailedToRunning);
    m_pReady->useAccessInfoFromInstance(pOther->m_pReady);
    m_pReadyToRunning->useAccessInfoFromInstance(pOther->m_pReadyToRunning);
    m_pRunning->useAccessInfoFromInstance(pOther->m_pRunning);
    m_pRunningToCompleted->useAccessInfoFromInstance(pOther->m_pRunningToCompleted);
    m_pRunningToFailed->useAccessInfoFromInstance(pOther->m_pRunningToFailed);
    m_pRunningToReady->useAccessInfoFromInstance(pOther->m_pRunningToReady);
    m_pErrorCode->useAccessInfoFromInstance(pOther->m_pErrorCode);
    m_pErrorMessage->useAccessInfoFromInstance(pOther->m_pErrorMessage);
}

/** Set the NodeAccessInfo for this node and all of its children. */
void ProgramStateMachineTypeBase::setAccessInfoWithChildren(NodeAccessInfo* pNodeAccessInfo)
{
    OpcUa::FiniteStateMachineType::setAccessInfoWithChildren(pNodeAccessInfo);

    // children
    m_pCompleted->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pCompletedToRunning->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pFailed->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pFailedToRunning->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pReady->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pReadyToRunning->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pRunning->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pRunningToCompleted->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pRunningToFailed->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pRunningToReady->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pErrorCode->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pErrorMessage->setAccessInfoWithChildren(pNodeAccessInfo);
}


UaStatus ProgramStateMachineTypeBase::setProgramState(ProgramStateMachineTypeBase::ProgramState state)
{
    UaNodeId currentTransitionId;
    UaLocalizedText ltTransition;
    ProgramState currentState = getProgramState();
    switch (currentState)
    {
    case Completed:
        break;
    case Failed:
        break;
    case Ready:
        break;
    case Running:
        break;
    }
    return OpcUa_Bad;
}
ProgramStateMachineTypeBase::ProgramState ProgramStateMachineTypeBase::getProgramState()
{
    ProgramState ret = Completed;

    UaNodeId state(getCurrentStateNode()->getIdNodeId());
    OpcUa_UInt16 nsTypeIdx = MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace();

    if (state.identifierType() == OpcUa_IdentifierType_Numeric && state.namespaceIndex() == nsTypeIdx)
    {
        switch (state.identifierNumeric())
        {
        case MoxaClassBasedId_ProgramStateMachineType_Completed:
            ret = Completed;
            break;
        case MoxaClassBasedId_ProgramStateMachineType_Failed:
            ret = Failed;
            break;
        case MoxaClassBasedId_ProgramStateMachineType_Ready:
            ret = Ready;
            break;
        case MoxaClassBasedId_ProgramStateMachineType_Running:
            ret = Running;
            break;
        default:
            break;
        }
    }
    return ret;
}
} // End namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/


