/******************************************************************************
** opcuaclassbnm_iieeeautonegotiationstatustypebase.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://opcfoundation.org/UA/BNM/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#ifndef __OPCUACLASSBNM_IIEEEAUTONEGOTIATIONSTATUSTYPEBASE_H__
#define __OPCUACLASSBNM_IIEEEAUTONEGOTIATIONSTATUSTYPEBASE_H__

#include "opcua_baseinterfacetype.h"
#include "opcuaclassbnm_datatypes.h"
#include "basenodes.h"
#include "opcua_basedatavariabletype.h"
#include "opcuaclassbnm_identifiers.h"
#include "opcuaclassbnm_instancefactory_opcuaclassbnmns.h"

// Namespace for the UA information model http://opcfoundation.org/UA/BNM/
namespace OpcUaClassBnm {


/** Generated base class for a IIeeeAutoNegotiationStatusType.
 *
 *  This class contains the generated base code for the object type IIeeeAutoNegotiationStatusType
 *  representing an OPC UA ObjectType. This class is used to create the object type and to
 *  create and represent instances of the object type in the server address space.
 *
 *  **Variable members of the IIeeeAutoNegotiationStatusType:**
 *
 *  Browse Name       | DataType          | TypeDefinition       | Modelling Rule | See Also
 *  ------------------|-------------------|----------------------|----------------|-----------------------------------------------------
 *  NegotiationStatus | NegotiationStatus | BaseDataVariableType | Mandatory      | \ref getNegotiationStatus, \ref setNegotiationStatus
 *
 */
class OpcUaClassBnm_EXPORT IIeeeAutoNegotiationStatusTypeBase:
    public OpcUa::BaseInterfaceType
{
    UA_DISABLE_COPY(IIeeeAutoNegotiationStatusTypeBase);
protected:
    virtual ~IIeeeAutoNegotiationStatusTypeBase();
public:
    // construction / destruction
    IIeeeAutoNegotiationStatusTypeBase(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    IIeeeAutoNegotiationStatusTypeBase(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    IIeeeAutoNegotiationStatusTypeBase(
        UaBase::Object*    pBaseNode,
        XmlUaNodeFactoryManager*   pFactory,
        NodeManagerConfig* pNodeConfig,
        UaMutexRefCounted* pSharedMutex = NULL);
    static void createTypes();
    static void clearStaticMembers();

    virtual UaNodeId       typeDefinitionId() const;


    virtual void setNegotiationStatus(OpcUaClassBnm::NegotiationStatus NegotiationStatus);
    virtual OpcUaClassBnm::NegotiationStatus getNegotiationStatus() const;

    virtual OpcUa::BaseDataVariableType* getNegotiationStatusNode();
    virtual const OpcUa::BaseDataVariableType* getNegotiationStatusNode() const;

    // NodeAccessInfo management
    void useAccessInfoFromInstance(IIeeeAutoNegotiationStatusTypeBase *pInstance);
    virtual void setAccessInfoWithChildren(NodeAccessInfo* pNodeAccessInfo);

protected:
    // Variable nodes
    // Variable NegotiationStatus
    static OpcUa::BaseDataVariableType*  s_pNegotiationStatus;
    OpcUa::BaseDataVariableType*  m_pNegotiationStatus;



private:
    void initialize();

private:
    static bool s_typeNodesCreated;
};

} // End namespace for the UA information model http://opcfoundation.org/UA/BNM/

#endif // #ifndef __OPCUACLASSBNMIIEEEAUTONEGOTIATIONSTATUSTYPEBASE_H__


