/******************************************************************************
** opcuaclassbnm_iieeetsnmacaddresstypebase.cpp
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://opcfoundation.org/UA/BNM/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#include "opcuaclassbnm_iieeetsnmacaddresstypebase.h"
#include "opcuaclassbnm_iieeetsnmacaddresstype.h"
#include "uagenericnodes.h"
#include "nodemanagerroot.h"
#include "methodhandleuanode.h"
#include "opcuaclassbnm_nodemanageropcuaclassbnmns.h"

#include "instancefactory.h"
#include "opcua_extensionobject.h"
// Namespace for the UA information model http://opcfoundation.org/UA/BNM/
namespace OpcUaClassBnm {

bool IIeeeTsnMacAddressTypeBase::s_typeNodesCreated = false;
OpcUa::BaseDataVariableType* IIeeeTsnMacAddressTypeBase::s_pDestinationAddress = NULL;
OpcUa::BaseDataVariableType* IIeeeTsnMacAddressTypeBase::s_pSourceAddress = NULL;

/** Constructs an IIeeeTsnMacAddressType object using an instance declaration node as base
*/
IIeeeTsnMacAddressTypeBase::IIeeeTsnMacAddressTypeBase(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: OpcUa::BaseInterfaceType(nodeId, pInstanceDeclarationObject, pNodeConfig, pSharedMutex)
{
    initialize();
}

/** Constructs an IIeeeTsnMacAddressType object
*/
IIeeeTsnMacAddressTypeBase::IIeeeTsnMacAddressTypeBase(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: OpcUa::BaseInterfaceType(nodeId, name, browseNameNameSpaceIndex, pNodeConfig, pSharedMutex)
{
    initialize();
}

/**  Constructs an instance of the class IIeeeTsnMacAddressTypeBase with all components
*/
IIeeeTsnMacAddressTypeBase::IIeeeTsnMacAddressTypeBase(
    UaBase::Object*    pBaseNode,    //!< [in] The "tree" of nodes that specifies the attributes of the instance and its children
    XmlUaNodeFactoryManager* pFactory, //!< [in] The factory to create the children
    NodeManagerConfig* pNodeConfig,  //!< [in] Interface pointer to the NodeManagerConfig interface used to add and delete node and references in the address space
    UaMutexRefCounted* pSharedMutex) //!< [in] Shared mutex object used to synchronize access to the variable. Can be NULL if no shared mutex is provided
: OpcUa::BaseInterfaceType(pBaseNode, pFactory, pNodeConfig, pSharedMutex)
{
    UaStatus      addStatus;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }

    m_pDestinationAddress = NULL;
    m_pSourceAddress = NULL;

    std::list<UaBase::BaseNode*> lstReferencedNodes = pBaseNode->hierarchicallyReferencedNodes();
    for (std::list<UaBase::BaseNode*>::const_iterator it = lstReferencedNodes.begin(); it != lstReferencedNodes.end(); it++)
    {
        UaBase::BaseNode *pChild = *it;
        if (pChild->browseName() == UaQualifiedName("DestinationAddress", OpcUaClassBnm::NodeManagerOpcUaClassBnmNS::getTypeNamespace()))
        {
            if (!m_pDestinationAddress)
            {
                m_pDestinationAddress = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pDestinationAddress, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pDestinationAddress->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("SourceAddress", OpcUaClassBnm::NodeManagerOpcUaClassBnmNS::getTypeNamespace()))
        {
            if (!m_pSourceAddress)
            {
                m_pSourceAddress = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pSourceAddress, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pSourceAddress->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
    }
    UA_ASSERT(m_pDestinationAddress);
}

/** Initialize the object with all member nodes
*/
void IIeeeTsnMacAddressTypeBase::initialize()
{
    UaStatus      addStatus;
    UaVariant     defaultValue;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }
    m_pDestinationAddress = NULL;
    m_pSourceAddress = NULL;
    // Mandatory variable DestinationAddress
    m_pDestinationAddress = new OpcUa::BaseDataVariableType(this, s_pDestinationAddress, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pDestinationAddress, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());


}

/** Destruction
*/
IIeeeTsnMacAddressTypeBase::~IIeeeTsnMacAddressTypeBase()
{
}

/** Create the related type nodes
*/
void IIeeeTsnMacAddressTypeBase::createTypes()
{
    if ( s_typeNodesCreated == false )
    {
        s_typeNodesCreated = true;

        // Check if supertype is already created
        OpcUa::BaseInterfaceType::createTypes();

        UaStatus      addStatus;
        UaVariant     defaultValue;
        NodeManagerRoot* pNodeManagerRoot = NodeManagerRoot::CreateRootNodeManager();
        OpcUa_Int16 nsTypeIdx = NodeManagerOpcUaClassBnmNS::getTypeNamespace();
        OpcUa_Int16 nsSuperTypeIdx = NodeManagerRoot::getTypeNamespace();
        NodeManagerConfig* pTypeNodeConfig = pNodeManagerRoot->getNodeManagerByNamespace(nsTypeIdx)->getNodeManagerConfig();

        OpcUa::GenericObjectType* pObjectType;
        pObjectType = new OpcUa::GenericObjectType(
            UaNodeId(OpcUaClassBnmId_IIeeeTsnMacAddressType, nsTypeIdx),
            UaQualifiedName("IIeeeTsnMacAddressType", nsTypeIdx),
            UaLocalizedText("", "IIeeeTsnMacAddressType"),
            UaLocalizedText("", ""),
            OpcUa_True,
            &IIeeeTsnMacAddressType::clearStaticMembers);
        addStatus = pTypeNodeConfig->addNodeAndReference(UaNodeId(OpcUaId_BaseInterfaceType, nsSuperTypeIdx), pObjectType, OpcUaId_HasSubtype);
        UA_ASSERT(addStatus.isGood());

        // Mandatory variable DestinationAddress
        UaByteArray valDestinationAddress;
        defaultValue.setByteArray(valDestinationAddress);
        s_pDestinationAddress = new OpcUa::BaseDataVariableType(UaNodeId(OpcUaClassBnmId_IIeeeTsnMacAddressType_DestinationAddress, nsTypeIdx), "DestinationAddress", OpcUaClassBnm::NodeManagerOpcUaClassBnmNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pDestinationAddress->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pDestinationAddress->setValueRank(1);
        UaUInt32Array arrayDimensions;
        arrayDimensions.create(1);
        arrayDimensions[0] = 6;
        s_pDestinationAddress->setArrayDimensions(arrayDimensions);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pDestinationAddress, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

        // Optional variable SourceAddress
        UaByteArray valSourceAddress;
        defaultValue.setByteArray(valSourceAddress);
        s_pSourceAddress = new OpcUa::BaseDataVariableType(UaNodeId(OpcUaClassBnmId_IIeeeTsnMacAddressType_SourceAddress, nsTypeIdx), "SourceAddress", OpcUaClassBnm::NodeManagerOpcUaClassBnmNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pSourceAddress->setModellingRuleId(OpcUaId_ModellingRule_Optional);
        s_pSourceAddress->setValueRank(1);
        arrayDimensions.create(1);
        arrayDimensions[0] = 6;
        s_pSourceAddress->setArrayDimensions(arrayDimensions);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pSourceAddress, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

    }
}

/** Clear the static members of the class
*/
void IIeeeTsnMacAddressTypeBase::clearStaticMembers()
{
    s_typeNodesCreated = false;

    s_pDestinationAddress = NULL;
    s_pSourceAddress = NULL;
}

/** Returns the type definition NodeId for the IIeeeTsnMacAddressType
*/
UaNodeId IIeeeTsnMacAddressTypeBase::typeDefinitionId() const
{
    UaNodeId ret(OpcUaClassBnmId_IIeeeTsnMacAddressType, NodeManagerOpcUaClassBnmNS::getTypeNamespace());
    return ret;
}

/**
 *  Sets the DestinationAddress
 */
void IIeeeTsnMacAddressTypeBase::setDestinationAddress(const UaByteArray& DestinationAddress)
{
    UaDataValue dataValue;
    UaByteArray c = DestinationAddress;
    UaVariant v;
    v.setByteArray(c);
    dataValue.setValue(v, OpcUa_True, OpcUa_True);
    m_pDestinationAddress->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Gets the DestinationAddress
 */
void IIeeeTsnMacAddressTypeBase::getDestinationAddress(UaByteArray& DestinationAddress) const
{
    if ( m_pDestinationAddress != NULL )
    {
        UaDataValue dataValue(m_pDestinationAddress->value(NULL));
        UaVariant value;
        value.attach(dataValue.value());
        value.toByteArray(DestinationAddress);
        value.detach();
    }
}

/**
 *  Sets the SourceAddress
 */
void IIeeeTsnMacAddressTypeBase::setSourceAddress(const UaByteArray& SourceAddress)
{
    if ( m_pSourceAddress == NULL )
    {
        UaStatus addStatus;
        m_pSourceAddress = new OpcUa::BaseDataVariableType(this, s_pSourceAddress, m_pNodeConfig, m_pSharedMutex);
        addStatus = m_pNodeConfig->addNodeAndReference(this, m_pSourceAddress, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());
    }

    UaDataValue dataValue;
    UaByteArray c = SourceAddress;
    UaVariant v;
    v.setByteArray(c);
    dataValue.setValue(v, OpcUa_True, OpcUa_True);
    m_pSourceAddress->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Gets the SourceAddress
 */
void IIeeeTsnMacAddressTypeBase::getSourceAddress(UaByteArray& SourceAddress) const
{
    if ( m_pSourceAddress != NULL )
    {
        UaDataValue dataValue(m_pSourceAddress->value(NULL));
        UaVariant value;
        value.attach(dataValue.value());
        value.toByteArray(SourceAddress);
        value.detach();
    }
}

/** Returns the DestinationAddress node.
 */
OpcUa::BaseDataVariableType* IIeeeTsnMacAddressTypeBase::getDestinationAddressNode()
{
    return m_pDestinationAddress;
}

/** Returns the DestinationAddress node.
 */
const OpcUa::BaseDataVariableType* IIeeeTsnMacAddressTypeBase::getDestinationAddressNode() const
{
    return m_pDestinationAddress;
}

/** Returns the SourceAddress node.
 *
 * If the Variable has not been created yet, this method returns NULL.
 */
OpcUa::BaseDataVariableType* IIeeeTsnMacAddressTypeBase::getSourceAddressNode()
{
    return m_pSourceAddress;
}

/** Returns the SourceAddress node.
 *
 * If the Variable has not been created yet, this method returns NULL.
 */
const OpcUa::BaseDataVariableType* IIeeeTsnMacAddressTypeBase::getSourceAddressNode() const
{
    return m_pSourceAddress;
}


/** Uses the NodeAccessInfo of pOther and its children. */
void IIeeeTsnMacAddressTypeBase::useAccessInfoFromInstance(IIeeeTsnMacAddressTypeBase *pOther)
{
    OpcUa::BaseInterfaceType::useAccessInfoFromInstance(pOther);

    // children
    m_pDestinationAddress->useAccessInfoFromInstance(pOther->m_pDestinationAddress);
    if (m_pSourceAddress && pOther->m_pSourceAddress)
    {
        m_pSourceAddress->useAccessInfoFromInstance(pOther->m_pSourceAddress);
    }
}

/** Set the NodeAccessInfo for this node and all of its children. */
void IIeeeTsnMacAddressTypeBase::setAccessInfoWithChildren(NodeAccessInfo* pNodeAccessInfo)
{
    OpcUa::BaseInterfaceType::setAccessInfoWithChildren(pNodeAccessInfo);

    // children
    m_pDestinationAddress->setAccessInfoWithChildren(pNodeAccessInfo);
    if (m_pSourceAddress)
    {
        m_pSourceAddress->setAccessInfoWithChildren(pNodeAccessInfo);
    }
}


} // End namespace for the UA information model http://opcfoundation.org/UA/BNM/


