/******************************************************************************
** moxaclassbased_projecttypebase.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#ifndef __MOXACLASSBASED_PROJECTTYPEBASE_H__
#define __MOXACLASSBASED_PROJECTTYPEBASE_H__

#include "opcua_baseobjecttype.h"
#include "moxaclassbased_datatypes.h"
#include "basenodes.h"
#include "moxaclassbased_identifiers.h"
#include "moxaclassbased_instancefactory_moxaclassbasedns.h"
#include "moxaclassbased_trafficconfigurationentrydatatype.h"
#include "opcua_basedatavariabletype.h"
#include "opcua_finitestatevariabletype.h"
#include "opcua_foldertype.h"
#include "opcua_statetype.h"
#include "opcua_transitiontype.h"
#include "uaargument.h"

// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

class BroadcastSearchAndIPSettingStateMachineType;
class ComputeStateMachineType;
class ConnectionAccountType;
class DeployStateMachineType;
class DeviceFolderType;
class ExportSyslogStateMachineType;
class ExportTrapEventStateMachineType;
class IpSettingType;
class LinkFolderType;
class NETCONFType;
class ProjectSettingType;
class RESTfulType;
class SNMPType;
class ScanTopologyStateMachineType;
class TrafficConfigurationTableType;
class TrafficDesignFolderType;
class TsnStreamApplicationFolderType;
class TsnStreamFolderType;

/** Generated base class for a ProjectType.
 *
 *  This class contains the generated base code for the object type ProjectType
 *  representing an OPC UA ObjectType. This class is used to create the object type and to
 *  create and represent instances of the object type in the server address space.
 *
 *  **Object members of the ProjectType:**
 *
 *  Browse Name                 | TypeDefinition                              | Modelling Rule | See Also
 *  ----------------------------|---------------------------------------------|----------------|------------------------------------
 *  AutoScanTopology            | ScanTopologyStateMachineType                | Mandatory      | \ref getAutoScanTopology
 *  BroadcastSearchAndIPSetting | BroadcastSearchAndIPSettingStateMachineType | Mandatory      | \ref getBroadcastSearchAndIPSetting
 *  Compute                     | ComputeStateMachineType                     | Mandatory      | \ref getCompute
 *  Deploy                      | DeployStateMachineType                      | Mandatory      | \ref getDeploy
 *  Devices                     | DeviceFolderType                            | Mandatory      | \ref getDevices
 *  ExportSyslog                | ExportSyslogStateMachineType                | Mandatory      | \ref getExportSyslog
 *  ExportTrapEvent             | ExportTrapEventStateMachineType             | Mandatory      | \ref getExportTrapEvent
 *  Links                       | LinkFolderType                              | Mandatory      | \ref getLinks
 *  ProjectSetting              | ProjectSettingType                          | Mandatory      | \ref getProjectSetting
 *  TrafficDesign               | TrafficDesignFolderType                     | Mandatory      | \ref getTrafficDesign
 *
 */
class MoxaClassBased_EXPORT ProjectTypeBase:
    public OpcUa::BaseObjectType
{
    UA_DISABLE_COPY(ProjectTypeBase);
protected:
    virtual ~ProjectTypeBase();
public:
    // construction / destruction
    ProjectTypeBase(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    ProjectTypeBase(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    ProjectTypeBase(
        UaBase::Object*    pBaseNode,
        XmlUaNodeFactoryManager*   pFactory,
        NodeManagerConfig* pNodeConfig,
        UaMutexRefCounted* pSharedMutex = NULL);
    static void createTypes();
    static void clearStaticMembers();

    virtual UaNodeId       typeDefinitionId() const;


    virtual MoxaClassBased::ScanTopologyStateMachineType* getAutoScanTopology();
    virtual const MoxaClassBased::ScanTopologyStateMachineType* getAutoScanTopology() const;
    virtual MoxaClassBased::BroadcastSearchAndIPSettingStateMachineType* getBroadcastSearchAndIPSetting();
    virtual const MoxaClassBased::BroadcastSearchAndIPSettingStateMachineType* getBroadcastSearchAndIPSetting() const;
    virtual MoxaClassBased::ComputeStateMachineType* getCompute();
    virtual const MoxaClassBased::ComputeStateMachineType* getCompute() const;
    virtual MoxaClassBased::DeployStateMachineType* getDeploy();
    virtual const MoxaClassBased::DeployStateMachineType* getDeploy() const;
    virtual MoxaClassBased::DeviceFolderType* getDevices();
    virtual const MoxaClassBased::DeviceFolderType* getDevices() const;
    virtual MoxaClassBased::ExportSyslogStateMachineType* getExportSyslog();
    virtual const MoxaClassBased::ExportSyslogStateMachineType* getExportSyslog() const;
    virtual MoxaClassBased::ExportTrapEventStateMachineType* getExportTrapEvent();
    virtual const MoxaClassBased::ExportTrapEventStateMachineType* getExportTrapEvent() const;
    virtual MoxaClassBased::LinkFolderType* getLinks();
    virtual const MoxaClassBased::LinkFolderType* getLinks() const;
    virtual MoxaClassBased::ProjectSettingType* getProjectSetting();
    virtual const MoxaClassBased::ProjectSettingType* getProjectSetting() const;
    virtual MoxaClassBased::TrafficDesignFolderType* getTrafficDesign();
    virtual const MoxaClassBased::TrafficDesignFolderType* getTrafficDesign() const;

    // NodeAccessInfo management
    void useAccessInfoFromInstance(ProjectTypeBase *pInstance);
    virtual void setAccessInfoWithChildren(NodeAccessInfo* pNodeAccessInfo);

protected:
    // Object nodes
    // Object AutoScanTopology
    static MoxaClassBased::ScanTopologyStateMachineType*  s_pAutoScanTopology;
    MoxaClassBased::ScanTopologyStateMachineType*  m_pAutoScanTopology;
    // Object BroadcastSearchAndIPSetting
    static MoxaClassBased::BroadcastSearchAndIPSettingStateMachineType*  s_pBroadcastSearchAndIPSetting;
    MoxaClassBased::BroadcastSearchAndIPSettingStateMachineType*  m_pBroadcastSearchAndIPSetting;
    // Object Compute
    static MoxaClassBased::ComputeStateMachineType*  s_pCompute;
    MoxaClassBased::ComputeStateMachineType*  m_pCompute;
    // Object Deploy
    static MoxaClassBased::DeployStateMachineType*  s_pDeploy;
    MoxaClassBased::DeployStateMachineType*  m_pDeploy;
    // Object Devices
    static MoxaClassBased::DeviceFolderType*  s_pDevices;
    MoxaClassBased::DeviceFolderType*  m_pDevices;
    // Object ExportSyslog
    static MoxaClassBased::ExportSyslogStateMachineType*  s_pExportSyslog;
    MoxaClassBased::ExportSyslogStateMachineType*  m_pExportSyslog;
    // Object ExportTrapEvent
    static MoxaClassBased::ExportTrapEventStateMachineType*  s_pExportTrapEvent;
    MoxaClassBased::ExportTrapEventStateMachineType*  m_pExportTrapEvent;
    // Object Links
    static MoxaClassBased::LinkFolderType*  s_pLinks;
    MoxaClassBased::LinkFolderType*  m_pLinks;
    // Object ProjectSetting
    static MoxaClassBased::ProjectSettingType*  s_pProjectSetting;
    MoxaClassBased::ProjectSettingType*  m_pProjectSetting;
    // Object TrafficDesign
    static MoxaClassBased::TrafficDesignFolderType*  s_pTrafficDesign;
    MoxaClassBased::TrafficDesignFolderType*  m_pTrafficDesign;



private:
    void initialize();

private:
    static bool s_typeNodesCreated;
};

} // End namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/

#endif // #ifndef __MOXACLASSBASEDPROJECTTYPEBASE_H__


