/******************************************************************************
** moxaclassbased_tsninterfaceconfigurationlistenerdatatype.cpp
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#include "moxaclassbased_tsninterfaceconfigurationlistenerdatatype.h"

#include <opcua_datetime.h>

#include "uavariant.h"
#include "uadatavalue.h"
#include "uaextensionobject.h"
#include "uaatomic.h"

// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

/******************************************************************************
** Class TsnInterfaceConfigurationListenerDataTypePrivate
******************************************************************************/
class TsnInterfaceConfigurationListenerDataTypePrivate : private MoxaClassBased_TsnInterfaceConfigurationListenerDataType
{
    TsnInterfaceConfigurationListenerDataTypePrivate(const TsnInterfaceConfigurationListenerDataTypePrivate &other);
    TsnInterfaceConfigurationListenerDataTypePrivate& operator=(const TsnInterfaceConfigurationListenerDataTypePrivate&);
public:
    TsnInterfaceConfigurationListenerDataTypePrivate();
    explicit TsnInterfaceConfigurationListenerDataTypePrivate(bool bStatic);
    explicit TsnInterfaceConfigurationListenerDataTypePrivate(const MoxaClassBased_TsnInterfaceConfigurationListenerDataType &other);
    ~TsnInterfaceConfigurationListenerDataTypePrivate();

    int addRef();
    int release();
    inline int refCount() { return m_iRefCnt; }

private:
    int m_iRefCnt;
    friend class TsnInterfaceConfigurationListenerDataType;
};

/* construction */
TsnInterfaceConfigurationListenerDataTypePrivate::TsnInterfaceConfigurationListenerDataTypePrivate()
 : m_iRefCnt(0)
{
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Initialize(this);
}

/*  Static initializer.
 *  This is used internaly to initialize the static shared_emtpy variable.
 *  RefCnt is set to 1 so it will never be deleted.
 */
TsnInterfaceConfigurationListenerDataTypePrivate::TsnInterfaceConfigurationListenerDataTypePrivate(bool)
 : m_iRefCnt(1)
{
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Initialize(this);
}


/*  construction
 */
TsnInterfaceConfigurationListenerDataTypePrivate::TsnInterfaceConfigurationListenerDataTypePrivate(const MoxaClassBased_TsnInterfaceConfigurationListenerDataType &other) // [in] the other MoxaClassBased_TsnInterfaceConfigurationListenerDataType.
 : m_iRefCnt(0)
{
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(&other, this);
}

/* destruction */
TsnInterfaceConfigurationListenerDataTypePrivate::~TsnInterfaceConfigurationListenerDataTypePrivate()
{
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Clear(this);
}

/*  Add a reference to a TsnInterfaceConfigurationListenerDataTypePrivate
 *  @return 0 if the object was deleted - otherwise a value bigger than 0.
 *  This method is not thread save regarding the return value. The returned counter is only reliable when it is 0.
 *  Other values are not reliable and should not be used for any logic.
 */
int TsnInterfaceConfigurationListenerDataTypePrivate::addRef()
{
    return ua_atomic_increment(&m_iRefCnt);
}

/*  Release a TsnInterfaceConfigurationListenerDataTypePrivate.
 *  @return the reference count.
 */
int TsnInterfaceConfigurationListenerDataTypePrivate::release()
{
    int currentCount = ua_atomic_decrement(&m_iRefCnt);
    if (currentCount == 0)
    {
        delete this;
    }
    return currentCount;
}

TsnInterfaceConfigurationListenerDataTypePrivate* shared_empty_TsnInterfaceConfigurationListenerDataType()
{
    static TsnInterfaceConfigurationListenerDataTypePrivate shared_static(true);
    return &shared_static;
}


/******************************************************************************
** Class TsnInterfaceConfigurationListenerDataType
******************************************************************************/

/** Constructs an instance of the class TsnInterfaceConfigurationListenerDataType with empty default values
*/
TsnInterfaceConfigurationListenerDataType::TsnInterfaceConfigurationListenerDataType()
{
    d_ptr = shared_empty_TsnInterfaceConfigurationListenerDataType();
    d_ptr->addRef();
}

/** Constructs an instance of the class TsnInterfaceConfigurationListenerDataType with values from another TsnInterfaceConfigurationListenerDataType object
 *  @param other the other UaTsnInterfaceConfigurationListenerDataType used to initialize the object
 */
TsnInterfaceConfigurationListenerDataType::TsnInterfaceConfigurationListenerDataType(const TsnInterfaceConfigurationListenerDataType &other)
{
    d_ptr = other.d_ptr;
    d_ptr->addRef();
}

/** Constructs an instance of the class TsnInterfaceConfigurationListenerDataType with values from another MoxaClassBased_TsnInterfaceConfigurationListenerDataType structure
 *  @param other the other MoxaClassBased_TsnInterfaceConfigurationListenerDataType used to initialize the object
 */
TsnInterfaceConfigurationListenerDataType::TsnInterfaceConfigurationListenerDataType(const MoxaClassBased_TsnInterfaceConfigurationListenerDataType &other)
{
    d_ptr = new TsnInterfaceConfigurationListenerDataTypePrivate(other);
    d_ptr->addRef();
}

/** Constructs an instance of the class TsnInterfaceConfigurationListenerDataType with values provided in the constructor
 */
TsnInterfaceConfigurationListenerDataType::TsnInterfaceConfigurationListenerDataType(
        const UaString& IpAddress,
        const UaString& InterfaceName
        )
{
    d_ptr = new TsnInterfaceConfigurationListenerDataTypePrivate();
    d_ptr->addRef();
    setIpAddress(IpAddress);
    setInterfaceName(InterfaceName);
}

/** Constructs an instance of the class TsnInterfaceConfigurationListenerDataType initialized with value from a UaExtensionObject
 *  @param extensionObject the extension object containing the TsnInterfaceConfigurationListenerDataType
 */
TsnInterfaceConfigurationListenerDataType::TsnInterfaceConfigurationListenerDataType(const UaExtensionObject &extensionObject)
{
    d_ptr = new TsnInterfaceConfigurationListenerDataTypePrivate();
    d_ptr->addRef();

    const OpcUa_ExtensionObject *pExtensionObject = (const OpcUa_ExtensionObject*)extensionObject;
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pTsnInterfaceConfigurationListenerDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(TsnInterfaceConfigurationListenerDataType, pExtensionObject);

    if (pTsnInterfaceConfigurationListenerDataType)
    {
        MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(pTsnInterfaceConfigurationListenerDataType, d_ptr);
    }
}

/** Constructs an instance of the class TsnInterfaceConfigurationListenerDataType initialized with value from an OpcUa_ExtensionObject structure
 *  @param extensionObject the extension object containing the TsnInterfaceConfigurationListenerDataType
 */
TsnInterfaceConfigurationListenerDataType::TsnInterfaceConfigurationListenerDataType(const OpcUa_ExtensionObject &extensionObject)
{
    d_ptr = new TsnInterfaceConfigurationListenerDataTypePrivate();
    d_ptr->addRef();

    MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pTsnInterfaceConfigurationListenerDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(TsnInterfaceConfigurationListenerDataType, &extensionObject);

    if (pTsnInterfaceConfigurationListenerDataType)
    {
        MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(pTsnInterfaceConfigurationListenerDataType, d_ptr);
    }
}

TsnInterfaceConfigurationListenerDataType::TsnInterfaceConfigurationListenerDataType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    d_ptr = new TsnInterfaceConfigurationListenerDataTypePrivate();
    d_ptr->addRef();

    const OpcUa_ExtensionObject *pExtensionObject = (const OpcUa_ExtensionObject*)extensionObject;
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pTsnInterfaceConfigurationListenerDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(TsnInterfaceConfigurationListenerDataType, pExtensionObject);
    if (pTsnInterfaceConfigurationListenerDataType)
    {
        if (bDetach == OpcUa_False)
        {
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(pTsnInterfaceConfigurationListenerDataType, d_ptr);
        }
        else
        {
            (*(MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)d_ptr) = *pTsnInterfaceConfigurationListenerDataType;
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Initialize(pTsnInterfaceConfigurationListenerDataType);
            extensionObject.clear();
        }
    }
}

TsnInterfaceConfigurationListenerDataType::TsnInterfaceConfigurationListenerDataType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    d_ptr = new TsnInterfaceConfigurationListenerDataTypePrivate();
    d_ptr->addRef();

    MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pTsnInterfaceConfigurationListenerDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(TsnInterfaceConfigurationListenerDataType, &extensionObject);

    if (pTsnInterfaceConfigurationListenerDataType)
    {
        if (bDetach == OpcUa_False)
        {
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(pTsnInterfaceConfigurationListenerDataType, d_ptr);
        }
        else
        {
            (*(MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)d_ptr) = *pTsnInterfaceConfigurationListenerDataType;
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Initialize(pTsnInterfaceConfigurationListenerDataType);
            OpcUa_ExtensionObject_Clear(&extensionObject);
        }
    }
}

/** Destroys the TsnInterfaceConfigurationListenerDataType object
*/
TsnInterfaceConfigurationListenerDataType::~TsnInterfaceConfigurationListenerDataType()
{
    MOXACLASSBASED_D(TsnInterfaceConfigurationListenerDataType);
    d->release();
}

/** Clear the data of the TsnInterfaceConfigurationListenerDataType.
*/
void TsnInterfaceConfigurationListenerDataType::clear()
{
    d_ptr->release();
    d_ptr = shared_empty_TsnInterfaceConfigurationListenerDataType();
    d_ptr->addRef();
}

/** Compare two TsnInterfaceConfigurationListenerDataType if they are similar.
 *  @param other the TsnInterfaceConfigurationListenerDataType to compare.
 *  @return true if similar, false if not.
 */
bool TsnInterfaceConfigurationListenerDataType::operator==(const TsnInterfaceConfigurationListenerDataType &other) const
{
    return (MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Compare(d_ptr, other.d_ptr) == 0);
}

/** Returns true if the other TsnInterfaceConfigurationListenerDataType is not equal to this.
 *  @see operator==
 *  @param other the TsnInterfaceConfigurationListenerDataType to compare.
 *  @return true if other is not equal to this.
 */
bool TsnInterfaceConfigurationListenerDataType::operator!=(const TsnInterfaceConfigurationListenerDataType &other) const
{
    return !(operator==(other));
}

/** Assignment operator.
 *  @param other the TsnInterfaceConfigurationListenerDataType to assign.
 *  @return Assignment operator.
 */
TsnInterfaceConfigurationListenerDataType& TsnInterfaceConfigurationListenerDataType::operator=(const TsnInterfaceConfigurationListenerDataType &other)
{
    other.d_ptr->addRef();
    d_ptr->release();
    d_ptr = other.d_ptr;
    return *this;
}

/** Copy TsnInterfaceConfigurationListenerDataType data to a newly allocated MoxaClassBased_TsnInterfaceConfigurationListenerDataType.
 *  @return data to a newly allocated MoxaClassBased_TsnInterfaceConfigurationListenerDataType.
 */
MoxaClassBased_TsnInterfaceConfigurationListenerDataType* TsnInterfaceConfigurationListenerDataType::copy() const
{
    return clone(*d_ptr);
}

/** Copy TsnInterfaceConfigurationListenerDataType data to an existing MoxaClassBased_TsnInterfaceConfigurationListenerDataType structure.
 *  @param pDst the destination of this copy operation.
 */
void TsnInterfaceConfigurationListenerDataType::copyTo(MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pDst) const
{
    if (pDst == OpcUa_Null) return;
    cloneTo(*d_ptr, *pDst);
}

/** Copy MoxaClassBased_TsnInterfaceConfigurationListenerDataType data to a newly allocated MoxaClassBased_TsnInterfaceConfigurationListenerDataType.
 *  @param source Source to clone.
 *  @return new copy.
 */
MoxaClassBased_TsnInterfaceConfigurationListenerDataType* TsnInterfaceConfigurationListenerDataType::clone(const MoxaClassBased_TsnInterfaceConfigurationListenerDataType& source)
{
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType* pTsnInterfaceConfigurationListenerDataType = OpcUa_Null;
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Copy(&source, &pTsnInterfaceConfigurationListenerDataType);
    return pTsnInterfaceConfigurationListenerDataType;
}

/** Copy MoxaClassBased_TsnInterfaceConfigurationListenerDataType data to an existing MoxaClassBased_TsnInterfaceConfigurationListenerDataType structure.
 *  @param source the source of the clone operation.
 *  @param copy the destination of the clone operation.
 */
void TsnInterfaceConfigurationListenerDataType::cloneTo(const MoxaClassBased_TsnInterfaceConfigurationListenerDataType& source, MoxaClassBased_TsnInterfaceConfigurationListenerDataType& copy)
{
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(&source, &copy);
}

/** Attaches the data of the parameter pValue.
 * Don't clear the data of pValue afterwards manually, because TsnInterfaceConfigurationListenerDataType is responsible for it now.
 */
void TsnInterfaceConfigurationListenerDataType::attach(const MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pValue) //!< [in] Parameter to attach to.
{
    if (pValue == OpcUa_Null) return;
    if (d_ptr->refCount() == 1)
    {
        MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Clear(d_ptr);
    }
    else
    {
        d_ptr->release();
        d_ptr = new TsnInterfaceConfigurationListenerDataTypePrivate();
        d_ptr->addRef();
    }
    // copy data value structure (no deep copy)
    OpcUa_MemCpy(d_ptr, sizeof(MoxaClassBased_TsnInterfaceConfigurationListenerDataType), (void*)pValue, sizeof(MoxaClassBased_TsnInterfaceConfigurationListenerDataType));
}

/** Detaches the internal TsnInterfaceConfigurationListenerDataType structure from this class.
 *  This way you take over the control of releasing the TsnInterfaceConfigurationListenerDataType data.
 *  If more than one references exist, the data is copied to pDst instead of being detached.
 *  @return If the functions succeeds pDst is returned, otherwise 0 is returned.
 */
MoxaClassBased_TsnInterfaceConfigurationListenerDataType* TsnInterfaceConfigurationListenerDataType::detach(MoxaClassBased_TsnInterfaceConfigurationListenerDataType* pDst) //!< [out] Pointer to MoxaClassBased_TsnInterfaceConfigurationListenerDataType structure that receives the TsnInterfaceConfigurationListenerDataType data.
{
    if (pDst == OpcUa_Null) return OpcUa_Null;
    if (d_ptr->refCount() == 1)
    {
        OpcUa_MemCpy(pDst, sizeof(MoxaClassBased_TsnInterfaceConfigurationListenerDataType), d_ptr, sizeof(MoxaClassBased_TsnInterfaceConfigurationListenerDataType));
        // clear internal data without releasing deeper memory
        MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Initialize(d_ptr);
    }
    else
    {
        MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(d_ptr, pDst);
    }
    d_ptr->release();
    d_ptr = shared_empty_TsnInterfaceConfigurationListenerDataType();
    d_ptr->addRef();
    return pDst;
}

void TsnInterfaceConfigurationListenerDataType::toVariant(UaVariant &variant) const
{
    UaExtensionObject extensionObject;
    toExtensionObject(extensionObject);
    variant.setExtensionObject(extensionObject, OpcUa_True);
}

void TsnInterfaceConfigurationListenerDataType::toVariant(OpcUa_Variant &variant) const
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Scalar;
    variant.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(variant.Value.ExtensionObject);
    toExtensionObject(*variant.Value.ExtensionObject);
}

void TsnInterfaceConfigurationListenerDataType::toVariant(UaVariant &variant, OpcUa_Boolean bDetach)
{
    UaExtensionObject extensionObject;
    toExtensionObject(extensionObject, bDetach);
    variant.setExtensionObject(extensionObject, OpcUa_True);
}

void TsnInterfaceConfigurationListenerDataType::toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Scalar;
    variant.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(variant.Value.ExtensionObject);
    toExtensionObject(*variant.Value.ExtensionObject, bDetach);
}

void TsnInterfaceConfigurationListenerDataType::toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    UaVariant variant;
    toVariant(variant);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void TsnInterfaceConfigurationListenerDataType::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    OpcUa_Variant_Clear(&dataValue.Value);
    dataValue.Value.Datatype = OpcUaType_ExtensionObject;
    dataValue.Value.ArrayType = OpcUa_VariantArrayType_Scalar;
    dataValue.Value.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(dataValue.Value.Value.ExtensionObject);
    toExtensionObject(*dataValue.Value.Value.ExtensionObject);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

void TsnInterfaceConfigurationListenerDataType::toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    UaVariant variant;
    toVariant(variant, bDetach);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void TsnInterfaceConfigurationListenerDataType::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    OpcUa_Variant_Clear(&dataValue.Value);
    dataValue.Value.Datatype = OpcUaType_ExtensionObject;
    dataValue.Value.ArrayType = OpcUa_VariantArrayType_Scalar;
    dataValue.Value.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(dataValue.Value.Value.ExtensionObject);
    toExtensionObject(*dataValue.Value.Value.ExtensionObject, bDetach);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

void TsnInterfaceConfigurationListenerDataType::toExtensionObject(UaExtensionObject &extensionObject) const
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    toExtensionObject(*pExtensionObject);
}

void TsnInterfaceConfigurationListenerDataType::toExtensionObject(OpcUa_ExtensionObject &extensionObject) const
{
    OpcUa_ExtensionObject_Clear(&extensionObject);
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pTsnInterfaceConfigurationListenerDataType = OpcUa_Null;
    if (OpcUa_IsGood(OpcUa_EncodeableObject_CreateExtension(&MoxaClassBased_TsnInterfaceConfigurationListenerDataType_EncodeableType,
                                                            &extensionObject,
                                                            (OpcUa_Void**)&pTsnInterfaceConfigurationListenerDataType)))
    {
        MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(d_ptr, pTsnInterfaceConfigurationListenerDataType);
    }
}

void TsnInterfaceConfigurationListenerDataType::toExtensionObject(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    toExtensionObject(*pExtensionObject, bDetach);
}

void TsnInterfaceConfigurationListenerDataType::toExtensionObject(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject_Clear(&extensionObject);
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pTsnInterfaceConfigurationListenerDataType = OpcUa_Null;
    if (OpcUa_IsGood(OpcUa_EncodeableObject_CreateExtension(&MoxaClassBased_TsnInterfaceConfigurationListenerDataType_EncodeableType,
                                                            &extensionObject,
                                                            (OpcUa_Void**)&pTsnInterfaceConfigurationListenerDataType)))
    {
        MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Initialize(pTsnInterfaceConfigurationListenerDataType);
        if (bDetach != OpcUa_False && d_ptr->refCount() == 1)
        {
            *pTsnInterfaceConfigurationListenerDataType = *d_ptr;
            // clear internal data without releasing deeper memory
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Initialize(d_ptr);
        }
        else
        {
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(d_ptr, pTsnInterfaceConfigurationListenerDataType);
        }
        if (bDetach != OpcUa_False)
        {
            d_ptr->release();
            d_ptr = shared_empty_TsnInterfaceConfigurationListenerDataType();
            d_ptr->addRef();
        }
    }
}

OpcUa_StatusCode TsnInterfaceConfigurationListenerDataType::setTsnInterfaceConfigurationListenerDataType(const UaExtensionObject &extensionObject)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    return setTsnInterfaceConfigurationListenerDataType(*pExtensionObject);
}

OpcUa_StatusCode TsnInterfaceConfigurationListenerDataType::setTsnInterfaceConfigurationListenerDataType(const OpcUa_ExtensionObject &extensionObject)
{
    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pTsnInterfaceConfigurationListenerDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(TsnInterfaceConfigurationListenerDataType, &extensionObject);

    if (pTsnInterfaceConfigurationListenerDataType)
    {
        ret = OpcUa_Good;

        if (d_ptr->refCount() == 1)
        {
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Clear(d_ptr);
        }
        else
        {
            d_ptr->release();
            d_ptr = new TsnInterfaceConfigurationListenerDataTypePrivate();
            d_ptr->addRef();
        }

        MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(pTsnInterfaceConfigurationListenerDataType, d_ptr);
    }
    return ret;
}

OpcUa_StatusCode TsnInterfaceConfigurationListenerDataType::setTsnInterfaceConfigurationListenerDataType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    return setTsnInterfaceConfigurationListenerDataType(*pExtensionObject, bDetach);
}

OpcUa_StatusCode TsnInterfaceConfigurationListenerDataType::setTsnInterfaceConfigurationListenerDataType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pTsnInterfaceConfigurationListenerDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(TsnInterfaceConfigurationListenerDataType, &extensionObject);

    if (pTsnInterfaceConfigurationListenerDataType != OpcUa_Null)
    {
        ret = OpcUa_Good;

        if (d_ptr->refCount() == 1)
        {
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Clear(d_ptr);
        }
        else
        {
            d_ptr->release();
            d_ptr = new TsnInterfaceConfigurationListenerDataTypePrivate();
            d_ptr->addRef();
        }

        if (bDetach == OpcUa_False)
        {
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(pTsnInterfaceConfigurationListenerDataType, d_ptr);
        }
        else
        {
            (*(MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)d_ptr) = *pTsnInterfaceConfigurationListenerDataType;
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Initialize(pTsnInterfaceConfigurationListenerDataType);
            OpcUa_ExtensionObject_Clear(&extensionObject);
        }
    }
    return ret;
}

void TsnInterfaceConfigurationListenerDataType::setTsnInterfaceConfigurationListenerDataType(
        const UaString& IpAddress,
        const UaString& InterfaceName
        )
{
    if (d_ptr->refCount() == 1)
    {
        MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Clear(d_ptr);
    }
    else
    {
        d_ptr->release();
        d_ptr = new TsnInterfaceConfigurationListenerDataTypePrivate();
        d_ptr->addRef();
    }
    setIpAddress(IpAddress);
    setInterfaceName(InterfaceName);
}

UaString TsnInterfaceConfigurationListenerDataType::getIpAddress() const
{
    return d_ptr->IpAddress;
}

UaString TsnInterfaceConfigurationListenerDataType::getInterfaceName() const
{
    return d_ptr->InterfaceName;
}

void TsnInterfaceConfigurationListenerDataType::setIpAddress(const UaString& IpAddress)
{
    if (d_ptr->refCount() > 1)
    {
        TsnInterfaceConfigurationListenerDataTypePrivate *pNew = new TsnInterfaceConfigurationListenerDataTypePrivate((const MoxaClassBased_TsnInterfaceConfigurationListenerDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }

    OpcUa_String_Clear(&d_ptr->IpAddress);
    IpAddress.copyTo(&d_ptr->IpAddress);
}

void TsnInterfaceConfigurationListenerDataType::setInterfaceName(const UaString& InterfaceName)
{
    if (d_ptr->refCount() > 1)
    {
        TsnInterfaceConfigurationListenerDataTypePrivate *pNew = new TsnInterfaceConfigurationListenerDataTypePrivate((const MoxaClassBased_TsnInterfaceConfigurationListenerDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }

    OpcUa_String_Clear(&d_ptr->InterfaceName);
    InterfaceName.copyTo(&d_ptr->InterfaceName);
}


/******************************************************************************
** Class TsnInterfaceConfigurationListenerDataTypes
******************************************************************************/
TsnInterfaceConfigurationListenerDataTypes TsnInterfaceConfigurationListenerDataTypes::empty;

TsnInterfaceConfigurationListenerDataTypes::TsnInterfaceConfigurationListenerDataTypes()
: m_noOfElements(0),
  m_data((MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_Null)
{
}

TsnInterfaceConfigurationListenerDataTypes::TsnInterfaceConfigurationListenerDataTypes(const TsnInterfaceConfigurationListenerDataTypes &other)
: m_noOfElements(0),
  m_data((MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_Null)
{
    operator=(other);
}

TsnInterfaceConfigurationListenerDataTypes::TsnInterfaceConfigurationListenerDataTypes(OpcUa_Int32 length, MoxaClassBased_TsnInterfaceConfigurationListenerDataType* data)
: m_noOfElements(0),
  m_data((MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_Null)
{
    if (length > 0 && data != OpcUa_Null)
    {
        m_noOfElements = length;
        m_data = (MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_Alloc(m_noOfElements * sizeof(MoxaClassBased_TsnInterfaceConfigurationListenerDataType));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(&(data[i]), &(m_data[i]));
        }
    }
}

TsnInterfaceConfigurationListenerDataTypes::~TsnInterfaceConfigurationListenerDataTypes()
{
    clear();
}

TsnInterfaceConfigurationListenerDataTypes& TsnInterfaceConfigurationListenerDataTypes::operator=(const TsnInterfaceConfigurationListenerDataTypes &other)
{
    if (this == &other) {return *this;}

    clear();
    if (other.m_noOfElements > 0)
    {
        m_noOfElements = other.m_noOfElements;
        m_data = (MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_Alloc(m_noOfElements * sizeof(MoxaClassBased_TsnInterfaceConfigurationListenerDataType));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(&(other.m_data[i]), &(m_data[i]));
        }
    }
    return *this;
}

/** Returns the MoxaClassBased_TsnInterfaceConfigurationListenerDataType at index position index as a modifiable reference.
 *
 *  index must be valid index position in the array.
 */
MoxaClassBased_TsnInterfaceConfigurationListenerDataType& TsnInterfaceConfigurationListenerDataTypes::operator[](OpcUa_UInt32 index)
{
    assert(index<m_noOfElements);
    return m_data[index];
}

/** Returns the MoxaClassBased_TsnInterfaceConfigurationListenerDataType at index position index.
 *
 *  index must be valid index position in the array.
 */
const MoxaClassBased_TsnInterfaceConfigurationListenerDataType& TsnInterfaceConfigurationListenerDataTypes::operator[](OpcUa_UInt32 index) const
{
    assert(index<m_noOfElements);
    return m_data[index];
}

/** Attaches the raw data.
 *
 *  Clears the array and takes the ownership of data.
 *  Don't clear the data afterwards manually, because TsnInterfaceConfigurationListenerDataTypes is responsible for it now.
 */
void TsnInterfaceConfigurationListenerDataTypes::attach(OpcUa_UInt32 length, MoxaClassBased_TsnInterfaceConfigurationListenerDataType* data)
{
    clear();
    m_data = data;
    m_noOfElements = length;
}

/** Attaches the raw data.
 *
 *  Clears the array and takes the ownership of data.
 *  Don't clear the data afterwards manually, because TsnInterfaceConfigurationListenerDataTypes is responsible for it now.
 */
void TsnInterfaceConfigurationListenerDataTypes::attach(OpcUa_Int32 length, MoxaClassBased_TsnInterfaceConfigurationListenerDataType* data)
{
    clear();
    if (length >= 0)
    {
        m_data = data;
        m_noOfElements = length;
    }
}

bool TsnInterfaceConfigurationListenerDataTypes::operator==(const TsnInterfaceConfigurationListenerDataTypes &other) const
{
    if (m_noOfElements != other.m_noOfElements) {return false;}

    if (m_noOfElements > 0)
    {
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            if (MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Compare(&(m_data[i]), &(other.m_data[i])) != OPCUA_EQUAL) {return false;};
        }
    }
    return true;
}

bool TsnInterfaceConfigurationListenerDataTypes::operator!=(const TsnInterfaceConfigurationListenerDataTypes &other) const
{
    return !(operator==(other));
}

/** Detaches the raw data from this class.
 *
 *  The caller takes ownership of the raw data and is responsible for deleting it
 *  by calling OpcUa_Free.
 *  @return The raw data.
 */
MoxaClassBased_TsnInterfaceConfigurationListenerDataType* TsnInterfaceConfigurationListenerDataTypes::detach()
{
    MoxaClassBased_TsnInterfaceConfigurationListenerDataType* pRet = m_data;
    m_noOfElements = 0;
    m_data = (MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_Null;
    return pRet;
}

void TsnInterfaceConfigurationListenerDataTypes::create(OpcUa_UInt32 length)
{
    clear();
    if (length > 0)
    {
        m_data = (MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_Alloc(length * sizeof(MoxaClassBased_TsnInterfaceConfigurationListenerDataType));
        for (OpcUa_UInt32 i = 0; i < length; i++)
        {
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Initialize(&(m_data[i]));
        }
        m_noOfElements = length;
    }
}

void TsnInterfaceConfigurationListenerDataTypes::resize(OpcUa_UInt32 length)
{
    if (length < m_noOfElements)
    {
        if (length != 0)
        {
            for (OpcUa_UInt32 i = length; i < m_noOfElements; i++)
            {
                MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Clear(&(m_data[i]));
            }

            MoxaClassBased_TsnInterfaceConfigurationListenerDataType* newData = (MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_ReAlloc(m_data, length * sizeof(MoxaClassBased_TsnInterfaceConfigurationListenerDataType));
            if (newData)
            {
                m_data = newData;
                m_noOfElements = length;
            }
        }
        else
        {
            clear();
        }
    }
    else if (length > m_noOfElements)
    {
        MoxaClassBased_TsnInterfaceConfigurationListenerDataType* newData = (MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_ReAlloc(m_data, length * sizeof(MoxaClassBased_TsnInterfaceConfigurationListenerDataType));
        if (newData)
        {
            for (OpcUa_UInt32 i = m_noOfElements; i < length; i++)
            {
                MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Initialize(&(newData[i]));
            }
            m_data = newData;
            m_noOfElements = length;
        }
    }
}

void TsnInterfaceConfigurationListenerDataTypes::clear()
{
    if (m_data)
    {
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Clear(&(m_data[i]));
        }
        OpcUa_Free(m_data);
        m_data = (MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_Null;
    }
    m_noOfElements = 0;
}

void TsnInterfaceConfigurationListenerDataTypes::toVariant(UaVariant &variant) const
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    toVariant(*pVariant);
}

void TsnInterfaceConfigurationListenerDataTypes::toVariant(OpcUa_Variant &variant) const
{
    OpcUa_Variant_Clear(&variant);

    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Array;
    variant.Value.Array.Length = m_noOfElements;
    variant.Value.Array.Value.ExtensionObjectArray = (OpcUa_ExtensionObject*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUa_ExtensionObject));
    for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
    {
        MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pValue = OpcUa_Null;
        OpcUa_ExtensionObject_Initialize(&variant.Value.Array.Value.ExtensionObjectArray[i]);
        OpcUa_EncodeableObject_CreateExtension(&MoxaClassBased_TsnInterfaceConfigurationListenerDataType_EncodeableType,
                                               &variant.Value.Array.Value.ExtensionObjectArray[i],
                                               (OpcUa_Void**)&pValue);
        MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(&m_data[i], pValue);
    }
}

void TsnInterfaceConfigurationListenerDataTypes::toVariant(UaVariant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    toVariant(*pVariant, bDetach);
}

void TsnInterfaceConfigurationListenerDataTypes::toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Array;
    variant.Value.Array.Length = m_noOfElements;
    variant.Value.Array.Value.ExtensionObjectArray = (OpcUa_ExtensionObject*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUa_ExtensionObject));
    for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
    {
        MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pValue = OpcUa_Null;
        OpcUa_ExtensionObject_Initialize(&variant.Value.Array.Value.ExtensionObjectArray[i]);
        OpcUa_EncodeableObject_CreateExtension(&MoxaClassBased_TsnInterfaceConfigurationListenerDataType_EncodeableType,
                                               &variant.Value.Array.Value.ExtensionObjectArray[i],
                                               (OpcUa_Void**)&pValue);
        if (bDetach != OpcUa_False)
        {
            *pValue = m_data[i];
        }
        else
        {
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(&m_data[i], pValue);
        }
    }
    if (bDetach != OpcUa_False)
    {
        OpcUa_Free(m_data);
        m_data = (MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_Null;
        m_noOfElements = 0;
    }
}

void TsnInterfaceConfigurationListenerDataTypes::toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    UaVariant variant;
    toVariant(variant);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void TsnInterfaceConfigurationListenerDataTypes::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    toVariant(dataValue.Value);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

void TsnInterfaceConfigurationListenerDataTypes::toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    UaVariant variant;
    toVariant(variant, bDetach);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void TsnInterfaceConfigurationListenerDataTypes::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    toVariant(dataValue.Value, bDetach);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

OpcUa_StatusCode TsnInterfaceConfigurationListenerDataTypes::setTsnInterfaceConfigurationListenerDataTypes(const UaVariant &variant)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    return setTsnInterfaceConfigurationListenerDataTypes(*pVariant);
}

OpcUa_StatusCode TsnInterfaceConfigurationListenerDataTypes::setTsnInterfaceConfigurationListenerDataTypes(const OpcUa_Variant &variant)
{
    return setTsnInterfaceConfigurationListenerDataTypes((OpcUa_Variant&)variant, OpcUa_False);
}

OpcUa_StatusCode TsnInterfaceConfigurationListenerDataTypes::setTsnInterfaceConfigurationListenerDataTypes(UaVariant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    return setTsnInterfaceConfigurationListenerDataTypes(*pVariant, bDetach);
}

OpcUa_StatusCode TsnInterfaceConfigurationListenerDataTypes::setTsnInterfaceConfigurationListenerDataTypes(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    clear();

    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    if (variant.Datatype == OpcUaType_ExtensionObject &&
        variant.ArrayType == OpcUa_VariantArrayType_Array)
    {
        ret = OpcUa_Good;
        m_noOfElements = variant.Value.Array.Length >= 0 ? variant.Value.Array.Length : 0;
        if (m_noOfElements > 0 && variant.Value.Array.Value.ExtensionObjectArray != OpcUa_Null)
        {
            m_data = (MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_Alloc(m_noOfElements * sizeof(MoxaClassBased_TsnInterfaceConfigurationListenerDataType));

            OpcUa_UInt32 i = 0;
            for (i = 0; i < m_noOfElements; i++)
            {
                MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Initialize(&m_data[i]);

                MoxaClassBased_TsnInterfaceConfigurationListenerDataType *pValue = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(TsnInterfaceConfigurationListenerDataType, &variant.Value.Array.Value.ExtensionObjectArray[i]);
                if (pValue)
                {
                    if (bDetach != OpcUa_False)
                    {
                        m_data[i] = *pValue;
                        MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Initialize(pValue);
                    }
                    else
                    {
                        MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(pValue, &m_data[i]);
                    }
                }
                else
                {
                    ret = OpcUa_BadTypeMismatch;
                    break;
                }
            }
            if (OpcUa_IsNotGood(ret))
            {
                for (OpcUa_UInt32 j = 0; j < i; j++)
                {
                    MoxaClassBased_TsnInterfaceConfigurationListenerDataType_Clear(&m_data[j]);
                }
                OpcUa_Free(m_data);
                m_data = (MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_Null;
                m_noOfElements = 0;
            }
        }
        else
        {
            m_noOfElements = 0;
        }
    }
    return ret;
}

OpcUa_StatusCode TsnInterfaceConfigurationListenerDataTypes::setTsnInterfaceConfigurationListenerDataTypes(OpcUa_Int32 length, MoxaClassBased_TsnInterfaceConfigurationListenerDataType* data)
{
    clear();

    if (length > 0 && data != OpcUa_Null)
    {
        m_noOfElements = length;
        m_data = (MoxaClassBased_TsnInterfaceConfigurationListenerDataType*)OpcUa_Alloc(m_noOfElements * sizeof(MoxaClassBased_TsnInterfaceConfigurationListenerDataType));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            MoxaClassBased_TsnInterfaceConfigurationListenerDataType_CopyTo(&(data[i]), &(m_data[i]));
        }
    }
    return OpcUa_Good;
}

} // namespace MoxaClassBased

