/******************************************************************************
** opcuaclassbnm_tsnstreamfailuresystemidentifier.cpp
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://opcfoundation.org/UA/BNM/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#include "opcuaclassbnm_tsnstreamfailuresystemidentifier.h"

#include <opcua_datetime.h>

#include "uavariant.h"
#include "uadatavalue.h"
#include "uaextensionobject.h"
#include "uaatomic.h"

// Namespace for the UA information model http://opcfoundation.org/UA/BNM/
namespace OpcUaClassBnm {

/******************************************************************************
** Class TsnStreamFailureSystemIdentifierPrivate
******************************************************************************/
class TsnStreamFailureSystemIdentifierPrivate : private OpcUaClassBnm_TsnStreamFailureSystemIdentifier
{
    TsnStreamFailureSystemIdentifierPrivate(const TsnStreamFailureSystemIdentifierPrivate &other);
    TsnStreamFailureSystemIdentifierPrivate& operator=(const TsnStreamFailureSystemIdentifierPrivate&);
public:
    TsnStreamFailureSystemIdentifierPrivate();
    explicit TsnStreamFailureSystemIdentifierPrivate(bool bStatic);
    explicit TsnStreamFailureSystemIdentifierPrivate(const OpcUaClassBnm_TsnStreamFailureSystemIdentifier &other);
    ~TsnStreamFailureSystemIdentifierPrivate();

    int addRef();
    int release();
    inline int refCount() { return m_iRefCnt; }

private:
    int m_iRefCnt;
    friend class TsnStreamFailureSystemIdentifier;
};

/* construction */
TsnStreamFailureSystemIdentifierPrivate::TsnStreamFailureSystemIdentifierPrivate()
 : m_iRefCnt(0)
{
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Initialize(this);
}

/*  Static initializer.
 *  This is used internaly to initialize the static shared_emtpy variable.
 *  RefCnt is set to 1 so it will never be deleted.
 */
TsnStreamFailureSystemIdentifierPrivate::TsnStreamFailureSystemIdentifierPrivate(bool)
 : m_iRefCnt(1)
{
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Initialize(this);
}


/*  construction
 */
TsnStreamFailureSystemIdentifierPrivate::TsnStreamFailureSystemIdentifierPrivate(const OpcUaClassBnm_TsnStreamFailureSystemIdentifier &other) // [in] the other OpcUaClassBnm_TsnStreamFailureSystemIdentifier.
 : m_iRefCnt(0)
{
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(&other, this);
}

/* destruction */
TsnStreamFailureSystemIdentifierPrivate::~TsnStreamFailureSystemIdentifierPrivate()
{
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Clear(this);
}

/*  Add a reference to a TsnStreamFailureSystemIdentifierPrivate
 *  @return 0 if the object was deleted - otherwise a value bigger than 0.
 *  This method is not thread save regarding the return value. The returned counter is only reliable when it is 0.
 *  Other values are not reliable and should not be used for any logic.
 */
int TsnStreamFailureSystemIdentifierPrivate::addRef()
{
    return ua_atomic_increment(&m_iRefCnt);
}

/*  Release a TsnStreamFailureSystemIdentifierPrivate.
 *  @return the reference count.
 */
int TsnStreamFailureSystemIdentifierPrivate::release()
{
    int currentCount = ua_atomic_decrement(&m_iRefCnt);
    if (currentCount == 0)
    {
        delete this;
    }
    return currentCount;
}

TsnStreamFailureSystemIdentifierPrivate* shared_empty_TsnStreamFailureSystemIdentifier()
{
    static TsnStreamFailureSystemIdentifierPrivate shared_static(true);
    return &shared_static;
}


/******************************************************************************
** Class TsnStreamFailureSystemIdentifier
******************************************************************************/

/** Constructs an instance of the class TsnStreamFailureSystemIdentifier with empty default values
*/
TsnStreamFailureSystemIdentifier::TsnStreamFailureSystemIdentifier()
{
    d_ptr = shared_empty_TsnStreamFailureSystemIdentifier();
    d_ptr->addRef();
}

/** Constructs an instance of the class TsnStreamFailureSystemIdentifier with values from another TsnStreamFailureSystemIdentifier object
 *  @param other the other UaTsnStreamFailureSystemIdentifier used to initialize the object
 */
TsnStreamFailureSystemIdentifier::TsnStreamFailureSystemIdentifier(const TsnStreamFailureSystemIdentifier &other)
{
    d_ptr = other.d_ptr;
    d_ptr->addRef();
}

/** Constructs an instance of the class TsnStreamFailureSystemIdentifier with values from another OpcUaClassBnm_TsnStreamFailureSystemIdentifier structure
 *  @param other the other OpcUaClassBnm_TsnStreamFailureSystemIdentifier used to initialize the object
 */
TsnStreamFailureSystemIdentifier::TsnStreamFailureSystemIdentifier(const OpcUaClassBnm_TsnStreamFailureSystemIdentifier &other)
{
    d_ptr = new TsnStreamFailureSystemIdentifierPrivate(other);
    d_ptr->addRef();
}

/** Constructs an instance of the class TsnStreamFailureSystemIdentifier with values provided in the constructor
 */
TsnStreamFailureSystemIdentifier::TsnStreamFailureSystemIdentifier(
        const UaByteArray& SystemIdentifier
        )
{
    d_ptr = new TsnStreamFailureSystemIdentifierPrivate();
    d_ptr->addRef();
    setSystemIdentifier(SystemIdentifier);
}

/** Constructs an instance of the class TsnStreamFailureSystemIdentifier initialized with value from a UaExtensionObject
 *  @param extensionObject the extension object containing the TsnStreamFailureSystemIdentifier
 */
TsnStreamFailureSystemIdentifier::TsnStreamFailureSystemIdentifier(const UaExtensionObject &extensionObject)
{
    d_ptr = new TsnStreamFailureSystemIdentifierPrivate();
    d_ptr->addRef();

    const OpcUa_ExtensionObject *pExtensionObject = (const OpcUa_ExtensionObject*)extensionObject;
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pTsnStreamFailureSystemIdentifier = OPCUACLASSBNM_EXTENSIONOBJECT_GET_ENCODEABLE(TsnStreamFailureSystemIdentifier, pExtensionObject);

    if (pTsnStreamFailureSystemIdentifier)
    {
        OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(pTsnStreamFailureSystemIdentifier, d_ptr);
    }
}

/** Constructs an instance of the class TsnStreamFailureSystemIdentifier initialized with value from an OpcUa_ExtensionObject structure
 *  @param extensionObject the extension object containing the TsnStreamFailureSystemIdentifier
 */
TsnStreamFailureSystemIdentifier::TsnStreamFailureSystemIdentifier(const OpcUa_ExtensionObject &extensionObject)
{
    d_ptr = new TsnStreamFailureSystemIdentifierPrivate();
    d_ptr->addRef();

    OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pTsnStreamFailureSystemIdentifier = OPCUACLASSBNM_EXTENSIONOBJECT_GET_ENCODEABLE(TsnStreamFailureSystemIdentifier, &extensionObject);

    if (pTsnStreamFailureSystemIdentifier)
    {
        OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(pTsnStreamFailureSystemIdentifier, d_ptr);
    }
}

TsnStreamFailureSystemIdentifier::TsnStreamFailureSystemIdentifier(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    d_ptr = new TsnStreamFailureSystemIdentifierPrivate();
    d_ptr->addRef();

    const OpcUa_ExtensionObject *pExtensionObject = (const OpcUa_ExtensionObject*)extensionObject;
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pTsnStreamFailureSystemIdentifier = OPCUACLASSBNM_EXTENSIONOBJECT_GET_ENCODEABLE(TsnStreamFailureSystemIdentifier, pExtensionObject);
    if (pTsnStreamFailureSystemIdentifier)
    {
        if (bDetach == OpcUa_False)
        {
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(pTsnStreamFailureSystemIdentifier, d_ptr);
        }
        else
        {
            (*(OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)d_ptr) = *pTsnStreamFailureSystemIdentifier;
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Initialize(pTsnStreamFailureSystemIdentifier);
            extensionObject.clear();
        }
    }
}

TsnStreamFailureSystemIdentifier::TsnStreamFailureSystemIdentifier(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    d_ptr = new TsnStreamFailureSystemIdentifierPrivate();
    d_ptr->addRef();

    OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pTsnStreamFailureSystemIdentifier = OPCUACLASSBNM_EXTENSIONOBJECT_GET_ENCODEABLE(TsnStreamFailureSystemIdentifier, &extensionObject);

    if (pTsnStreamFailureSystemIdentifier)
    {
        if (bDetach == OpcUa_False)
        {
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(pTsnStreamFailureSystemIdentifier, d_ptr);
        }
        else
        {
            (*(OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)d_ptr) = *pTsnStreamFailureSystemIdentifier;
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Initialize(pTsnStreamFailureSystemIdentifier);
            OpcUa_ExtensionObject_Clear(&extensionObject);
        }
    }
}

/** Destroys the TsnStreamFailureSystemIdentifier object
*/
TsnStreamFailureSystemIdentifier::~TsnStreamFailureSystemIdentifier()
{
    OPCUACLASSBNM_D(TsnStreamFailureSystemIdentifier);
    d->release();
}

/** Clear the data of the TsnStreamFailureSystemIdentifier.
*/
void TsnStreamFailureSystemIdentifier::clear()
{
    d_ptr->release();
    d_ptr = shared_empty_TsnStreamFailureSystemIdentifier();
    d_ptr->addRef();
}

/** Compare two TsnStreamFailureSystemIdentifier if they are similar.
 *  @param other the TsnStreamFailureSystemIdentifier to compare.
 *  @return true if similar, false if not.
 */
bool TsnStreamFailureSystemIdentifier::operator==(const TsnStreamFailureSystemIdentifier &other) const
{
    return (OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Compare(d_ptr, other.d_ptr) == 0);
}

/** Returns true if the other TsnStreamFailureSystemIdentifier is not equal to this.
 *  @see operator==
 *  @param other the TsnStreamFailureSystemIdentifier to compare.
 *  @return true if other is not equal to this.
 */
bool TsnStreamFailureSystemIdentifier::operator!=(const TsnStreamFailureSystemIdentifier &other) const
{
    return !(operator==(other));
}

/** Assignment operator.
 *  @param other the TsnStreamFailureSystemIdentifier to assign.
 *  @return Assignment operator.
 */
TsnStreamFailureSystemIdentifier& TsnStreamFailureSystemIdentifier::operator=(const TsnStreamFailureSystemIdentifier &other)
{
    other.d_ptr->addRef();
    d_ptr->release();
    d_ptr = other.d_ptr;
    return *this;
}

/** Copy TsnStreamFailureSystemIdentifier data to a newly allocated OpcUaClassBnm_TsnStreamFailureSystemIdentifier.
 *  @return data to a newly allocated OpcUaClassBnm_TsnStreamFailureSystemIdentifier.
 */
OpcUaClassBnm_TsnStreamFailureSystemIdentifier* TsnStreamFailureSystemIdentifier::copy() const
{
    return clone(*d_ptr);
}

/** Copy TsnStreamFailureSystemIdentifier data to an existing OpcUaClassBnm_TsnStreamFailureSystemIdentifier structure.
 *  @param pDst the destination of this copy operation.
 */
void TsnStreamFailureSystemIdentifier::copyTo(OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pDst) const
{
    if (pDst == OpcUa_Null) return;
    cloneTo(*d_ptr, *pDst);
}

/** Copy OpcUaClassBnm_TsnStreamFailureSystemIdentifier data to a newly allocated OpcUaClassBnm_TsnStreamFailureSystemIdentifier.
 *  @param source Source to clone.
 *  @return new copy.
 */
OpcUaClassBnm_TsnStreamFailureSystemIdentifier* TsnStreamFailureSystemIdentifier::clone(const OpcUaClassBnm_TsnStreamFailureSystemIdentifier& source)
{
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier* pTsnStreamFailureSystemIdentifier = OpcUa_Null;
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Copy(&source, &pTsnStreamFailureSystemIdentifier);
    return pTsnStreamFailureSystemIdentifier;
}

/** Copy OpcUaClassBnm_TsnStreamFailureSystemIdentifier data to an existing OpcUaClassBnm_TsnStreamFailureSystemIdentifier structure.
 *  @param source the source of the clone operation.
 *  @param copy the destination of the clone operation.
 */
void TsnStreamFailureSystemIdentifier::cloneTo(const OpcUaClassBnm_TsnStreamFailureSystemIdentifier& source, OpcUaClassBnm_TsnStreamFailureSystemIdentifier& copy)
{
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(&source, &copy);
}

/** Attaches the data of the parameter pValue.
 * Don't clear the data of pValue afterwards manually, because TsnStreamFailureSystemIdentifier is responsible for it now.
 */
void TsnStreamFailureSystemIdentifier::attach(const OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pValue) //!< [in] Parameter to attach to.
{
    if (pValue == OpcUa_Null) return;
    if (d_ptr->refCount() == 1)
    {
        OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Clear(d_ptr);
    }
    else
    {
        d_ptr->release();
        d_ptr = new TsnStreamFailureSystemIdentifierPrivate();
        d_ptr->addRef();
    }
    // copy data value structure (no deep copy)
    OpcUa_MemCpy(d_ptr, sizeof(OpcUaClassBnm_TsnStreamFailureSystemIdentifier), (void*)pValue, sizeof(OpcUaClassBnm_TsnStreamFailureSystemIdentifier));
}

/** Detaches the internal TsnStreamFailureSystemIdentifier structure from this class.
 *  This way you take over the control of releasing the TsnStreamFailureSystemIdentifier data.
 *  If more than one references exist, the data is copied to pDst instead of being detached.
 *  @return If the functions succeeds pDst is returned, otherwise 0 is returned.
 */
OpcUaClassBnm_TsnStreamFailureSystemIdentifier* TsnStreamFailureSystemIdentifier::detach(OpcUaClassBnm_TsnStreamFailureSystemIdentifier* pDst) //!< [out] Pointer to OpcUaClassBnm_TsnStreamFailureSystemIdentifier structure that receives the TsnStreamFailureSystemIdentifier data.
{
    if (pDst == OpcUa_Null) return OpcUa_Null;
    if (d_ptr->refCount() == 1)
    {
        OpcUa_MemCpy(pDst, sizeof(OpcUaClassBnm_TsnStreamFailureSystemIdentifier), d_ptr, sizeof(OpcUaClassBnm_TsnStreamFailureSystemIdentifier));
        // clear internal data without releasing deeper memory
        OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Initialize(d_ptr);
    }
    else
    {
        OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(d_ptr, pDst);
    }
    d_ptr->release();
    d_ptr = shared_empty_TsnStreamFailureSystemIdentifier();
    d_ptr->addRef();
    return pDst;
}

void TsnStreamFailureSystemIdentifier::toVariant(UaVariant &variant) const
{
    UaExtensionObject extensionObject;
    toExtensionObject(extensionObject);
    variant.setExtensionObject(extensionObject, OpcUa_True);
}

void TsnStreamFailureSystemIdentifier::toVariant(OpcUa_Variant &variant) const
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Scalar;
    variant.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(variant.Value.ExtensionObject);
    toExtensionObject(*variant.Value.ExtensionObject);
}

void TsnStreamFailureSystemIdentifier::toVariant(UaVariant &variant, OpcUa_Boolean bDetach)
{
    UaExtensionObject extensionObject;
    toExtensionObject(extensionObject, bDetach);
    variant.setExtensionObject(extensionObject, OpcUa_True);
}

void TsnStreamFailureSystemIdentifier::toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Scalar;
    variant.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(variant.Value.ExtensionObject);
    toExtensionObject(*variant.Value.ExtensionObject, bDetach);
}

void TsnStreamFailureSystemIdentifier::toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    UaVariant variant;
    toVariant(variant);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void TsnStreamFailureSystemIdentifier::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    OpcUa_Variant_Clear(&dataValue.Value);
    dataValue.Value.Datatype = OpcUaType_ExtensionObject;
    dataValue.Value.ArrayType = OpcUa_VariantArrayType_Scalar;
    dataValue.Value.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(dataValue.Value.Value.ExtensionObject);
    toExtensionObject(*dataValue.Value.Value.ExtensionObject);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

void TsnStreamFailureSystemIdentifier::toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    UaVariant variant;
    toVariant(variant, bDetach);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void TsnStreamFailureSystemIdentifier::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    OpcUa_Variant_Clear(&dataValue.Value);
    dataValue.Value.Datatype = OpcUaType_ExtensionObject;
    dataValue.Value.ArrayType = OpcUa_VariantArrayType_Scalar;
    dataValue.Value.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(dataValue.Value.Value.ExtensionObject);
    toExtensionObject(*dataValue.Value.Value.ExtensionObject, bDetach);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

void TsnStreamFailureSystemIdentifier::toExtensionObject(UaExtensionObject &extensionObject) const
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    toExtensionObject(*pExtensionObject);
}

void TsnStreamFailureSystemIdentifier::toExtensionObject(OpcUa_ExtensionObject &extensionObject) const
{
    OpcUa_ExtensionObject_Clear(&extensionObject);
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pTsnStreamFailureSystemIdentifier = OpcUa_Null;
    if (OpcUa_IsGood(OpcUa_EncodeableObject_CreateExtension(&OpcUaClassBnm_TsnStreamFailureSystemIdentifier_EncodeableType,
                                                            &extensionObject,
                                                            (OpcUa_Void**)&pTsnStreamFailureSystemIdentifier)))
    {
        OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(d_ptr, pTsnStreamFailureSystemIdentifier);
    }
}

void TsnStreamFailureSystemIdentifier::toExtensionObject(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    toExtensionObject(*pExtensionObject, bDetach);
}

void TsnStreamFailureSystemIdentifier::toExtensionObject(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject_Clear(&extensionObject);
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pTsnStreamFailureSystemIdentifier = OpcUa_Null;
    if (OpcUa_IsGood(OpcUa_EncodeableObject_CreateExtension(&OpcUaClassBnm_TsnStreamFailureSystemIdentifier_EncodeableType,
                                                            &extensionObject,
                                                            (OpcUa_Void**)&pTsnStreamFailureSystemIdentifier)))
    {
        OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Initialize(pTsnStreamFailureSystemIdentifier);
        if (bDetach != OpcUa_False && d_ptr->refCount() == 1)
        {
            *pTsnStreamFailureSystemIdentifier = *d_ptr;
            // clear internal data without releasing deeper memory
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Initialize(d_ptr);
        }
        else
        {
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(d_ptr, pTsnStreamFailureSystemIdentifier);
        }
        if (bDetach != OpcUa_False)
        {
            d_ptr->release();
            d_ptr = shared_empty_TsnStreamFailureSystemIdentifier();
            d_ptr->addRef();
        }
    }
}

OpcUa_StatusCode TsnStreamFailureSystemIdentifier::setTsnStreamFailureSystemIdentifier(const UaExtensionObject &extensionObject)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    return setTsnStreamFailureSystemIdentifier(*pExtensionObject);
}

OpcUa_StatusCode TsnStreamFailureSystemIdentifier::setTsnStreamFailureSystemIdentifier(const OpcUa_ExtensionObject &extensionObject)
{
    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pTsnStreamFailureSystemIdentifier = OPCUACLASSBNM_EXTENSIONOBJECT_GET_ENCODEABLE(TsnStreamFailureSystemIdentifier, &extensionObject);

    if (pTsnStreamFailureSystemIdentifier)
    {
        ret = OpcUa_Good;

        if (d_ptr->refCount() == 1)
        {
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Clear(d_ptr);
        }
        else
        {
            d_ptr->release();
            d_ptr = new TsnStreamFailureSystemIdentifierPrivate();
            d_ptr->addRef();
        }

        OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(pTsnStreamFailureSystemIdentifier, d_ptr);
    }
    return ret;
}

OpcUa_StatusCode TsnStreamFailureSystemIdentifier::setTsnStreamFailureSystemIdentifier(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    return setTsnStreamFailureSystemIdentifier(*pExtensionObject, bDetach);
}

OpcUa_StatusCode TsnStreamFailureSystemIdentifier::setTsnStreamFailureSystemIdentifier(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pTsnStreamFailureSystemIdentifier = OPCUACLASSBNM_EXTENSIONOBJECT_GET_ENCODEABLE(TsnStreamFailureSystemIdentifier, &extensionObject);

    if (pTsnStreamFailureSystemIdentifier != OpcUa_Null)
    {
        ret = OpcUa_Good;

        if (d_ptr->refCount() == 1)
        {
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Clear(d_ptr);
        }
        else
        {
            d_ptr->release();
            d_ptr = new TsnStreamFailureSystemIdentifierPrivate();
            d_ptr->addRef();
        }

        if (bDetach == OpcUa_False)
        {
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(pTsnStreamFailureSystemIdentifier, d_ptr);
        }
        else
        {
            (*(OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)d_ptr) = *pTsnStreamFailureSystemIdentifier;
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Initialize(pTsnStreamFailureSystemIdentifier);
            OpcUa_ExtensionObject_Clear(&extensionObject);
        }
    }
    return ret;
}

void TsnStreamFailureSystemIdentifier::setTsnStreamFailureSystemIdentifier(
        const UaByteArray& SystemIdentifier
        )
{
    if (d_ptr->refCount() == 1)
    {
        OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Clear(d_ptr);
    }
    else
    {
        d_ptr->release();
        d_ptr = new TsnStreamFailureSystemIdentifierPrivate();
        d_ptr->addRef();
    }
    setSystemIdentifier(SystemIdentifier);
}

void TsnStreamFailureSystemIdentifier::getSystemIdentifier(UaByteArray& SystemIdentifier) const
{
    SystemIdentifier.resize(0);
    if (d_ptr->NoOfSystemIdentifier > 0)
    {
        SystemIdentifier.resize(d_ptr->NoOfSystemIdentifier);
        OpcUa_MemCpy((OpcUa_Byte*)SystemIdentifier.data(), d_ptr->NoOfSystemIdentifier * sizeof(OpcUa_Byte),
                     d_ptr->SystemIdentifier, d_ptr->NoOfSystemIdentifier * sizeof(OpcUa_Byte));
    }
}

void TsnStreamFailureSystemIdentifier::setSystemIdentifier(const UaByteArray& SystemIdentifier)
{
    if (d_ptr->refCount() > 1)
    {
        TsnStreamFailureSystemIdentifierPrivate *pNew = new TsnStreamFailureSystemIdentifierPrivate((const OpcUaClassBnm_TsnStreamFailureSystemIdentifier)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }
    if (d_ptr->NoOfSystemIdentifier > 0)
    {
        OpcUa_Free(d_ptr->SystemIdentifier);
        d_ptr->SystemIdentifier = OpcUa_Null;
    }

    d_ptr->NoOfSystemIdentifier = SystemIdentifier.size();
    if (d_ptr->NoOfSystemIdentifier > 0)
    {
        d_ptr->SystemIdentifier = (OpcUa_Byte*)OpcUa_Alloc(d_ptr->NoOfSystemIdentifier * sizeof(OpcUa_Byte));
        if (d_ptr->SystemIdentifier != OpcUa_Null)
        {
            OpcUa_MemCpy((OpcUa_Byte*)d_ptr->SystemIdentifier, d_ptr->NoOfSystemIdentifier * sizeof(OpcUa_Byte),
                         (OpcUa_Byte*)SystemIdentifier.data(), d_ptr->NoOfSystemIdentifier * sizeof(OpcUa_Byte));
        }
        else
        {
            d_ptr->NoOfSystemIdentifier = 0;
        }
    }
}


/******************************************************************************
** Class TsnStreamFailureSystemIdentifiers
******************************************************************************/
TsnStreamFailureSystemIdentifiers TsnStreamFailureSystemIdentifiers::empty;

TsnStreamFailureSystemIdentifiers::TsnStreamFailureSystemIdentifiers()
: m_noOfElements(0),
  m_data((OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_Null)
{
}

TsnStreamFailureSystemIdentifiers::TsnStreamFailureSystemIdentifiers(const TsnStreamFailureSystemIdentifiers &other)
: m_noOfElements(0),
  m_data((OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_Null)
{
    operator=(other);
}

TsnStreamFailureSystemIdentifiers::TsnStreamFailureSystemIdentifiers(OpcUa_Int32 length, OpcUaClassBnm_TsnStreamFailureSystemIdentifier* data)
: m_noOfElements(0),
  m_data((OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_Null)
{
    if (length > 0 && data != OpcUa_Null)
    {
        m_noOfElements = length;
        m_data = (OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUaClassBnm_TsnStreamFailureSystemIdentifier));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(&(data[i]), &(m_data[i]));
        }
    }
}

TsnStreamFailureSystemIdentifiers::~TsnStreamFailureSystemIdentifiers()
{
    clear();
}

TsnStreamFailureSystemIdentifiers& TsnStreamFailureSystemIdentifiers::operator=(const TsnStreamFailureSystemIdentifiers &other)
{
    if (this == &other) {return *this;}

    clear();
    if (other.m_noOfElements > 0)
    {
        m_noOfElements = other.m_noOfElements;
        m_data = (OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUaClassBnm_TsnStreamFailureSystemIdentifier));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(&(other.m_data[i]), &(m_data[i]));
        }
    }
    return *this;
}

/** Returns the OpcUaClassBnm_TsnStreamFailureSystemIdentifier at index position index as a modifiable reference.
 *
 *  index must be valid index position in the array.
 */
OpcUaClassBnm_TsnStreamFailureSystemIdentifier& TsnStreamFailureSystemIdentifiers::operator[](OpcUa_UInt32 index)
{
    assert(index<m_noOfElements);
    return m_data[index];
}

/** Returns the OpcUaClassBnm_TsnStreamFailureSystemIdentifier at index position index.
 *
 *  index must be valid index position in the array.
 */
const OpcUaClassBnm_TsnStreamFailureSystemIdentifier& TsnStreamFailureSystemIdentifiers::operator[](OpcUa_UInt32 index) const
{
    assert(index<m_noOfElements);
    return m_data[index];
}

/** Attaches the raw data.
 *
 *  Clears the array and takes the ownership of data.
 *  Don't clear the data afterwards manually, because TsnStreamFailureSystemIdentifiers is responsible for it now.
 */
void TsnStreamFailureSystemIdentifiers::attach(OpcUa_UInt32 length, OpcUaClassBnm_TsnStreamFailureSystemIdentifier* data)
{
    clear();
    m_data = data;
    m_noOfElements = length;
}

/** Attaches the raw data.
 *
 *  Clears the array and takes the ownership of data.
 *  Don't clear the data afterwards manually, because TsnStreamFailureSystemIdentifiers is responsible for it now.
 */
void TsnStreamFailureSystemIdentifiers::attach(OpcUa_Int32 length, OpcUaClassBnm_TsnStreamFailureSystemIdentifier* data)
{
    clear();
    if (length >= 0)
    {
        m_data = data;
        m_noOfElements = length;
    }
}

bool TsnStreamFailureSystemIdentifiers::operator==(const TsnStreamFailureSystemIdentifiers &other) const
{
    if (m_noOfElements != other.m_noOfElements) {return false;}

    if (m_noOfElements > 0)
    {
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            if (OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Compare(&(m_data[i]), &(other.m_data[i])) != OPCUA_EQUAL) {return false;};
        }
    }
    return true;
}

bool TsnStreamFailureSystemIdentifiers::operator!=(const TsnStreamFailureSystemIdentifiers &other) const
{
    return !(operator==(other));
}

/** Detaches the raw data from this class.
 *
 *  The caller takes ownership of the raw data and is responsible for deleting it
 *  by calling OpcUa_Free.
 *  @return The raw data.
 */
OpcUaClassBnm_TsnStreamFailureSystemIdentifier* TsnStreamFailureSystemIdentifiers::detach()
{
    OpcUaClassBnm_TsnStreamFailureSystemIdentifier* pRet = m_data;
    m_noOfElements = 0;
    m_data = (OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_Null;
    return pRet;
}

void TsnStreamFailureSystemIdentifiers::create(OpcUa_UInt32 length)
{
    clear();
    if (length > 0)
    {
        m_data = (OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_Alloc(length * sizeof(OpcUaClassBnm_TsnStreamFailureSystemIdentifier));
        for (OpcUa_UInt32 i = 0; i < length; i++)
        {
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Initialize(&(m_data[i]));
        }
        m_noOfElements = length;
    }
}

void TsnStreamFailureSystemIdentifiers::resize(OpcUa_UInt32 length)
{
    if (length < m_noOfElements)
    {
        if (length != 0)
        {
            for (OpcUa_UInt32 i = length; i < m_noOfElements; i++)
            {
                OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Clear(&(m_data[i]));
            }

            OpcUaClassBnm_TsnStreamFailureSystemIdentifier* newData = (OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_ReAlloc(m_data, length * sizeof(OpcUaClassBnm_TsnStreamFailureSystemIdentifier));
            if (newData)
            {
                m_data = newData;
                m_noOfElements = length;
            }
        }
        else
        {
            clear();
        }
    }
    else if (length > m_noOfElements)
    {
        OpcUaClassBnm_TsnStreamFailureSystemIdentifier* newData = (OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_ReAlloc(m_data, length * sizeof(OpcUaClassBnm_TsnStreamFailureSystemIdentifier));
        if (newData)
        {
            for (OpcUa_UInt32 i = m_noOfElements; i < length; i++)
            {
                OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Initialize(&(newData[i]));
            }
            m_data = newData;
            m_noOfElements = length;
        }
    }
}

void TsnStreamFailureSystemIdentifiers::clear()
{
    if (m_data)
    {
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Clear(&(m_data[i]));
        }
        OpcUa_Free(m_data);
        m_data = (OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_Null;
    }
    m_noOfElements = 0;
}

void TsnStreamFailureSystemIdentifiers::toVariant(UaVariant &variant) const
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    toVariant(*pVariant);
}

void TsnStreamFailureSystemIdentifiers::toVariant(OpcUa_Variant &variant) const
{
    OpcUa_Variant_Clear(&variant);

    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Array;
    variant.Value.Array.Length = m_noOfElements;
    variant.Value.Array.Value.ExtensionObjectArray = (OpcUa_ExtensionObject*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUa_ExtensionObject));
    for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
    {
        OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pValue = OpcUa_Null;
        OpcUa_ExtensionObject_Initialize(&variant.Value.Array.Value.ExtensionObjectArray[i]);
        OpcUa_EncodeableObject_CreateExtension(&OpcUaClassBnm_TsnStreamFailureSystemIdentifier_EncodeableType,
                                               &variant.Value.Array.Value.ExtensionObjectArray[i],
                                               (OpcUa_Void**)&pValue);
        OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(&m_data[i], pValue);
    }
}

void TsnStreamFailureSystemIdentifiers::toVariant(UaVariant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    toVariant(*pVariant, bDetach);
}

void TsnStreamFailureSystemIdentifiers::toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Array;
    variant.Value.Array.Length = m_noOfElements;
    variant.Value.Array.Value.ExtensionObjectArray = (OpcUa_ExtensionObject*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUa_ExtensionObject));
    for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
    {
        OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pValue = OpcUa_Null;
        OpcUa_ExtensionObject_Initialize(&variant.Value.Array.Value.ExtensionObjectArray[i]);
        OpcUa_EncodeableObject_CreateExtension(&OpcUaClassBnm_TsnStreamFailureSystemIdentifier_EncodeableType,
                                               &variant.Value.Array.Value.ExtensionObjectArray[i],
                                               (OpcUa_Void**)&pValue);
        if (bDetach != OpcUa_False)
        {
            *pValue = m_data[i];
        }
        else
        {
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(&m_data[i], pValue);
        }
    }
    if (bDetach != OpcUa_False)
    {
        OpcUa_Free(m_data);
        m_data = (OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_Null;
        m_noOfElements = 0;
    }
}

void TsnStreamFailureSystemIdentifiers::toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    UaVariant variant;
    toVariant(variant);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void TsnStreamFailureSystemIdentifiers::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    toVariant(dataValue.Value);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

void TsnStreamFailureSystemIdentifiers::toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    UaVariant variant;
    toVariant(variant, bDetach);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void TsnStreamFailureSystemIdentifiers::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    toVariant(dataValue.Value, bDetach);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

OpcUa_StatusCode TsnStreamFailureSystemIdentifiers::setTsnStreamFailureSystemIdentifiers(const UaVariant &variant)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    return setTsnStreamFailureSystemIdentifiers(*pVariant);
}

OpcUa_StatusCode TsnStreamFailureSystemIdentifiers::setTsnStreamFailureSystemIdentifiers(const OpcUa_Variant &variant)
{
    return setTsnStreamFailureSystemIdentifiers((OpcUa_Variant&)variant, OpcUa_False);
}

OpcUa_StatusCode TsnStreamFailureSystemIdentifiers::setTsnStreamFailureSystemIdentifiers(UaVariant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    return setTsnStreamFailureSystemIdentifiers(*pVariant, bDetach);
}

OpcUa_StatusCode TsnStreamFailureSystemIdentifiers::setTsnStreamFailureSystemIdentifiers(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    clear();

    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    if (variant.Datatype == OpcUaType_ExtensionObject &&
        variant.ArrayType == OpcUa_VariantArrayType_Array)
    {
        ret = OpcUa_Good;
        m_noOfElements = variant.Value.Array.Length >= 0 ? variant.Value.Array.Length : 0;
        if (m_noOfElements > 0 && variant.Value.Array.Value.ExtensionObjectArray != OpcUa_Null)
        {
            m_data = (OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUaClassBnm_TsnStreamFailureSystemIdentifier));

            OpcUa_UInt32 i = 0;
            for (i = 0; i < m_noOfElements; i++)
            {
                OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Initialize(&m_data[i]);

                OpcUaClassBnm_TsnStreamFailureSystemIdentifier *pValue = OPCUACLASSBNM_EXTENSIONOBJECT_GET_ENCODEABLE(TsnStreamFailureSystemIdentifier, &variant.Value.Array.Value.ExtensionObjectArray[i]);
                if (pValue)
                {
                    if (bDetach != OpcUa_False)
                    {
                        m_data[i] = *pValue;
                        OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Initialize(pValue);
                    }
                    else
                    {
                        OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(pValue, &m_data[i]);
                    }
                }
                else
                {
                    ret = OpcUa_BadTypeMismatch;
                    break;
                }
            }
            if (OpcUa_IsNotGood(ret))
            {
                for (OpcUa_UInt32 j = 0; j < i; j++)
                {
                    OpcUaClassBnm_TsnStreamFailureSystemIdentifier_Clear(&m_data[j]);
                }
                OpcUa_Free(m_data);
                m_data = (OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_Null;
                m_noOfElements = 0;
            }
        }
        else
        {
            m_noOfElements = 0;
        }
    }
    return ret;
}

OpcUa_StatusCode TsnStreamFailureSystemIdentifiers::setTsnStreamFailureSystemIdentifiers(OpcUa_Int32 length, OpcUaClassBnm_TsnStreamFailureSystemIdentifier* data)
{
    clear();

    if (length > 0 && data != OpcUa_Null)
    {
        m_noOfElements = length;
        m_data = (OpcUaClassBnm_TsnStreamFailureSystemIdentifier*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUaClassBnm_TsnStreamFailureSystemIdentifier));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            OpcUaClassBnm_TsnStreamFailureSystemIdentifier_CopyTo(&(data[i]), &(m_data[i]));
        }
    }
    return OpcUa_Good;
}

} // namespace OpcUaClassBnm

