/******************************************************************************
** moxaclassbased_snmpdatatype.cpp
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#include "moxaclassbased_snmpdatatype.h"

#include <opcua_datetime.h>

#include "uavariant.h"
#include "uadatavalue.h"
#include "uaextensionobject.h"
#include "uaatomic.h"

// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

/******************************************************************************
** Class SNMPDataTypePrivate
******************************************************************************/
class SNMPDataTypePrivate : private MoxaClassBased_SNMPDataType
{
    SNMPDataTypePrivate(const SNMPDataTypePrivate &other);
    SNMPDataTypePrivate& operator=(const SNMPDataTypePrivate&);
public:
    SNMPDataTypePrivate();
    explicit SNMPDataTypePrivate(bool bStatic);
    explicit SNMPDataTypePrivate(const MoxaClassBased_SNMPDataType &other);
    ~SNMPDataTypePrivate();

    int addRef();
    int release();
    inline int refCount() { return m_iRefCnt; }

private:
    int m_iRefCnt;
    friend class SNMPDataType;
};

/* construction */
SNMPDataTypePrivate::SNMPDataTypePrivate()
 : m_iRefCnt(0)
{
    MoxaClassBased_SNMPDataType_Initialize(this);
}

/*  Static initializer.
 *  This is used internaly to initialize the static shared_emtpy variable.
 *  RefCnt is set to 1 so it will never be deleted.
 */
SNMPDataTypePrivate::SNMPDataTypePrivate(bool)
 : m_iRefCnt(1)
{
    MoxaClassBased_SNMPDataType_Initialize(this);
}


/*  construction
 */
SNMPDataTypePrivate::SNMPDataTypePrivate(const MoxaClassBased_SNMPDataType &other) // [in] the other MoxaClassBased_SNMPDataType.
 : m_iRefCnt(0)
{
    MoxaClassBased_SNMPDataType_CopyTo(&other, this);
}

/* destruction */
SNMPDataTypePrivate::~SNMPDataTypePrivate()
{
    MoxaClassBased_SNMPDataType_Clear(this);
}

/*  Add a reference to a SNMPDataTypePrivate
 *  @return 0 if the object was deleted - otherwise a value bigger than 0.
 *  This method is not thread save regarding the return value. The returned counter is only reliable when it is 0.
 *  Other values are not reliable and should not be used for any logic.
 */
int SNMPDataTypePrivate::addRef()
{
    return ua_atomic_increment(&m_iRefCnt);
}

/*  Release a SNMPDataTypePrivate.
 *  @return the reference count.
 */
int SNMPDataTypePrivate::release()
{
    int currentCount = ua_atomic_decrement(&m_iRefCnt);
    if (currentCount == 0)
    {
        delete this;
    }
    return currentCount;
}

SNMPDataTypePrivate* shared_empty_SNMPDataType()
{
    static SNMPDataTypePrivate shared_static(true);
    return &shared_static;
}


/******************************************************************************
** Class SNMPDataType
******************************************************************************/

/** Constructs an instance of the class SNMPDataType with empty default values
*/
SNMPDataType::SNMPDataType()
{
    d_ptr = shared_empty_SNMPDataType();
    d_ptr->addRef();
}

/** Constructs an instance of the class SNMPDataType with values from another SNMPDataType object
 *  @param other the other UaSNMPDataType used to initialize the object
 */
SNMPDataType::SNMPDataType(const SNMPDataType &other)
{
    d_ptr = other.d_ptr;
    d_ptr->addRef();
}

/** Constructs an instance of the class SNMPDataType with values from another MoxaClassBased_SNMPDataType structure
 *  @param other the other MoxaClassBased_SNMPDataType used to initialize the object
 */
SNMPDataType::SNMPDataType(const MoxaClassBased_SNMPDataType &other)
{
    d_ptr = new SNMPDataTypePrivate(other);
    d_ptr->addRef();
}

/** Constructs an instance of the class SNMPDataType initialized with value from a UaExtensionObject
 *  @param extensionObject the extension object containing the SNMPDataType
 */
SNMPDataType::SNMPDataType(const UaExtensionObject &extensionObject)
{
    d_ptr = new SNMPDataTypePrivate();
    d_ptr->addRef();

    const OpcUa_ExtensionObject *pExtensionObject = (const OpcUa_ExtensionObject*)extensionObject;
    MoxaClassBased_SNMPDataType *pSNMPDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(SNMPDataType, pExtensionObject);

    if (pSNMPDataType)
    {
        MoxaClassBased_SNMPDataType_CopyTo(pSNMPDataType, d_ptr);
    }
}

/** Constructs an instance of the class SNMPDataType initialized with value from an OpcUa_ExtensionObject structure
 *  @param extensionObject the extension object containing the SNMPDataType
 */
SNMPDataType::SNMPDataType(const OpcUa_ExtensionObject &extensionObject)
{
    d_ptr = new SNMPDataTypePrivate();
    d_ptr->addRef();

    MoxaClassBased_SNMPDataType *pSNMPDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(SNMPDataType, &extensionObject);

    if (pSNMPDataType)
    {
        MoxaClassBased_SNMPDataType_CopyTo(pSNMPDataType, d_ptr);
    }
}

SNMPDataType::SNMPDataType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    d_ptr = new SNMPDataTypePrivate();
    d_ptr->addRef();

    const OpcUa_ExtensionObject *pExtensionObject = (const OpcUa_ExtensionObject*)extensionObject;
    MoxaClassBased_SNMPDataType *pSNMPDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(SNMPDataType, pExtensionObject);
    if (pSNMPDataType)
    {
        if (bDetach == OpcUa_False)
        {
            MoxaClassBased_SNMPDataType_CopyTo(pSNMPDataType, d_ptr);
        }
        else
        {
            (*(MoxaClassBased_SNMPDataType*)d_ptr) = *pSNMPDataType;
            MoxaClassBased_SNMPDataType_Initialize(pSNMPDataType);
            extensionObject.clear();
        }
    }
}

SNMPDataType::SNMPDataType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    d_ptr = new SNMPDataTypePrivate();
    d_ptr->addRef();

    MoxaClassBased_SNMPDataType *pSNMPDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(SNMPDataType, &extensionObject);

    if (pSNMPDataType)
    {
        if (bDetach == OpcUa_False)
        {
            MoxaClassBased_SNMPDataType_CopyTo(pSNMPDataType, d_ptr);
        }
        else
        {
            (*(MoxaClassBased_SNMPDataType*)d_ptr) = *pSNMPDataType;
            MoxaClassBased_SNMPDataType_Initialize(pSNMPDataType);
            OpcUa_ExtensionObject_Clear(&extensionObject);
        }
    }
}

/** Destroys the SNMPDataType object
*/
SNMPDataType::~SNMPDataType()
{
    MOXACLASSBASED_D(SNMPDataType);
    d->release();
}

/** Clear the data of the SNMPDataType.
*/
void SNMPDataType::clear()
{
    d_ptr->release();
    d_ptr = shared_empty_SNMPDataType();
    d_ptr->addRef();
}

/** Compare two SNMPDataType if they are similar.
 *  @param other the SNMPDataType to compare.
 *  @return true if similar, false if not.
 */
bool SNMPDataType::operator==(const SNMPDataType &other) const
{
    return (MoxaClassBased_SNMPDataType_Compare(d_ptr, other.d_ptr) == 0);
}

/** Returns true if the other SNMPDataType is not equal to this.
 *  @see operator==
 *  @param other the SNMPDataType to compare.
 *  @return true if other is not equal to this.
 */
bool SNMPDataType::operator!=(const SNMPDataType &other) const
{
    return !(operator==(other));
}

/** Assignment operator.
 *  @param other the SNMPDataType to assign.
 *  @return Assignment operator.
 */
SNMPDataType& SNMPDataType::operator=(const SNMPDataType &other)
{
    other.d_ptr->addRef();
    d_ptr->release();
    d_ptr = other.d_ptr;
    return *this;
}

/** Copy SNMPDataType data to a newly allocated MoxaClassBased_SNMPDataType.
 *  @return data to a newly allocated MoxaClassBased_SNMPDataType.
 */
MoxaClassBased_SNMPDataType* SNMPDataType::copy() const
{
    return clone(*d_ptr);
}

/** Copy SNMPDataType data to an existing MoxaClassBased_SNMPDataType structure.
 *  @param pDst the destination of this copy operation.
 */
void SNMPDataType::copyTo(MoxaClassBased_SNMPDataType *pDst) const
{
    if (pDst == OpcUa_Null) return;
    cloneTo(*d_ptr, *pDst);
}

/** Copy MoxaClassBased_SNMPDataType data to a newly allocated MoxaClassBased_SNMPDataType.
 *  @param source Source to clone.
 *  @return new copy.
 */
MoxaClassBased_SNMPDataType* SNMPDataType::clone(const MoxaClassBased_SNMPDataType& source)
{
    MoxaClassBased_SNMPDataType* pSNMPDataType = OpcUa_Null;
    MoxaClassBased_SNMPDataType_Copy(&source, &pSNMPDataType);
    return pSNMPDataType;
}

/** Copy MoxaClassBased_SNMPDataType data to an existing MoxaClassBased_SNMPDataType structure.
 *  @param source the source of the clone operation.
 *  @param copy the destination of the clone operation.
 */
void SNMPDataType::cloneTo(const MoxaClassBased_SNMPDataType& source, MoxaClassBased_SNMPDataType& copy)
{
    MoxaClassBased_SNMPDataType_CopyTo(&source, &copy);
}

/** Attaches the data of the parameter pValue.
 * Don't clear the data of pValue afterwards manually, because SNMPDataType is responsible for it now.
 */
void SNMPDataType::attach(const MoxaClassBased_SNMPDataType *pValue) //!< [in] Parameter to attach to.
{
    if (pValue == OpcUa_Null) return;
    if (d_ptr->refCount() == 1)
    {
        MoxaClassBased_SNMPDataType_Clear(d_ptr);
    }
    else
    {
        d_ptr->release();
        d_ptr = new SNMPDataTypePrivate();
        d_ptr->addRef();
    }
    // copy data value structure (no deep copy)
    OpcUa_MemCpy(d_ptr, sizeof(MoxaClassBased_SNMPDataType), (void*)pValue, sizeof(MoxaClassBased_SNMPDataType));
}

/** Detaches the internal SNMPDataType structure from this class.
 *  This way you take over the control of releasing the SNMPDataType data.
 *  If more than one references exist, the data is copied to pDst instead of being detached.
 *  @return If the functions succeeds pDst is returned, otherwise 0 is returned.
 */
MoxaClassBased_SNMPDataType* SNMPDataType::detach(MoxaClassBased_SNMPDataType* pDst) //!< [out] Pointer to MoxaClassBased_SNMPDataType structure that receives the SNMPDataType data.
{
    if (pDst == OpcUa_Null) return OpcUa_Null;
    if (d_ptr->refCount() == 1)
    {
        OpcUa_MemCpy(pDst, sizeof(MoxaClassBased_SNMPDataType), d_ptr, sizeof(MoxaClassBased_SNMPDataType));
        // clear internal data without releasing deeper memory
        MoxaClassBased_SNMPDataType_Initialize(d_ptr);
    }
    else
    {
        MoxaClassBased_SNMPDataType_CopyTo(d_ptr, pDst);
    }
    d_ptr->release();
    d_ptr = shared_empty_SNMPDataType();
    d_ptr->addRef();
    return pDst;
}

void SNMPDataType::toVariant(UaVariant &variant) const
{
    UaExtensionObject extensionObject;
    toExtensionObject(extensionObject);
    variant.setExtensionObject(extensionObject, OpcUa_True);
}

void SNMPDataType::toVariant(OpcUa_Variant &variant) const
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Scalar;
    variant.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(variant.Value.ExtensionObject);
    toExtensionObject(*variant.Value.ExtensionObject);
}

void SNMPDataType::toVariant(UaVariant &variant, OpcUa_Boolean bDetach)
{
    UaExtensionObject extensionObject;
    toExtensionObject(extensionObject, bDetach);
    variant.setExtensionObject(extensionObject, OpcUa_True);
}

void SNMPDataType::toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Scalar;
    variant.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(variant.Value.ExtensionObject);
    toExtensionObject(*variant.Value.ExtensionObject, bDetach);
}

void SNMPDataType::toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    UaVariant variant;
    toVariant(variant);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void SNMPDataType::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    OpcUa_Variant_Clear(&dataValue.Value);
    dataValue.Value.Datatype = OpcUaType_ExtensionObject;
    dataValue.Value.ArrayType = OpcUa_VariantArrayType_Scalar;
    dataValue.Value.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(dataValue.Value.Value.ExtensionObject);
    toExtensionObject(*dataValue.Value.Value.ExtensionObject);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

void SNMPDataType::toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    UaVariant variant;
    toVariant(variant, bDetach);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void SNMPDataType::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    OpcUa_Variant_Clear(&dataValue.Value);
    dataValue.Value.Datatype = OpcUaType_ExtensionObject;
    dataValue.Value.ArrayType = OpcUa_VariantArrayType_Scalar;
    dataValue.Value.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(dataValue.Value.Value.ExtensionObject);
    toExtensionObject(*dataValue.Value.Value.ExtensionObject, bDetach);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

void SNMPDataType::toExtensionObject(UaExtensionObject &extensionObject) const
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    toExtensionObject(*pExtensionObject);
}

void SNMPDataType::toExtensionObject(OpcUa_ExtensionObject &extensionObject) const
{
    OpcUa_ExtensionObject_Clear(&extensionObject);
    MoxaClassBased_SNMPDataType *pSNMPDataType = OpcUa_Null;
    if (OpcUa_IsGood(OpcUa_EncodeableObject_CreateExtension(&MoxaClassBased_SNMPDataType_EncodeableType,
                                                            &extensionObject,
                                                            (OpcUa_Void**)&pSNMPDataType)))
    {
        MoxaClassBased_SNMPDataType_CopyTo(d_ptr, pSNMPDataType);
    }
}

void SNMPDataType::toExtensionObject(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    toExtensionObject(*pExtensionObject, bDetach);
}

void SNMPDataType::toExtensionObject(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject_Clear(&extensionObject);
    MoxaClassBased_SNMPDataType *pSNMPDataType = OpcUa_Null;
    if (OpcUa_IsGood(OpcUa_EncodeableObject_CreateExtension(&MoxaClassBased_SNMPDataType_EncodeableType,
                                                            &extensionObject,
                                                            (OpcUa_Void**)&pSNMPDataType)))
    {
        MoxaClassBased_SNMPDataType_Initialize(pSNMPDataType);
        if (bDetach != OpcUa_False && d_ptr->refCount() == 1)
        {
            *pSNMPDataType = *d_ptr;
            // clear internal data without releasing deeper memory
            MoxaClassBased_SNMPDataType_Initialize(d_ptr);
        }
        else
        {
            MoxaClassBased_SNMPDataType_CopyTo(d_ptr, pSNMPDataType);
        }
        if (bDetach != OpcUa_False)
        {
            d_ptr->release();
            d_ptr = shared_empty_SNMPDataType();
            d_ptr->addRef();
        }
    }
}

OpcUa_StatusCode SNMPDataType::setSNMPDataType(const UaExtensionObject &extensionObject)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    return setSNMPDataType(*pExtensionObject);
}

OpcUa_StatusCode SNMPDataType::setSNMPDataType(const OpcUa_ExtensionObject &extensionObject)
{
    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    MoxaClassBased_SNMPDataType *pSNMPDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(SNMPDataType, &extensionObject);

    if (pSNMPDataType)
    {
        ret = OpcUa_Good;

        if (d_ptr->refCount() == 1)
        {
            MoxaClassBased_SNMPDataType_Clear(d_ptr);
        }
        else
        {
            d_ptr->release();
            d_ptr = new SNMPDataTypePrivate();
            d_ptr->addRef();
        }

        MoxaClassBased_SNMPDataType_CopyTo(pSNMPDataType, d_ptr);
    }
    return ret;
}

OpcUa_StatusCode SNMPDataType::setSNMPDataType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    return setSNMPDataType(*pExtensionObject, bDetach);
}

OpcUa_StatusCode SNMPDataType::setSNMPDataType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    MoxaClassBased_SNMPDataType *pSNMPDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(SNMPDataType, &extensionObject);

    if (pSNMPDataType != OpcUa_Null)
    {
        ret = OpcUa_Good;

        if (d_ptr->refCount() == 1)
        {
            MoxaClassBased_SNMPDataType_Clear(d_ptr);
        }
        else
        {
            d_ptr->release();
            d_ptr = new SNMPDataTypePrivate();
            d_ptr->addRef();
        }

        if (bDetach == OpcUa_False)
        {
            MoxaClassBased_SNMPDataType_CopyTo(pSNMPDataType, d_ptr);
        }
        else
        {
            (*(MoxaClassBased_SNMPDataType*)d_ptr) = *pSNMPDataType;
            MoxaClassBased_SNMPDataType_Initialize(pSNMPDataType);
            OpcUa_ExtensionObject_Clear(&extensionObject);
        }
    }
    return ret;
}


bool SNMPDataType::isReadCommunitySet() const
{
    return (d_ptr->EncodingMask & MoxaClassBased_SNMPDataType_OptionalFields_ReadCommunity) != 0;
}

UaString SNMPDataType::getReadCommunity(bool *ok) const
{
    if (ok)
    {
        *ok = isReadCommunitySet();
    }
    return d_ptr->ReadCommunity;
}

bool SNMPDataType::isWriteCommunitySet() const
{
    return (d_ptr->EncodingMask & MoxaClassBased_SNMPDataType_OptionalFields_WriteCommunity) != 0;
}

UaString SNMPDataType::getWriteCommunity(bool *ok) const
{
    if (ok)
    {
        *ok = isWriteCommunitySet();
    }
    return d_ptr->WriteCommunity;
}

bool SNMPDataType::isPortSet() const
{
    return (d_ptr->EncodingMask & MoxaClassBased_SNMPDataType_OptionalFields_Port) != 0;
}

OpcUa_UInt16 SNMPDataType::getPort(bool *ok) const
{
    if (ok)
    {
        *ok = isPortSet();
    }
    return d_ptr->Port;
}

bool SNMPDataType::isVersionSet() const
{
    return (d_ptr->EncodingMask & MoxaClassBased_SNMPDataType_OptionalFields_Version) != 0;
}

MoxaClassBased::SNMPVersion SNMPDataType::getVersion(bool *ok) const
{
    if (ok)
    {
        *ok = isVersionSet();
    }
    return d_ptr->Version;
}

void SNMPDataType::unsetReadCommunity()
{
    if (d_ptr->refCount() > 1)
    {
        SNMPDataTypePrivate *pNew = new SNMPDataTypePrivate((const MoxaClassBased_SNMPDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }
    OpcUa_String_Clear(&d_ptr->ReadCommunity);
    d_ptr->EncodingMask &= (~MoxaClassBased_SNMPDataType_OptionalFields_ReadCommunity);
}

void SNMPDataType::setReadCommunity(const UaString& ReadCommunity)
{
    if (d_ptr->refCount() > 1)
    {
        SNMPDataTypePrivate *pNew = new SNMPDataTypePrivate((const MoxaClassBased_SNMPDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }

    d_ptr->EncodingMask |= MoxaClassBased_SNMPDataType_OptionalFields_ReadCommunity;

    OpcUa_String_Clear(&d_ptr->ReadCommunity);
    ReadCommunity.copyTo(&d_ptr->ReadCommunity);
}

void SNMPDataType::unsetWriteCommunity()
{
    if (d_ptr->refCount() > 1)
    {
        SNMPDataTypePrivate *pNew = new SNMPDataTypePrivate((const MoxaClassBased_SNMPDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }
    OpcUa_String_Clear(&d_ptr->WriteCommunity);
    d_ptr->EncodingMask &= (~MoxaClassBased_SNMPDataType_OptionalFields_WriteCommunity);
}

void SNMPDataType::setWriteCommunity(const UaString& WriteCommunity)
{
    if (d_ptr->refCount() > 1)
    {
        SNMPDataTypePrivate *pNew = new SNMPDataTypePrivate((const MoxaClassBased_SNMPDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }

    d_ptr->EncodingMask |= MoxaClassBased_SNMPDataType_OptionalFields_WriteCommunity;

    OpcUa_String_Clear(&d_ptr->WriteCommunity);
    WriteCommunity.copyTo(&d_ptr->WriteCommunity);
}

void SNMPDataType::unsetPort()
{
    if (d_ptr->refCount() > 1)
    {
        SNMPDataTypePrivate *pNew = new SNMPDataTypePrivate((const MoxaClassBased_SNMPDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }
    d_ptr->Port = 0;
    d_ptr->EncodingMask &= (~MoxaClassBased_SNMPDataType_OptionalFields_Port);
}

void SNMPDataType::setPort(OpcUa_UInt16 Port)
{
    if (d_ptr->refCount() > 1)
    {
        SNMPDataTypePrivate *pNew = new SNMPDataTypePrivate((const MoxaClassBased_SNMPDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }

    d_ptr->EncodingMask |= MoxaClassBased_SNMPDataType_OptionalFields_Port;

    d_ptr->Port = Port;
}

void SNMPDataType::unsetVersion()
{
    if (d_ptr->refCount() > 1)
    {
        SNMPDataTypePrivate *pNew = new SNMPDataTypePrivate((const MoxaClassBased_SNMPDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }
    d_ptr->Version = (MoxaClassBased::SNMPVersion)0;
    d_ptr->EncodingMask &= (~MoxaClassBased_SNMPDataType_OptionalFields_Version);
}

void SNMPDataType::setVersion(MoxaClassBased::SNMPVersion Version)
{
    if (d_ptr->refCount() > 1)
    {
        SNMPDataTypePrivate *pNew = new SNMPDataTypePrivate((const MoxaClassBased_SNMPDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }

    d_ptr->EncodingMask |= MoxaClassBased_SNMPDataType_OptionalFields_Version;

    d_ptr->Version = Version;
}


/******************************************************************************
** Class SNMPDataTypes
******************************************************************************/
SNMPDataTypes SNMPDataTypes::empty;

SNMPDataTypes::SNMPDataTypes()
: m_noOfElements(0),
  m_data((MoxaClassBased_SNMPDataType*)OpcUa_Null)
{
}

SNMPDataTypes::SNMPDataTypes(const SNMPDataTypes &other)
: m_noOfElements(0),
  m_data((MoxaClassBased_SNMPDataType*)OpcUa_Null)
{
    operator=(other);
}

SNMPDataTypes::SNMPDataTypes(OpcUa_Int32 length, MoxaClassBased_SNMPDataType* data)
: m_noOfElements(0),
  m_data((MoxaClassBased_SNMPDataType*)OpcUa_Null)
{
    if (length > 0 && data != OpcUa_Null)
    {
        m_noOfElements = length;
        m_data = (MoxaClassBased_SNMPDataType*)OpcUa_Alloc(m_noOfElements * sizeof(MoxaClassBased_SNMPDataType));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            MoxaClassBased_SNMPDataType_CopyTo(&(data[i]), &(m_data[i]));
        }
    }
}

SNMPDataTypes::~SNMPDataTypes()
{
    clear();
}

SNMPDataTypes& SNMPDataTypes::operator=(const SNMPDataTypes &other)
{
    if (this == &other) {return *this;}

    clear();
    if (other.m_noOfElements > 0)
    {
        m_noOfElements = other.m_noOfElements;
        m_data = (MoxaClassBased_SNMPDataType*)OpcUa_Alloc(m_noOfElements * sizeof(MoxaClassBased_SNMPDataType));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            MoxaClassBased_SNMPDataType_CopyTo(&(other.m_data[i]), &(m_data[i]));
        }
    }
    return *this;
}

/** Returns the MoxaClassBased_SNMPDataType at index position index as a modifiable reference.
 *
 *  index must be valid index position in the array.
 */
MoxaClassBased_SNMPDataType& SNMPDataTypes::operator[](OpcUa_UInt32 index)
{
    assert(index<m_noOfElements);
    return m_data[index];
}

/** Returns the MoxaClassBased_SNMPDataType at index position index.
 *
 *  index must be valid index position in the array.
 */
const MoxaClassBased_SNMPDataType& SNMPDataTypes::operator[](OpcUa_UInt32 index) const
{
    assert(index<m_noOfElements);
    return m_data[index];
}

/** Attaches the raw data.
 *
 *  Clears the array and takes the ownership of data.
 *  Don't clear the data afterwards manually, because SNMPDataTypes is responsible for it now.
 */
void SNMPDataTypes::attach(OpcUa_UInt32 length, MoxaClassBased_SNMPDataType* data)
{
    clear();
    m_data = data;
    m_noOfElements = length;
}

/** Attaches the raw data.
 *
 *  Clears the array and takes the ownership of data.
 *  Don't clear the data afterwards manually, because SNMPDataTypes is responsible for it now.
 */
void SNMPDataTypes::attach(OpcUa_Int32 length, MoxaClassBased_SNMPDataType* data)
{
    clear();
    if (length >= 0)
    {
        m_data = data;
        m_noOfElements = length;
    }
}

bool SNMPDataTypes::operator==(const SNMPDataTypes &other) const
{
    if (m_noOfElements != other.m_noOfElements) {return false;}

    if (m_noOfElements > 0)
    {
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            if (MoxaClassBased_SNMPDataType_Compare(&(m_data[i]), &(other.m_data[i])) != OPCUA_EQUAL) {return false;};
        }
    }
    return true;
}

bool SNMPDataTypes::operator!=(const SNMPDataTypes &other) const
{
    return !(operator==(other));
}

/** Detaches the raw data from this class.
 *
 *  The caller takes ownership of the raw data and is responsible for deleting it
 *  by calling OpcUa_Free.
 *  @return The raw data.
 */
MoxaClassBased_SNMPDataType* SNMPDataTypes::detach()
{
    MoxaClassBased_SNMPDataType* pRet = m_data;
    m_noOfElements = 0;
    m_data = (MoxaClassBased_SNMPDataType*)OpcUa_Null;
    return pRet;
}

void SNMPDataTypes::create(OpcUa_UInt32 length)
{
    clear();
    if (length > 0)
    {
        m_data = (MoxaClassBased_SNMPDataType*)OpcUa_Alloc(length * sizeof(MoxaClassBased_SNMPDataType));
        for (OpcUa_UInt32 i = 0; i < length; i++)
        {
            MoxaClassBased_SNMPDataType_Initialize(&(m_data[i]));
        }
        m_noOfElements = length;
    }
}

void SNMPDataTypes::resize(OpcUa_UInt32 length)
{
    if (length < m_noOfElements)
    {
        if (length != 0)
        {
            for (OpcUa_UInt32 i = length; i < m_noOfElements; i++)
            {
                MoxaClassBased_SNMPDataType_Clear(&(m_data[i]));
            }

            MoxaClassBased_SNMPDataType* newData = (MoxaClassBased_SNMPDataType*)OpcUa_ReAlloc(m_data, length * sizeof(MoxaClassBased_SNMPDataType));
            if (newData)
            {
                m_data = newData;
                m_noOfElements = length;
            }
        }
        else
        {
            clear();
        }
    }
    else if (length > m_noOfElements)
    {
        MoxaClassBased_SNMPDataType* newData = (MoxaClassBased_SNMPDataType*)OpcUa_ReAlloc(m_data, length * sizeof(MoxaClassBased_SNMPDataType));
        if (newData)
        {
            for (OpcUa_UInt32 i = m_noOfElements; i < length; i++)
            {
                MoxaClassBased_SNMPDataType_Initialize(&(newData[i]));
            }
            m_data = newData;
            m_noOfElements = length;
        }
    }
}

void SNMPDataTypes::clear()
{
    if (m_data)
    {
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            MoxaClassBased_SNMPDataType_Clear(&(m_data[i]));
        }
        OpcUa_Free(m_data);
        m_data = (MoxaClassBased_SNMPDataType*)OpcUa_Null;
    }
    m_noOfElements = 0;
}

void SNMPDataTypes::toVariant(UaVariant &variant) const
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    toVariant(*pVariant);
}

void SNMPDataTypes::toVariant(OpcUa_Variant &variant) const
{
    OpcUa_Variant_Clear(&variant);

    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Array;
    variant.Value.Array.Length = m_noOfElements;
    variant.Value.Array.Value.ExtensionObjectArray = (OpcUa_ExtensionObject*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUa_ExtensionObject));
    for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
    {
        MoxaClassBased_SNMPDataType *pValue = OpcUa_Null;
        OpcUa_ExtensionObject_Initialize(&variant.Value.Array.Value.ExtensionObjectArray[i]);
        OpcUa_EncodeableObject_CreateExtension(&MoxaClassBased_SNMPDataType_EncodeableType,
                                               &variant.Value.Array.Value.ExtensionObjectArray[i],
                                               (OpcUa_Void**)&pValue);
        MoxaClassBased_SNMPDataType_CopyTo(&m_data[i], pValue);
    }
}

void SNMPDataTypes::toVariant(UaVariant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    toVariant(*pVariant, bDetach);
}

void SNMPDataTypes::toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Array;
    variant.Value.Array.Length = m_noOfElements;
    variant.Value.Array.Value.ExtensionObjectArray = (OpcUa_ExtensionObject*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUa_ExtensionObject));
    for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
    {
        MoxaClassBased_SNMPDataType *pValue = OpcUa_Null;
        OpcUa_ExtensionObject_Initialize(&variant.Value.Array.Value.ExtensionObjectArray[i]);
        OpcUa_EncodeableObject_CreateExtension(&MoxaClassBased_SNMPDataType_EncodeableType,
                                               &variant.Value.Array.Value.ExtensionObjectArray[i],
                                               (OpcUa_Void**)&pValue);
        if (bDetach != OpcUa_False)
        {
            *pValue = m_data[i];
        }
        else
        {
            MoxaClassBased_SNMPDataType_CopyTo(&m_data[i], pValue);
        }
    }
    if (bDetach != OpcUa_False)
    {
        OpcUa_Free(m_data);
        m_data = (MoxaClassBased_SNMPDataType*)OpcUa_Null;
        m_noOfElements = 0;
    }
}

void SNMPDataTypes::toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    UaVariant variant;
    toVariant(variant);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void SNMPDataTypes::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    toVariant(dataValue.Value);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

void SNMPDataTypes::toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    UaVariant variant;
    toVariant(variant, bDetach);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void SNMPDataTypes::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    toVariant(dataValue.Value, bDetach);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

OpcUa_StatusCode SNMPDataTypes::setSNMPDataTypes(const UaVariant &variant)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    return setSNMPDataTypes(*pVariant);
}

OpcUa_StatusCode SNMPDataTypes::setSNMPDataTypes(const OpcUa_Variant &variant)
{
    return setSNMPDataTypes((OpcUa_Variant&)variant, OpcUa_False);
}

OpcUa_StatusCode SNMPDataTypes::setSNMPDataTypes(UaVariant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    return setSNMPDataTypes(*pVariant, bDetach);
}

OpcUa_StatusCode SNMPDataTypes::setSNMPDataTypes(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    clear();

    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    if (variant.Datatype == OpcUaType_ExtensionObject &&
        variant.ArrayType == OpcUa_VariantArrayType_Array)
    {
        ret = OpcUa_Good;
        m_noOfElements = variant.Value.Array.Length >= 0 ? variant.Value.Array.Length : 0;
        if (m_noOfElements > 0 && variant.Value.Array.Value.ExtensionObjectArray != OpcUa_Null)
        {
            m_data = (MoxaClassBased_SNMPDataType*)OpcUa_Alloc(m_noOfElements * sizeof(MoxaClassBased_SNMPDataType));

            OpcUa_UInt32 i = 0;
            for (i = 0; i < m_noOfElements; i++)
            {
                MoxaClassBased_SNMPDataType_Initialize(&m_data[i]);

                MoxaClassBased_SNMPDataType *pValue = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(SNMPDataType, &variant.Value.Array.Value.ExtensionObjectArray[i]);
                if (pValue)
                {
                    if (bDetach != OpcUa_False)
                    {
                        m_data[i] = *pValue;
                        MoxaClassBased_SNMPDataType_Initialize(pValue);
                    }
                    else
                    {
                        MoxaClassBased_SNMPDataType_CopyTo(pValue, &m_data[i]);
                    }
                }
                else
                {
                    ret = OpcUa_BadTypeMismatch;
                    break;
                }
            }
            if (OpcUa_IsNotGood(ret))
            {
                for (OpcUa_UInt32 j = 0; j < i; j++)
                {
                    MoxaClassBased_SNMPDataType_Clear(&m_data[j]);
                }
                OpcUa_Free(m_data);
                m_data = (MoxaClassBased_SNMPDataType*)OpcUa_Null;
                m_noOfElements = 0;
            }
        }
        else
        {
            m_noOfElements = 0;
        }
    }
    return ret;
}

OpcUa_StatusCode SNMPDataTypes::setSNMPDataTypes(OpcUa_Int32 length, MoxaClassBased_SNMPDataType* data)
{
    clear();

    if (length > 0 && data != OpcUa_Null)
    {
        m_noOfElements = length;
        m_data = (MoxaClassBased_SNMPDataType*)OpcUa_Alloc(m_noOfElements * sizeof(MoxaClassBased_SNMPDataType));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            MoxaClassBased_SNMPDataType_CopyTo(&(data[i]), &(m_data[i]));
        }
    }
    return OpcUa_Good;
}

} // namespace MoxaClassBased

