/******************************************************************************
** moxaclassbased_firmwareupgradestatemachinetypebase.cpp
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#include "moxaclassbased_firmwareupgradestatemachinetypebase.h"
#include "moxaclassbased_firmwareupgradestatemachinetype.h"
#include "uagenericnodes.h"
#include "nodemanagerroot.h"
#include "methodhandleuanode.h"
#include "moxaclassbased_nodemanagermoxaclassbasedns.h"

#include "instancefactory.h"
#include "opcua_extensionobject.h"
#include "opcua_finitestatevariabletype.h"
#include "opcua_finitetransitionvariabletype.h"
// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

bool FirmwareUpgradeStateMachineTypeBase::s_typeNodesCreated = false;
OpcUa::BaseMethod* FirmwareUpgradeStateMachineTypeBase::s_pStartMethod = NULL;
OpcUa::BaseMethod* FirmwareUpgradeStateMachineTypeBase::s_pStopMethod = NULL;

/** Constructs an FirmwareUpgradeStateMachineType object using an instance declaration node as base
*/
FirmwareUpgradeStateMachineTypeBase::FirmwareUpgradeStateMachineTypeBase(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: MoxaClassBased::ProgramStateMachineType(nodeId, pInstanceDeclarationObject, pNodeConfig, pSharedMutex)
{
    initialize();
}

/** Constructs an FirmwareUpgradeStateMachineType object
*/
FirmwareUpgradeStateMachineTypeBase::FirmwareUpgradeStateMachineTypeBase(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: MoxaClassBased::ProgramStateMachineType(nodeId, name, browseNameNameSpaceIndex, pNodeConfig, pSharedMutex)
{
    initialize();
}

/**  Constructs an instance of the class FirmwareUpgradeStateMachineTypeBase with all components
*/
FirmwareUpgradeStateMachineTypeBase::FirmwareUpgradeStateMachineTypeBase(
    UaBase::Object*    pBaseNode,    //!< [in] The "tree" of nodes that specifies the attributes of the instance and its children
    XmlUaNodeFactoryManager* pFactory, //!< [in] The factory to create the children
    NodeManagerConfig* pNodeConfig,  //!< [in] Interface pointer to the NodeManagerConfig interface used to add and delete node and references in the address space
    UaMutexRefCounted* pSharedMutex) //!< [in] Shared mutex object used to synchronize access to the variable. Can be NULL if no shared mutex is provided
: MoxaClassBased::ProgramStateMachineType(pBaseNode, pFactory, pNodeConfig, pSharedMutex)
{
    UaStatus      addStatus;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }

    m_pStartMethod = NULL;
    m_pStopMethod = NULL;

    std::list<UaBase::BaseNode*> lstReferencedNodes = pBaseNode->hierarchicallyReferencedNodes();
    for (std::list<UaBase::BaseNode*>::const_iterator it = lstReferencedNodes.begin(); it != lstReferencedNodes.end(); it++)
    {
        UaBase::BaseNode *pChild = *it;
        if (s_pStartMethod && pChild->browseName() == s_pStartMethod->browseName())
        {
            if (!m_pStartMethod)
            {
                m_pStartMethod = (OpcUa::BaseMethod*) pFactory->createMethod((UaBase::Method*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pStartMethod, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Method*)pChild)->modellingRuleId().isNull())
                {
                    m_pStartMethod->setModellingRuleId(((UaBase::Method*)pChild)->modellingRuleId());
                }
            }
        }
        else if (s_pStopMethod && pChild->browseName() == s_pStopMethod->browseName())
        {
            if (!m_pStopMethod)
            {
                m_pStopMethod = (OpcUa::BaseMethod*) pFactory->createMethod((UaBase::Method*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pStopMethod, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Method*)pChild)->modellingRuleId().isNull())
                {
                    m_pStopMethod->setModellingRuleId(((UaBase::Method*)pChild)->modellingRuleId());
                }
            }
        }
    }
    UA_ASSERT(m_pStartMethod);
    UA_ASSERT(m_pStopMethod);
}

/** Initialize the object with all member nodes
*/
void FirmwareUpgradeStateMachineTypeBase::initialize()
{
    OpcUa_Int16 nsIdx = m_pNodeConfig->getNameSpaceIndex();
    UaStatus      addStatus;
    UaUInt32Array arrayDimensions;
    UaPropertyMethodArgument* pPropertyArg = NULL;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }
    m_pStartMethod = NULL;
    m_pStopMethod = NULL;
    // Method Start
    m_pStartMethod = new OpcUa::BaseMethod(this, s_pStartMethod, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pStartMethod, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // ------------------------------------------------------------------------
    // Add InputArguments
    // Create property
    pPropertyArg = new UaPropertyMethodArgument(
        UaNodeId(UaString("%1.Start.InputArguments").arg(nodeId().toString()), nsIdx), // NodeId of the property
        OpcUa_AccessLevels_CurrentRead,         // Access level of the property
        1,                                      // Number of arguments
        UaPropertyMethodArgument::INARGUMENTS); // IN arguments
    // Argument FilePath
    pPropertyArg->setArgument(
        0,                      // Index of the argument
        "FilePath",             // Name of the argument
        UaNodeId(OpcUaId_String),// Data type of the argument
        -1,                     // ValueRank of the argument
        arrayDimensions,
        UaLocalizedText("", "")); // Description
    // Add property to method
    addStatus = m_pNodeConfig->addNodeAndReference(m_pStartMethod, pPropertyArg, OpcUaId_HasProperty);
    UA_ASSERT(addStatus.isGood());

    // Method Stop
    m_pStopMethod = new OpcUa::BaseMethod(this, s_pStopMethod, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pStopMethod, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

}

/** Destruction
*/
FirmwareUpgradeStateMachineTypeBase::~FirmwareUpgradeStateMachineTypeBase()
{
}

/** Create the related type nodes
*/
void FirmwareUpgradeStateMachineTypeBase::createTypes()
{
    if ( s_typeNodesCreated == false )
    {
        s_typeNodesCreated = true;

        // Check if supertype is already created
        MoxaClassBased::ProgramStateMachineType::createTypes();

        UaStatus      addStatus;
        UaVariant     defaultValue;
        UaUInt32Array arrayDimensions;
        UaPropertyMethodArgument* pPropertyArg = NULL;
        NodeManagerRoot* pNodeManagerRoot = NodeManagerRoot::CreateRootNodeManager();
        OpcUa_Int16 nsTypeIdx = NodeManagerMoxaClassBasedNS::getTypeNamespace();
        OpcUa_Int16 nsSuperTypeIdx = MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace();
        NodeManagerConfig* pTypeNodeConfig = pNodeManagerRoot->getNodeManagerByNamespace(nsTypeIdx)->getNodeManagerConfig();

        OpcUa::GenericObjectType* pObjectType;
        pObjectType = new OpcUa::GenericObjectType(
            UaNodeId(MoxaClassBasedId_FirmwareUpgradeStateMachineType, nsTypeIdx),
            UaQualifiedName("FirmwareUpgradeStateMachineType", nsTypeIdx),
            UaLocalizedText("", "FirmwareUpgradeStateMachineType"),
            UaLocalizedText("", ""),
            OpcUa_False,
            &FirmwareUpgradeStateMachineType::clearStaticMembers);
        addStatus = pTypeNodeConfig->addNodeAndReference(UaNodeId(MoxaClassBasedId_ProgramStateMachineType, nsSuperTypeIdx), pObjectType, OpcUaId_HasSubtype);
        UA_ASSERT(addStatus.isGood());
        // ------------------------------------------------------------------------
        // Method Start
        // ------------------------------------------------------------------------
        s_pStartMethod = new OpcUa::BaseMethod(UaNodeId(MoxaClassBasedId_FirmwareUpgradeStateMachineType_Start, nsTypeIdx), "Start", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace());
        s_pStartMethod->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pStartMethod, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());
        // ------------------------------------------------------------------------
        // Add InputArguments
        // Create property
        pPropertyArg = new UaPropertyMethodArgument(
            UaNodeId(MoxaClassBasedId_FirmwareUpgradeStateMachineType_Start_InputArguments, nsTypeIdx),       // NodeId of the property
            OpcUa_AccessLevels_CurrentRead,         // Access level of the property
            1,                                      // Number of arguments
            UaPropertyMethodArgument::INARGUMENTS); // IN arguments
        // Argument FilePath
        pPropertyArg->setArgument(
            0,                      // Index of the argument
            "FilePath",             // Name of the argument
            UaNodeId(OpcUaId_String),// Data type of the argument
            -1,                     // Array rank of the argument
            arrayDimensions,
            UaLocalizedText("", "")); // Description
        // Set the ModellingRule to InputArguments
        pPropertyArg->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        // Add property to method
        pTypeNodeConfig->addNodeAndReference(s_pStartMethod, pPropertyArg, OpcUaId_HasProperty);

        // ------------------------------------------------------------------------
        // Method Stop
        // ------------------------------------------------------------------------
        s_pStopMethod = new OpcUa::BaseMethod(UaNodeId(MoxaClassBasedId_FirmwareUpgradeStateMachineType_Stop, nsTypeIdx), "Stop", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace());
        s_pStopMethod->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pStopMethod, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());


    }
}

/** Clear the static members of the class
*/
void FirmwareUpgradeStateMachineTypeBase::clearStaticMembers()
{
    s_typeNodesCreated = false;

    s_pStartMethod = NULL;
    s_pStopMethod = NULL;
}

/** Returns the type definition NodeId for the FirmwareUpgradeStateMachineType
*/
UaNodeId FirmwareUpgradeStateMachineTypeBase::typeDefinitionId() const
{
    UaNodeId ret(MoxaClassBasedId_FirmwareUpgradeStateMachineType, NodeManagerMoxaClassBasedNS::getTypeNamespace());
    return ret;
}

/** Implementation of the MethodManager interface method beginCall
*/
UaStatus FirmwareUpgradeStateMachineTypeBase::beginCall(
    MethodManagerCallback* pCallback,
    const ServiceContext&  serviceContext,
    OpcUa_UInt32           callbackHandle,
    MethodHandle*          pMethodHandle,
    const UaVariantArray&  inputArguments)
{
    UaStatus            ret;

    OpcUa::MethodCallJob* pCallJob = new OpcUa::MethodCallJob;
    pCallJob->initialize(this, pCallback, serviceContext, callbackHandle, pMethodHandle, inputArguments);
    ret = NodeManagerRoot::CreateRootNodeManager()->pServerManager()->getThreadPool()->addJob(pCallJob);
    if ( ret.isBad() )
    {
        delete pCallJob;
    }

    return ret;
}

/** Synchronous version of the MethodManager method call executed in a worker thread
*/
UaStatus FirmwareUpgradeStateMachineTypeBase::call(
    const ServiceContext&  serviceContext,
    MethodHandle*          pMethodHandle,
    const UaVariantArray&  inputArguments,
    UaVariantArray&        outputArguments,
    UaStatusCodeArray&     inputArgumentResults,
    UaDiagnosticInfos&     inputArgumentDiag)
{
    UaStatus            ret;
    MethodHandleUaNode* pMethodHandleUaNode = (MethodHandleUaNode*)pMethodHandle;
    UaMethod*           pMethod             = NULL;

    if (pMethodHandleUaNode)
    {
        pMethod = pMethodHandleUaNode->pUaMethod();

        if (pMethod)
        {
            if ( ( (m_pStartMethod != NULL) && (pMethod->nodeId() == m_pStartMethod->nodeId()) )
                 || ( (s_pStartMethod != NULL) && (pMethod->nodeId() == s_pStartMethod->nodeId()) ) )
            {
                if ( inputArguments.length() < 1 )
                {
                    ret = OpcUa_BadArgumentsMissing;
                }
                else if ( inputArguments.length() > 1 )
                {
                    ret = OpcUa_BadTooManyArguments;
                }
                else
                {
                    inputArgumentResults.create(1);

                    UaVariant value;
                    UaStatus tmpRet;

                    UaString FilePath;
                    value = inputArguments[ 0 ];
                    FilePath = value.toString();
                    inputArgumentResults[ 0 ] = tmpRet.statusCode();
                    if (tmpRet.isNotGood()) {ret = tmpRet;}

                    if ( ret.isGood() )
                    {
                        ret = this->Start(serviceContext, FilePath);
                    }
                }

            }
            else if ( ( (m_pStopMethod != NULL) && (pMethod->nodeId() == m_pStopMethod->nodeId()) )
                      || ( (s_pStopMethod != NULL) && (pMethod->nodeId() == s_pStopMethod->nodeId()) ) )
            {
                if ( inputArguments.length() > 0 )
                {
                    ret = OpcUa_BadTooManyArguments;
                }
                else
                {
                    ret = this->Stop(serviceContext);
                }

            }
            else
            {
                return ProgramStateMachineType::call(serviceContext, pMethodHandle, inputArguments, outputArguments, inputArgumentResults, inputArgumentDiag);
            }
        }
        else
        {
            assert(false);
            ret = OpcUa_BadInvalidArgument;
        }
    }
    else
    {
        assert(false);
        ret = OpcUa_BadInvalidArgument;
    }

    return ret;
}

/** Returns the Start node.
  */
OpcUa::BaseMethod* FirmwareUpgradeStateMachineTypeBase::getStart()
{
    return m_pStartMethod;
}

/** Returns the Start node.
  */
const OpcUa::BaseMethod* FirmwareUpgradeStateMachineTypeBase::getStart() const
{
    return m_pStartMethod;
}
/** Returns the Stop node.
  */
OpcUa::BaseMethod* FirmwareUpgradeStateMachineTypeBase::getStop()
{
    return m_pStopMethod;
}

/** Returns the Stop node.
  */
const OpcUa::BaseMethod* FirmwareUpgradeStateMachineTypeBase::getStop() const
{
    return m_pStopMethod;
}

/** Uses the NodeAccessInfo of pOther and its children. */
void FirmwareUpgradeStateMachineTypeBase::useAccessInfoFromInstance(FirmwareUpgradeStateMachineTypeBase *pOther)
{
    MoxaClassBased::ProgramStateMachineType::useAccessInfoFromInstance(pOther);

    // children
    m_pStartMethod->useAccessInfoFrom(pOther->m_pStartMethod);
    m_pStopMethod->useAccessInfoFrom(pOther->m_pStopMethod);
}

/** Set the NodeAccessInfo for this node and all of its children. */
void FirmwareUpgradeStateMachineTypeBase::setAccessInfoWithChildren(NodeAccessInfo* pNodeAccessInfo)
{
    MoxaClassBased::ProgramStateMachineType::setAccessInfoWithChildren(pNodeAccessInfo);

    // children
    m_pStartMethod->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pStopMethod->setAccessInfoWithChildren(pNodeAccessInfo);
}


} // End namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/


