/******************************************************************************
** moxaclassbased_deviceinformationtypebase.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#ifndef __MOXACLASSBASED_DEVICEINFORMATIONTYPEBASE_H__
#define __MOXACLASSBASED_DEVICEINFORMATIONTYPEBASE_H__

#include "opcua_baseobjecttype.h"
#include "moxaclassbased_datatypes.h"
#include "basenodes.h"
#include "moxaclassbased_identifiers.h"
#include "moxaclassbased_instancefactory_moxaclassbasedns.h"
#include "opcua_basedatavariabletype.h"

// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {


/** Generated base class for a DeviceInformationType.
 *
 *  This class contains the generated base code for the object type DeviceInformationType
 *  representing an OPC UA ObjectType. This class is used to create the object type and to
 *  create and represent instances of the object type in the server address space.
 *
 *  **Variable members of the DeviceInformationType:**
 *
 *  Browse Name     | DataType | TypeDefinition       | Modelling Rule | See Also
 *  ----------------|----------|----------------------|----------------|-------------------------------------------------
 *  FirmwareVersion | String   | BaseDataVariableType | Mandatory      | \ref getFirmwareVersion, \ref setFirmwareVersion
 *
 */
class MoxaClassBased_EXPORT DeviceInformationTypeBase:
    public OpcUa::BaseObjectType
{
    UA_DISABLE_COPY(DeviceInformationTypeBase);
protected:
    virtual ~DeviceInformationTypeBase();
public:
    // construction / destruction
    DeviceInformationTypeBase(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    DeviceInformationTypeBase(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    DeviceInformationTypeBase(
        UaBase::Object*    pBaseNode,
        XmlUaNodeFactoryManager*   pFactory,
        NodeManagerConfig* pNodeConfig,
        UaMutexRefCounted* pSharedMutex = NULL);
    static void createTypes();
    static void clearStaticMembers();

    virtual UaNodeId       typeDefinitionId() const;


    virtual void setFirmwareVersion(const UaString& FirmwareVersion);
    virtual UaString getFirmwareVersion() const;

    virtual OpcUa::BaseDataVariableType* getFirmwareVersionNode();
    virtual const OpcUa::BaseDataVariableType* getFirmwareVersionNode() const;

    // NodeAccessInfo management
    void useAccessInfoFromInstance(DeviceInformationTypeBase *pInstance);
    virtual void setAccessInfoWithChildren(NodeAccessInfo* pNodeAccessInfo);

protected:
    // Variable nodes
    // Variable FirmwareVersion
    static OpcUa::BaseDataVariableType*  s_pFirmwareVersion;
    OpcUa::BaseDataVariableType*  m_pFirmwareVersion;



private:
    void initialize();

private:
    static bool s_typeNodesCreated;
};

} // End namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/

#endif // #ifndef __MOXACLASSBASEDDEVICEINFORMATIONTYPEBASE_H__


