/******************************************************************************
** moxaclassbased_ieeedot1as2011datatype.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/


#ifndef __MOXACLASSBASED_IEEEDOT1AS2011DATATYPE_H__
#define __MOXACLASSBASED_IEEEDOT1AS2011DATATYPE_H__

#include <opcua_proxystub.h>

#include "uabase.h"
#include "uaarraytemplates.h"
#include "moxaclassbased_identifiers.h"
#include "moxaclassbased_datatypes.h"

class UaExtensionObject;
class UaVariant;
class UaDataValue;

// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

class MoxaClassBased_EXPORT IeeeDot1AS2011DataTypePrivate;

/**
 *  @brief Wrapper class for the UA stack structure MoxaClassBased_IeeeDot1AS2011DataType.
 *
 *  This class encapsulates the native MoxaClassBased_IeeeDot1AS2011DataType structure
 *  and handles memory allocation and cleanup for you.
 *  IeeeDot1AS2011DataType uses implicit sharing to avoid needless copying and to boost the performance.
 *  Only if you modify a shared IeeeDot1AS2011DataType it creates a copy for that (copy-on-write).
 *  So assigning another IeeeDot1AS2011DataType or passing it as parameter needs constant time and is nearly as fast as assigning a pointer.
 */
class MoxaClassBased_EXPORT IeeeDot1AS2011DataType
{
    MOXACLASSBASED_DECLARE_PRIVATE(IeeeDot1AS2011DataType)
public:
    IeeeDot1AS2011DataType();
    IeeeDot1AS2011DataType(const IeeeDot1AS2011DataType &other);
    IeeeDot1AS2011DataType(const MoxaClassBased_IeeeDot1AS2011DataType &other);
    IeeeDot1AS2011DataType(const UaExtensionObject &extensionObject);
    IeeeDot1AS2011DataType(const OpcUa_ExtensionObject &extensionObject);
    IeeeDot1AS2011DataType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach);
    IeeeDot1AS2011DataType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach);
    ~IeeeDot1AS2011DataType();

    void clear();

    bool operator==(const IeeeDot1AS2011DataType &other) const;
    bool operator!=(const IeeeDot1AS2011DataType &other) const;

    IeeeDot1AS2011DataType& operator=(const IeeeDot1AS2011DataType &other);

    MoxaClassBased_IeeeDot1AS2011DataType* copy() const;
    void copyTo(MoxaClassBased_IeeeDot1AS2011DataType *pDst) const;

    static MoxaClassBased_IeeeDot1AS2011DataType* clone(const MoxaClassBased_IeeeDot1AS2011DataType& source);
    static void cloneTo(const MoxaClassBased_IeeeDot1AS2011DataType& source, MoxaClassBased_IeeeDot1AS2011DataType& copy);

    void attach(const MoxaClassBased_IeeeDot1AS2011DataType *pValue);
    MoxaClassBased_IeeeDot1AS2011DataType* detach(MoxaClassBased_IeeeDot1AS2011DataType* pDst);

    void toVariant(UaVariant &variant) const;
    void toVariant(OpcUa_Variant &variant) const;
    void toVariant(UaVariant &variant, OpcUa_Boolean bDetach);
    void toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach);

    void toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const;
    void toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const;
    void toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps);
    void toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps);

    void toExtensionObject(UaExtensionObject &extensionObject) const;
    void toExtensionObject(OpcUa_ExtensionObject &extensionObject) const;
    void toExtensionObject(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach);
    void toExtensionObject(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach);

    OpcUa_StatusCode setIeeeDot1AS2011DataType(const UaExtensionObject &extensionObject);
    OpcUa_StatusCode setIeeeDot1AS2011DataType(const OpcUa_ExtensionObject &extensionObject);
    OpcUa_StatusCode setIeeeDot1AS2011DataType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach);
    OpcUa_StatusCode setIeeeDot1AS2011DataType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach);

    bool isPriority1Set() const;
    OpcUa_UInt16 getPriority1(bool *ok = 0) const;
    bool isPriority2Set() const;
    OpcUa_UInt16 getPriority2(bool *ok = 0) const;
    bool isAccuracyAlertSet() const;
    OpcUa_UInt64 getAccuracyAlert(bool *ok = 0) const;

    void setPriority1(OpcUa_UInt16 Priority1);
    void unsetPriority1();
    void setPriority2(OpcUa_UInt16 Priority2);
    void unsetPriority2();
    void setAccuracyAlert(OpcUa_UInt64 AccuracyAlert);
    void unsetAccuracyAlert();
};

class MoxaClassBased_EXPORT IeeeDot1AS2011DataTypes
{
public:
    IeeeDot1AS2011DataTypes();
    IeeeDot1AS2011DataTypes(const IeeeDot1AS2011DataTypes &other);
    IeeeDot1AS2011DataTypes(OpcUa_Int32 length, MoxaClassBased_IeeeDot1AS2011DataType* data);
    virtual ~IeeeDot1AS2011DataTypes();

    IeeeDot1AS2011DataTypes& operator=(const IeeeDot1AS2011DataTypes &other);
    MoxaClassBased_IeeeDot1AS2011DataType& operator[](OpcUa_UInt32 index);
    const MoxaClassBased_IeeeDot1AS2011DataType& operator[](OpcUa_UInt32 index) const;

    void attach(OpcUa_UInt32 length, MoxaClassBased_IeeeDot1AS2011DataType* data);
    void attach(OpcUa_Int32 length, MoxaClassBased_IeeeDot1AS2011DataType* data);
    MoxaClassBased_IeeeDot1AS2011DataType* detach();

    bool operator==(const IeeeDot1AS2011DataTypes &other) const;
    bool operator!=(const IeeeDot1AS2011DataTypes &other) const;

    void create(OpcUa_UInt32 length);
    void resize(OpcUa_UInt32 length);
    void clear();

    inline OpcUa_UInt32 length() const {return m_noOfElements;}
    inline const MoxaClassBased_IeeeDot1AS2011DataType* rawData() const {return m_data;}
    inline MoxaClassBased_IeeeDot1AS2011DataType* rawData() {return m_data;}
    void toVariant(UaVariant &variant) const;
    void toVariant(OpcUa_Variant &variant) const;
    void toVariant(UaVariant &variant, OpcUa_Boolean bDetach);
    void toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach);

    void toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const;
    void toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const;
    void toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps);
    void toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps);

    OpcUa_StatusCode setIeeeDot1AS2011DataTypes(const UaVariant &variant);
    OpcUa_StatusCode setIeeeDot1AS2011DataTypes(const OpcUa_Variant &variant);
    OpcUa_StatusCode setIeeeDot1AS2011DataTypes(UaVariant &variant, OpcUa_Boolean bDetach);
    OpcUa_StatusCode setIeeeDot1AS2011DataTypes(OpcUa_Variant &variant, OpcUa_Boolean bDetach);
    OpcUa_StatusCode setIeeeDot1AS2011DataTypes(OpcUa_Int32 length, MoxaClassBased_IeeeDot1AS2011DataType* data);

    static IeeeDot1AS2011DataTypes empty;
private:
    OpcUa_UInt32 m_noOfElements;
    MoxaClassBased_IeeeDot1AS2011DataType* m_data;
};

} // namespace MoxaClassBased

#endif // __MOXACLASSBASED_IEEEDOT1AS2011DATATYPE_H__

