/******************************************************************************
** moxaclassbased_vlanporttypebase.cpp
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#include "moxaclassbased_vlanporttypebase.h"
#include "moxaclassbased_vlanporttype.h"
#include "uagenericnodes.h"
#include "nodemanagerroot.h"
#include "methodhandleuanode.h"
#include "moxaclassbased_nodemanagermoxaclassbasedns.h"

#include "instancefactory.h"
#include "moxaclassbased_instancefactory_moxaclassbasedns.h"
#include "opcua_extensionobject.h"
// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

bool VlanPortTypeBase::s_typeNodesCreated = false;
OpcUa::BaseMethod* VlanPortTypeBase::s_pSetVlanPortMethod = NULL;
OpcUa::BaseDataVariableType* VlanPortTypeBase::s_pMode = NULL;
OpcUa::BaseDataVariableType* VlanPortTypeBase::s_pPriorityCodePoint = NULL;
OpcUa::BaseDataVariableType* VlanPortTypeBase::s_pPvid = NULL;
OpcUa::BaseDataVariableType* VlanPortTypeBase::s_pTaggedVlan = NULL;
OpcUa::BaseDataVariableType* VlanPortTypeBase::s_pUntaggedVlan = NULL;

/** Constructs an VlanPortType object using an instance declaration node as base
*/
VlanPortTypeBase::VlanPortTypeBase(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: OpcUa::BaseObjectType(nodeId, pInstanceDeclarationObject, pNodeConfig, pSharedMutex)
{
    initialize();
}

/** Constructs an VlanPortType object
*/
VlanPortTypeBase::VlanPortTypeBase(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: OpcUa::BaseObjectType(nodeId, name, browseNameNameSpaceIndex, pNodeConfig, pSharedMutex)
{
    initialize();
}

/**  Constructs an instance of the class VlanPortTypeBase with all components
*/
VlanPortTypeBase::VlanPortTypeBase(
    UaBase::Object*    pBaseNode,    //!< [in] The "tree" of nodes that specifies the attributes of the instance and its children
    XmlUaNodeFactoryManager* pFactory, //!< [in] The factory to create the children
    NodeManagerConfig* pNodeConfig,  //!< [in] Interface pointer to the NodeManagerConfig interface used to add and delete node and references in the address space
    UaMutexRefCounted* pSharedMutex) //!< [in] Shared mutex object used to synchronize access to the variable. Can be NULL if no shared mutex is provided
: OpcUa::BaseObjectType(pBaseNode, pFactory, pNodeConfig, pSharedMutex)
{
    UaStatus      addStatus;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }

    m_pMode = NULL;
    m_pPriorityCodePoint = NULL;
    m_pPvid = NULL;
    m_pTaggedVlan = NULL;
    m_pUntaggedVlan = NULL;
    m_pSetVlanPortMethod = NULL;

    std::list<UaBase::BaseNode*> lstReferencedNodes = pBaseNode->hierarchicallyReferencedNodes();
    for (std::list<UaBase::BaseNode*>::const_iterator it = lstReferencedNodes.begin(); it != lstReferencedNodes.end(); it++)
    {
        UaBase::BaseNode *pChild = *it;
        if (pChild->browseName() == UaQualifiedName("Mode", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pMode)
            {
                m_pMode = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pMode, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pMode->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("PriorityCodePoint", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pPriorityCodePoint)
            {
                m_pPriorityCodePoint = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pPriorityCodePoint, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pPriorityCodePoint->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("Pvid", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pPvid)
            {
                m_pPvid = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pPvid, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pPvid->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("TaggedVlan", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pTaggedVlan)
            {
                m_pTaggedVlan = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pTaggedVlan, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pTaggedVlan->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("UntaggedVlan", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pUntaggedVlan)
            {
                m_pUntaggedVlan = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pUntaggedVlan, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pUntaggedVlan->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (s_pSetVlanPortMethod && pChild->browseName() == s_pSetVlanPortMethod->browseName())
        {
            if (!m_pSetVlanPortMethod)
            {
                m_pSetVlanPortMethod = (OpcUa::BaseMethod*) pFactory->createMethod((UaBase::Method*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pSetVlanPortMethod, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Method*)pChild)->modellingRuleId().isNull())
                {
                    m_pSetVlanPortMethod->setModellingRuleId(((UaBase::Method*)pChild)->modellingRuleId());
                }
            }
        }
    }
    UA_ASSERT(m_pMode);
    UA_ASSERT(m_pPriorityCodePoint);
    UA_ASSERT(m_pPvid);
    UA_ASSERT(m_pTaggedVlan);
    UA_ASSERT(m_pUntaggedVlan);
    UA_ASSERT(m_pSetVlanPortMethod);
}

/** Initialize the object with all member nodes
*/
void VlanPortTypeBase::initialize()
{
    OpcUa_Int16 nsIdx = m_pNodeConfig->getNameSpaceIndex();
    UaStatus      addStatus;
    UaVariant     defaultValue;
    UaUInt32Array arrayDimensions;
    UaPropertyMethodArgument* pPropertyArg = NULL;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }
    m_pMode = NULL;
    m_pPriorityCodePoint = NULL;
    m_pPvid = NULL;
    m_pTaggedVlan = NULL;
    m_pUntaggedVlan = NULL;
    m_pSetVlanPortMethod = NULL;
    // Mandatory variable Mode
    m_pMode = new OpcUa::BaseDataVariableType(this, s_pMode, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pMode, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    m_pMode->setDataType(UaNodeId(MoxaClassBasedId_PortModeEnumType, MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));

    // Mandatory variable PriorityCodePoint
    m_pPriorityCodePoint = new OpcUa::BaseDataVariableType(this, s_pPriorityCodePoint, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pPriorityCodePoint, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

    // Mandatory variable Pvid
    m_pPvid = new OpcUa::BaseDataVariableType(this, s_pPvid, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pPvid, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

    // Mandatory variable TaggedVlan
    m_pTaggedVlan = new OpcUa::BaseDataVariableType(this, s_pTaggedVlan, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pTaggedVlan, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

    // Mandatory variable UntaggedVlan
    m_pUntaggedVlan = new OpcUa::BaseDataVariableType(this, s_pUntaggedVlan, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pUntaggedVlan, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());


    // Method SetVlanPort
    m_pSetVlanPortMethod = new OpcUa::BaseMethod(this, s_pSetVlanPortMethod, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pSetVlanPortMethod, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());
    // ------------------------------------------------------------------------
    // Add InputArguments
    // Create property
    pPropertyArg = new UaPropertyMethodArgument(
        UaNodeId(UaString("%1.SetVlanPort.InputArguments").arg(nodeId().toString()), nsIdx), // NodeId of the property
        OpcUa_AccessLevels_CurrentRead,         // Access level of the property
        1,                                      // Number of arguments
        UaPropertyMethodArgument::INARGUMENTS); // IN arguments
    // Argument Configuration
    pPropertyArg->setArgument(
        0,                      // Index of the argument
        "Configuration",             // Name of the argument
        UaNodeId(MoxaClassBasedId_VlanPortDataType, MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()),// Data type of the argument
        -1,                     // ValueRank of the argument
        arrayDimensions,
        UaLocalizedText("", "")); // Description
    // Add property to method
    addStatus = m_pNodeConfig->addNodeAndReference(m_pSetVlanPortMethod, pPropertyArg, OpcUaId_HasProperty);
    UA_ASSERT(addStatus.isGood());
    // ------------------------------------------------------------------------
    // Add OutputArguments
    // Create property
    pPropertyArg = new UaPropertyMethodArgument(
        UaNodeId(UaString("%1.SetVlanPort.OutputArguments").arg(nodeId().toString()), nsIdx), // NodeId of the property
        OpcUa_AccessLevels_CurrentRead,          // Access level of the property
        2,                                      // Number of arguments
        UaPropertyMethodArgument::OUTARGUMENTS); // OUT arguments
    // Argument ErrorCode
    pPropertyArg->setArgument(
        0,                      // Index of the argument
        "ErrorCode",             // Name of the argument
        UaNodeId(OpcUaId_UInt32),// Data type of the argument
        -1,                     // ValueRank of the argument
        arrayDimensions,
        UaLocalizedText("", "")); // Description
    // Argument ErrorMessage
    pPropertyArg->setArgument(
        1,                      // Index of the argument
        "ErrorMessage",             // Name of the argument
        UaNodeId(OpcUaId_String),// Data type of the argument
        -1,                     // ValueRank of the argument
        arrayDimensions,
        UaLocalizedText("", "")); // Description
    // Add property to method
    addStatus = m_pNodeConfig->addNodeAndReference(m_pSetVlanPortMethod, pPropertyArg, OpcUaId_HasProperty);
    UA_ASSERT(addStatus.isGood());

}

/** Destruction
*/
VlanPortTypeBase::~VlanPortTypeBase()
{
}

/** Create the related type nodes
*/
void VlanPortTypeBase::createTypes()
{
    if ( s_typeNodesCreated == false )
    {
        s_typeNodesCreated = true;

        UaStatus      addStatus;
        UaVariant     defaultValue;
        UaUInt32Array arrayDimensions;
        UaPropertyMethodArgument* pPropertyArg = NULL;
        NodeManagerRoot* pNodeManagerRoot = NodeManagerRoot::CreateRootNodeManager();
        OpcUa_Int16 nsTypeIdx = NodeManagerMoxaClassBasedNS::getTypeNamespace();
        OpcUa_Int16 nsSuperTypeIdx = NodeManagerRoot::getTypeNamespace();
        NodeManagerConfig* pTypeNodeConfig = pNodeManagerRoot->getNodeManagerByNamespace(nsTypeIdx)->getNodeManagerConfig();

        OpcUa::GenericObjectType* pObjectType;
        pObjectType = new OpcUa::GenericObjectType(
            UaNodeId(MoxaClassBasedId_VlanPortType, nsTypeIdx),
            UaQualifiedName("VlanPortType", nsTypeIdx),
            UaLocalizedText("", "VlanPortType"),
            UaLocalizedText("", ""),
            OpcUa_False,
            &VlanPortType::clearStaticMembers);
        addStatus = pTypeNodeConfig->addNodeAndReference(UaNodeId(OpcUaId_BaseObjectType, nsSuperTypeIdx), pObjectType, OpcUaId_HasSubtype);
        UA_ASSERT(addStatus.isGood());
        // ------------------------------------------------------------------------
        // Method SetVlanPort
        // ------------------------------------------------------------------------
        s_pSetVlanPortMethod = new OpcUa::BaseMethod(UaNodeId(MoxaClassBasedId_VlanPortType_SetVlanPort, nsTypeIdx), "SetVlanPort", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace());
        s_pSetVlanPortMethod->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pSetVlanPortMethod, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());
        // ------------------------------------------------------------------------
        // Add InputArguments
        // Create property
        pPropertyArg = new UaPropertyMethodArgument(
            UaNodeId(MoxaClassBasedId_VlanPortType_SetVlanPort_InputArguments, nsTypeIdx),       // NodeId of the property
            OpcUa_AccessLevels_CurrentRead,         // Access level of the property
            1,                                      // Number of arguments
            UaPropertyMethodArgument::INARGUMENTS); // IN arguments
        // Argument Configuration
        pPropertyArg->setArgument(
            0,                      // Index of the argument
            "Configuration",             // Name of the argument
            UaNodeId(MoxaClassBasedId_VlanPortDataType, MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()),// Data type of the argument
            -1,                     // Array rank of the argument
            arrayDimensions,
            UaLocalizedText("", "")); // Description
        // Set the ModellingRule to InputArguments
        pPropertyArg->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        // Add property to method
        pTypeNodeConfig->addNodeAndReference(s_pSetVlanPortMethod, pPropertyArg, OpcUaId_HasProperty);
        // ------------------------------------------------------------------------
        // Add OutputArguments
        // Create property
        pPropertyArg = new UaPropertyMethodArgument(
            UaNodeId(MoxaClassBasedId_VlanPortType_SetVlanPort_OutputArguments, nsTypeIdx),       // NodeId of the property
            OpcUa_AccessLevels_CurrentRead,          // Access level of the property
            2,                                      // Number of arguments
            UaPropertyMethodArgument::OUTARGUMENTS); // OUT arguments
        // Argument ErrorCode
        pPropertyArg->setArgument(
            0,                      // Index of the argument
            "ErrorCode",             // Name of the argument
            UaNodeId(OpcUaId_UInt32),// Data type of the argument
            -1,                     // Array rank of the argument
            arrayDimensions,
            UaLocalizedText("", "")); // Description
        // Argument ErrorMessage
        pPropertyArg->setArgument(
            1,                      // Index of the argument
            "ErrorMessage",             // Name of the argument
            UaNodeId(OpcUaId_String),// Data type of the argument
            -1,                     // Array rank of the argument
            arrayDimensions,
            UaLocalizedText("", "")); // Description
        // Set the ModellingRule to OutputArguments
        pPropertyArg->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        // Add property to method
        addStatus = pTypeNodeConfig->addNodeAndReference(s_pSetVlanPortMethod, pPropertyArg, OpcUaId_HasProperty);
        UA_ASSERT(addStatus.isGood());


        // Mandatory variable Mode
        defaultValue.setInt32((OpcUa_Int32) (MoxaClassBased::PortModeEnumType)0);
        s_pMode = new OpcUa::BaseDataVariableType(UaNodeId(MoxaClassBasedId_VlanPortType_Mode, nsTypeIdx), "Mode", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pMode->setDataType(UaNodeId(MoxaClassBasedId_PortModeEnumType, MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()));
        s_pMode->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pMode->setValueRank(-1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pMode, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

        // Mandatory variable PriorityCodePoint
        defaultValue.setUInt16(0);
        s_pPriorityCodePoint = new OpcUa::BaseDataVariableType(UaNodeId(MoxaClassBasedId_VlanPortType_PriorityCodePoint, nsTypeIdx), "PriorityCodePoint", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pPriorityCodePoint->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pPriorityCodePoint->setValueRank(-1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pPriorityCodePoint, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

        // Mandatory variable Pvid
        defaultValue.setUInt16(0);
        s_pPvid = new OpcUa::BaseDataVariableType(UaNodeId(MoxaClassBasedId_VlanPortType_Pvid, nsTypeIdx), "Pvid", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pPvid->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pPvid->setValueRank(-1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pPvid, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

        // Mandatory variable TaggedVlan
        UaUInt16Array valTaggedVlan;
        defaultValue.setUInt16Array(valTaggedVlan);
        s_pTaggedVlan = new OpcUa::BaseDataVariableType(UaNodeId(MoxaClassBasedId_VlanPortType_TaggedVlan, nsTypeIdx), "TaggedVlan", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pTaggedVlan->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pTaggedVlan->setValueRank(1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pTaggedVlan, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

        // Mandatory variable UntaggedVlan
        UaUInt16Array valUntaggedVlan;
        defaultValue.setUInt16Array(valUntaggedVlan);
        s_pUntaggedVlan = new OpcUa::BaseDataVariableType(UaNodeId(MoxaClassBasedId_VlanPortType_UntaggedVlan, nsTypeIdx), "UntaggedVlan", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pUntaggedVlan->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pUntaggedVlan->setValueRank(1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pUntaggedVlan, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

    }
}

/** Clear the static members of the class
*/
void VlanPortTypeBase::clearStaticMembers()
{
    s_typeNodesCreated = false;

    s_pMode = NULL;
    s_pPriorityCodePoint = NULL;
    s_pPvid = NULL;
    s_pTaggedVlan = NULL;
    s_pUntaggedVlan = NULL;
    s_pSetVlanPortMethod = NULL;
}

/** Returns the type definition NodeId for the VlanPortType
*/
UaNodeId VlanPortTypeBase::typeDefinitionId() const
{
    UaNodeId ret(MoxaClassBasedId_VlanPortType, NodeManagerMoxaClassBasedNS::getTypeNamespace());
    return ret;
}

/** Implementation of the MethodManager interface method beginCall
*/
UaStatus VlanPortTypeBase::beginCall(
    MethodManagerCallback* pCallback,
    const ServiceContext&  serviceContext,
    OpcUa_UInt32           callbackHandle,
    MethodHandle*          pMethodHandle,
    const UaVariantArray&  inputArguments)
{
    UaStatus            ret;

    OpcUa::MethodCallJob* pCallJob = new OpcUa::MethodCallJob;
    pCallJob->initialize(this, pCallback, serviceContext, callbackHandle, pMethodHandle, inputArguments);
    ret = NodeManagerRoot::CreateRootNodeManager()->pServerManager()->getThreadPool()->addJob(pCallJob);
    if ( ret.isBad() )
    {
        delete pCallJob;
    }

    return ret;
}

/** Synchronous version of the MethodManager method call executed in a worker thread
*/
UaStatus VlanPortTypeBase::call(
    const ServiceContext&  serviceContext,
    MethodHandle*          pMethodHandle,
    const UaVariantArray&  inputArguments,
    UaVariantArray&        outputArguments,
    UaStatusCodeArray&     inputArgumentResults,
    UaDiagnosticInfos&     inputArgumentDiag)
{
    UaStatus            ret;
    MethodHandleUaNode* pMethodHandleUaNode = (MethodHandleUaNode*)pMethodHandle;
    UaMethod*           pMethod             = NULL;

    if (pMethodHandleUaNode)
    {
        pMethod = pMethodHandleUaNode->pUaMethod();

        if (pMethod)
        {
            if ( ( (m_pSetVlanPortMethod != NULL) && (pMethod->nodeId() == m_pSetVlanPortMethod->nodeId()) )
                 || ( (s_pSetVlanPortMethod != NULL) && (pMethod->nodeId() == s_pSetVlanPortMethod->nodeId()) ) )
            {
                if ( inputArguments.length() < 1 )
                {
                    ret = OpcUa_BadArgumentsMissing;
                }
                else if ( inputArguments.length() > 1 )
                {
                    ret = OpcUa_BadTooManyArguments;
                }
                else
                {
                    inputArgumentResults.create(1);

                    OpcUa_UInt32 ErrorCode = 0;
                    UaString ErrorMessage;
                    UaVariant value;
                    UaStatus tmpRet;

                    MoxaClassBased::VlanPortDataType Configuration;
                    value = inputArguments[ 0 ];
                    UaExtensionObject extConfiguration;
                    value.toExtensionObject(extConfiguration);
                    tmpRet = Configuration.setVlanPortDataType(extConfiguration, OpcUa_True);
                    inputArgumentResults[ 0 ] = tmpRet.statusCode();
                    if (tmpRet.isNotGood()) {ret = tmpRet;}

                    if ( ret.isGood() )
                    {
                        ret = this->SetVlanPort(serviceContext, Configuration, ErrorCode, ErrorMessage);
                    }
                    if ( ret.isNotBad() )
                    {
                        outputArguments.create(2);
                        value.setUInt32(ErrorCode);
                        outputArguments[ 0 ] = *(OpcUa_Variant*)(const OpcUa_Variant*)value;
                        value.detach();
                        value.setString(ErrorMessage);
                        outputArguments[ 1 ] = *(OpcUa_Variant*)(const OpcUa_Variant*)value;
                        value.detach();
                    }
                }

            }
            else
            {
                return BaseObjectType::call(serviceContext, pMethodHandle, inputArguments, outputArguments, inputArgumentResults, inputArgumentDiag);
            }
        }
        else
        {
            assert(false);
            ret = OpcUa_BadInvalidArgument;
        }
    }
    else
    {
        assert(false);
        ret = OpcUa_BadInvalidArgument;
    }

    return ret;
}

/**
 *  Sets the Mode value
 */
void VlanPortTypeBase::setMode(MoxaClassBased::PortModeEnumType Mode)
{
    UaVariant value;
    value.setInt32(Mode);
    UaDataValue dataValue;
    dataValue.setValue(value, OpcUa_True, OpcUa_True);
    m_pMode->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Returns the value of Mode
 */
MoxaClassBased::PortModeEnumType VlanPortTypeBase::getMode() const
{
    UaVariant defaultValue;
    MoxaClassBased::PortModeEnumType ret = (MoxaClassBased::PortModeEnumType)0;
    UaDataValue dataValue(m_pMode->value(NULL));
    defaultValue = *dataValue.value();
    OpcUa_Int32 i = (OpcUa_Int32) (MoxaClassBased::PortModeEnumType)0;
    defaultValue.toInt32(i);
    ret = (MoxaClassBased::PortModeEnumType) i;
    return ret;
}

/**
 *  Sets the PriorityCodePoint value
 */
void VlanPortTypeBase::setPriorityCodePoint(OpcUa_UInt16 PriorityCodePoint)
{
    UaVariant value;
    value.setUInt16(PriorityCodePoint);
    UaDataValue dataValue;
    dataValue.setValue(value, OpcUa_True, OpcUa_True);
    m_pPriorityCodePoint->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Returns the value of PriorityCodePoint
 */
OpcUa_UInt16 VlanPortTypeBase::getPriorityCodePoint() const
{
    UaVariant defaultValue;
    OpcUa_UInt16 ret = 0;
    UaDataValue dataValue(m_pPriorityCodePoint->value(NULL));
    defaultValue = *dataValue.value();
    defaultValue.toUInt16(ret);
    return ret;
}

/**
 *  Sets the Pvid value
 */
void VlanPortTypeBase::setPvid(OpcUa_UInt16 Pvid)
{
    UaVariant value;
    value.setUInt16(Pvid);
    UaDataValue dataValue;
    dataValue.setValue(value, OpcUa_True, OpcUa_True);
    m_pPvid->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Returns the value of Pvid
 */
OpcUa_UInt16 VlanPortTypeBase::getPvid() const
{
    UaVariant defaultValue;
    OpcUa_UInt16 ret = 0;
    UaDataValue dataValue(m_pPvid->value(NULL));
    defaultValue = *dataValue.value();
    defaultValue.toUInt16(ret);
    return ret;
}

/**
 *  Sets the TaggedVlan
 */
void VlanPortTypeBase::setTaggedVlan(const UaUInt16Array& TaggedVlan)
{
    UaDataValue dataValue;
    TaggedVlan.toDataValue(dataValue, OpcUa_True);
    m_pTaggedVlan->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Gets the TaggedVlan
 */
void VlanPortTypeBase::getTaggedVlan(UaUInt16Array& TaggedVlan) const
{
    TaggedVlan.clear();
    if ( m_pTaggedVlan != NULL )
    {
        UaDataValue dataValue(m_pTaggedVlan->value(NULL));
        UaVariant value;
        value.attach(dataValue.value());
        value.toUInt16Array(TaggedVlan);
        value.detach();
    }
}

/**
 *  Sets the UntaggedVlan
 */
void VlanPortTypeBase::setUntaggedVlan(const UaUInt16Array& UntaggedVlan)
{
    UaDataValue dataValue;
    UntaggedVlan.toDataValue(dataValue, OpcUa_True);
    m_pUntaggedVlan->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Gets the UntaggedVlan
 */
void VlanPortTypeBase::getUntaggedVlan(UaUInt16Array& UntaggedVlan) const
{
    UntaggedVlan.clear();
    if ( m_pUntaggedVlan != NULL )
    {
        UaDataValue dataValue(m_pUntaggedVlan->value(NULL));
        UaVariant value;
        value.attach(dataValue.value());
        value.toUInt16Array(UntaggedVlan);
        value.detach();
    }
}

/** Returns the Mode node.
 */
OpcUa::BaseDataVariableType* VlanPortTypeBase::getModeNode()
{
    return m_pMode;
}

/** Returns the Mode node.
 */
const OpcUa::BaseDataVariableType* VlanPortTypeBase::getModeNode() const
{
    return m_pMode;
}

/** Returns the PriorityCodePoint node.
 */
OpcUa::BaseDataVariableType* VlanPortTypeBase::getPriorityCodePointNode()
{
    return m_pPriorityCodePoint;
}

/** Returns the PriorityCodePoint node.
 */
const OpcUa::BaseDataVariableType* VlanPortTypeBase::getPriorityCodePointNode() const
{
    return m_pPriorityCodePoint;
}

/** Returns the Pvid node.
 */
OpcUa::BaseDataVariableType* VlanPortTypeBase::getPvidNode()
{
    return m_pPvid;
}

/** Returns the Pvid node.
 */
const OpcUa::BaseDataVariableType* VlanPortTypeBase::getPvidNode() const
{
    return m_pPvid;
}

/** Returns the TaggedVlan node.
 */
OpcUa::BaseDataVariableType* VlanPortTypeBase::getTaggedVlanNode()
{
    return m_pTaggedVlan;
}

/** Returns the TaggedVlan node.
 */
const OpcUa::BaseDataVariableType* VlanPortTypeBase::getTaggedVlanNode() const
{
    return m_pTaggedVlan;
}

/** Returns the UntaggedVlan node.
 */
OpcUa::BaseDataVariableType* VlanPortTypeBase::getUntaggedVlanNode()
{
    return m_pUntaggedVlan;
}

/** Returns the UntaggedVlan node.
 */
const OpcUa::BaseDataVariableType* VlanPortTypeBase::getUntaggedVlanNode() const
{
    return m_pUntaggedVlan;
}

/** Returns the SetVlanPort node.
  */
OpcUa::BaseMethod* VlanPortTypeBase::getSetVlanPort()
{
    return m_pSetVlanPortMethod;
}

/** Returns the SetVlanPort node.
  */
const OpcUa::BaseMethod* VlanPortTypeBase::getSetVlanPort() const
{
    return m_pSetVlanPortMethod;
}

/** Uses the NodeAccessInfo of pOther and its children. */
void VlanPortTypeBase::useAccessInfoFromInstance(VlanPortTypeBase *pOther)
{
    OpcUa::BaseObjectType::useAccessInfoFromInstance(pOther);

    // children
    m_pMode->useAccessInfoFromInstance(pOther->m_pMode);
    m_pPriorityCodePoint->useAccessInfoFromInstance(pOther->m_pPriorityCodePoint);
    m_pPvid->useAccessInfoFromInstance(pOther->m_pPvid);
    m_pTaggedVlan->useAccessInfoFromInstance(pOther->m_pTaggedVlan);
    m_pUntaggedVlan->useAccessInfoFromInstance(pOther->m_pUntaggedVlan);
    m_pSetVlanPortMethod->useAccessInfoFrom(pOther->m_pSetVlanPortMethod);
}

/** Set the NodeAccessInfo for this node and all of its children. */
void VlanPortTypeBase::setAccessInfoWithChildren(NodeAccessInfo* pNodeAccessInfo)
{
    OpcUa::BaseObjectType::setAccessInfoWithChildren(pNodeAccessInfo);

    // children
    m_pMode->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pPriorityCodePoint->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pPvid->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pTaggedVlan->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pUntaggedVlan->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pSetVlanPortMethod->setAccessInfoWithChildren(pNodeAccessInfo);
}


} // End namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/


