/******************************************************************************
** moxaclassbased_deviceprofiletypebase.cpp
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#include "moxaclassbased_deviceprofiletypebase.h"
#include "moxaclassbased_deviceprofiletype.h"
#include "uagenericnodes.h"
#include "nodemanagerroot.h"
#include "methodhandleuanode.h"
#include "moxaclassbased_nodemanagermoxaclassbasedns.h"

#include "instancefactory.h"
#include "opcua_extensionobject.h"
// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

bool DeviceProfileTypeBase::s_typeNodesCreated = false;
OpcUa::BaseDataVariableType* DeviceProfileTypeBase::s_pDeviceProfileName = NULL;

/** Constructs an DeviceProfileType object using an instance declaration node as base
*/
DeviceProfileTypeBase::DeviceProfileTypeBase(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: OpcUa::BaseObjectType(nodeId, pInstanceDeclarationObject, pNodeConfig, pSharedMutex)
{
    initialize();
}

/** Constructs an DeviceProfileType object
*/
DeviceProfileTypeBase::DeviceProfileTypeBase(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: OpcUa::BaseObjectType(nodeId, name, browseNameNameSpaceIndex, pNodeConfig, pSharedMutex)
{
    initialize();
}

/**  Constructs an instance of the class DeviceProfileTypeBase with all components
*/
DeviceProfileTypeBase::DeviceProfileTypeBase(
    UaBase::Object*    pBaseNode,    //!< [in] The "tree" of nodes that specifies the attributes of the instance and its children
    XmlUaNodeFactoryManager* pFactory, //!< [in] The factory to create the children
    NodeManagerConfig* pNodeConfig,  //!< [in] Interface pointer to the NodeManagerConfig interface used to add and delete node and references in the address space
    UaMutexRefCounted* pSharedMutex) //!< [in] Shared mutex object used to synchronize access to the variable. Can be NULL if no shared mutex is provided
: OpcUa::BaseObjectType(pBaseNode, pFactory, pNodeConfig, pSharedMutex)
{
    UaStatus      addStatus;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }

    m_pDeviceProfileName = NULL;

    std::list<UaBase::BaseNode*> lstReferencedNodes = pBaseNode->hierarchicallyReferencedNodes();
    for (std::list<UaBase::BaseNode*>::const_iterator it = lstReferencedNodes.begin(); it != lstReferencedNodes.end(); it++)
    {
        UaBase::BaseNode *pChild = *it;
        if (pChild->browseName() == UaQualifiedName("DeviceProfileName", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace()))
        {
            if (!m_pDeviceProfileName)
            {
                m_pDeviceProfileName = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pDeviceProfileName, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pDeviceProfileName->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
    }
    UA_ASSERT(m_pDeviceProfileName);
}

/** Initialize the object with all member nodes
*/
void DeviceProfileTypeBase::initialize()
{
    UaStatus      addStatus;
    UaVariant     defaultValue;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }
    m_pDeviceProfileName = NULL;
    // Mandatory variable DeviceProfileName
    m_pDeviceProfileName = new OpcUa::BaseDataVariableType(this, s_pDeviceProfileName, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pDeviceProfileName, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());


}

/** Destruction
*/
DeviceProfileTypeBase::~DeviceProfileTypeBase()
{
}

/** Create the related type nodes
*/
void DeviceProfileTypeBase::createTypes()
{
    if ( s_typeNodesCreated == false )
    {
        s_typeNodesCreated = true;

        UaStatus      addStatus;
        UaVariant     defaultValue;
        NodeManagerRoot* pNodeManagerRoot = NodeManagerRoot::CreateRootNodeManager();
        OpcUa_Int16 nsTypeIdx = NodeManagerMoxaClassBasedNS::getTypeNamespace();
        OpcUa_Int16 nsSuperTypeIdx = NodeManagerRoot::getTypeNamespace();
        NodeManagerConfig* pTypeNodeConfig = pNodeManagerRoot->getNodeManagerByNamespace(nsTypeIdx)->getNodeManagerConfig();

        OpcUa::GenericObjectType* pObjectType;
        pObjectType = new OpcUa::GenericObjectType(
            UaNodeId(MoxaClassBasedId_DeviceProfileType, nsTypeIdx),
            UaQualifiedName("DeviceProfileType", nsTypeIdx),
            UaLocalizedText("", "DeviceProfileType"),
            UaLocalizedText("", ""),
            OpcUa_False,
            &DeviceProfileType::clearStaticMembers);
        addStatus = pTypeNodeConfig->addNodeAndReference(UaNodeId(OpcUaId_BaseObjectType, nsSuperTypeIdx), pObjectType, OpcUaId_HasSubtype);
        UA_ASSERT(addStatus.isGood());

        // Mandatory variable DeviceProfileName
        defaultValue.setString("");
        s_pDeviceProfileName = new OpcUa::BaseDataVariableType(UaNodeId(MoxaClassBasedId_DeviceProfileType_DeviceProfileName, nsTypeIdx), "DeviceProfileName", MoxaClassBased::NodeManagerMoxaClassBasedNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pDeviceProfileName->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pDeviceProfileName->setValueRank(-1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pDeviceProfileName, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

    }
}

/** Clear the static members of the class
*/
void DeviceProfileTypeBase::clearStaticMembers()
{
    s_typeNodesCreated = false;

    s_pDeviceProfileName = NULL;
}

/** Returns the type definition NodeId for the DeviceProfileType
*/
UaNodeId DeviceProfileTypeBase::typeDefinitionId() const
{
    UaNodeId ret(MoxaClassBasedId_DeviceProfileType, NodeManagerMoxaClassBasedNS::getTypeNamespace());
    return ret;
}

/**
 *  Sets the DeviceProfileName value
 */
void DeviceProfileTypeBase::setDeviceProfileName(const UaString& DeviceProfileName)
{
    UaVariant value;
    value.setString(DeviceProfileName);
    UaDataValue dataValue;
    dataValue.setValue(value, OpcUa_True, OpcUa_True);
    m_pDeviceProfileName->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Returns the value of DeviceProfileName
 */
UaString DeviceProfileTypeBase::getDeviceProfileName() const
{
    UaVariant defaultValue;
    UaString ret;
    UaDataValue dataValue(m_pDeviceProfileName->value(NULL));
    defaultValue = *dataValue.value();
    ret = defaultValue.toString();
    return ret;
}

/** Returns the DeviceProfileName node.
 */
OpcUa::BaseDataVariableType* DeviceProfileTypeBase::getDeviceProfileNameNode()
{
    return m_pDeviceProfileName;
}

/** Returns the DeviceProfileName node.
 */
const OpcUa::BaseDataVariableType* DeviceProfileTypeBase::getDeviceProfileNameNode() const
{
    return m_pDeviceProfileName;
}


/** Uses the NodeAccessInfo of pOther and its children. */
void DeviceProfileTypeBase::useAccessInfoFromInstance(DeviceProfileTypeBase *pOther)
{
    OpcUa::BaseObjectType::useAccessInfoFromInstance(pOther);

    // children
    m_pDeviceProfileName->useAccessInfoFromInstance(pOther->m_pDeviceProfileName);
}

/** Set the NodeAccessInfo for this node and all of its children. */
void DeviceProfileTypeBase::setAccessInfoWithChildren(NodeAccessInfo* pNodeAccessInfo)
{
    OpcUa::BaseObjectType::setAccessInfoWithChildren(pNodeAccessInfo);

    // children
    m_pDeviceProfileName->setAccessInfoWithChildren(pNodeAccessInfo);
}


} // End namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/


