/******************************************************************************
** opcuaclassbnm_isrclasstypebase.cpp
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://opcfoundation.org/UA/BNM/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#include "opcuaclassbnm_isrclasstypebase.h"
#include "opcuaclassbnm_isrclasstype.h"
#include "uagenericnodes.h"
#include "nodemanagerroot.h"
#include "methodhandleuanode.h"
#include "opcuaclassbnm_nodemanageropcuaclassbnmns.h"

#include "instancefactory.h"
#include "opcua_extensionobject.h"
// Namespace for the UA information model http://opcfoundation.org/UA/BNM/
namespace OpcUaClassBnm {

bool ISrClassTypeBase::s_typeNodesCreated = false;
OpcUa::BaseDataVariableType* ISrClassTypeBase::s_pId = NULL;
OpcUa::BaseDataVariableType* ISrClassTypeBase::s_pPriority = NULL;
OpcUa::BaseDataVariableType* ISrClassTypeBase::s_pVid = NULL;

/** Constructs an ISrClassType object using an instance declaration node as base
*/
ISrClassTypeBase::ISrClassTypeBase(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: OpcUa::BaseInterfaceType(nodeId, pInstanceDeclarationObject, pNodeConfig, pSharedMutex)
{
    initialize();
}

/** Constructs an ISrClassType object
*/
ISrClassTypeBase::ISrClassTypeBase(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex)
: OpcUa::BaseInterfaceType(nodeId, name, browseNameNameSpaceIndex, pNodeConfig, pSharedMutex)
{
    initialize();
}

/**  Constructs an instance of the class ISrClassTypeBase with all components
*/
ISrClassTypeBase::ISrClassTypeBase(
    UaBase::Object*    pBaseNode,    //!< [in] The "tree" of nodes that specifies the attributes of the instance and its children
    XmlUaNodeFactoryManager* pFactory, //!< [in] The factory to create the children
    NodeManagerConfig* pNodeConfig,  //!< [in] Interface pointer to the NodeManagerConfig interface used to add and delete node and references in the address space
    UaMutexRefCounted* pSharedMutex) //!< [in] Shared mutex object used to synchronize access to the variable. Can be NULL if no shared mutex is provided
: OpcUa::BaseInterfaceType(pBaseNode, pFactory, pNodeConfig, pSharedMutex)
{
    UaStatus      addStatus;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }

    m_pId = NULL;
    m_pPriority = NULL;
    m_pVid = NULL;

    std::list<UaBase::BaseNode*> lstReferencedNodes = pBaseNode->hierarchicallyReferencedNodes();
    for (std::list<UaBase::BaseNode*>::const_iterator it = lstReferencedNodes.begin(); it != lstReferencedNodes.end(); it++)
    {
        UaBase::BaseNode *pChild = *it;
        if (pChild->browseName() == UaQualifiedName("Id", OpcUaClassBnm::NodeManagerOpcUaClassBnmNS::getTypeNamespace()))
        {
            if (!m_pId)
            {
                m_pId = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pId, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pId->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("Priority", OpcUaClassBnm::NodeManagerOpcUaClassBnmNS::getTypeNamespace()))
        {
            if (!m_pPriority)
            {
                m_pPriority = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pPriority, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pPriority->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
        else if (pChild->browseName() == UaQualifiedName("Vid", OpcUaClassBnm::NodeManagerOpcUaClassBnmNS::getTypeNamespace()))
        {
            if (!m_pVid)
            {
                m_pVid = (OpcUa::BaseDataVariableType*) pFactory->createVariable((UaBase::Variable*)pChild, pNodeConfig, pSharedMutex);
                addStatus = pNodeConfig->addNodeAndReference(this, m_pVid, OpcUaId_HasComponent);
                UA_ASSERT(addStatus.isGood());
                if (!((UaBase::Variable*)pChild)->modellingRuleId().isNull())
                {
                    m_pVid->setModellingRuleId(((UaBase::Variable*)pChild)->modellingRuleId());
                }
            }
        }
    }
    UA_ASSERT(m_pId);
    UA_ASSERT(m_pPriority);
    UA_ASSERT(m_pVid);
}

/** Initialize the object with all member nodes
*/
void ISrClassTypeBase::initialize()
{
    UaStatus      addStatus;
    UaVariant     defaultValue;

    if ( s_typeNodesCreated == false )
    {
        createTypes();
    }
    m_pId = NULL;
    m_pPriority = NULL;
    m_pVid = NULL;
    // Mandatory variable Id
    m_pId = new OpcUa::BaseDataVariableType(this, s_pId, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pId, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

    // Mandatory variable Priority
    m_pPriority = new OpcUa::BaseDataVariableType(this, s_pPriority, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pPriority, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());

    // Mandatory variable Vid
    m_pVid = new OpcUa::BaseDataVariableType(this, s_pVid, m_pNodeConfig, m_pSharedMutex);
    addStatus = m_pNodeConfig->addNodeAndReference(this, m_pVid, OpcUaId_HasComponent);
    UA_ASSERT(addStatus.isGood());


}

/** Destruction
*/
ISrClassTypeBase::~ISrClassTypeBase()
{
}

/** Create the related type nodes
*/
void ISrClassTypeBase::createTypes()
{
    if ( s_typeNodesCreated == false )
    {
        s_typeNodesCreated = true;

        // Check if supertype is already created
        OpcUa::BaseInterfaceType::createTypes();

        UaStatus      addStatus;
        UaVariant     defaultValue;
        NodeManagerRoot* pNodeManagerRoot = NodeManagerRoot::CreateRootNodeManager();
        OpcUa_Int16 nsTypeIdx = NodeManagerOpcUaClassBnmNS::getTypeNamespace();
        OpcUa_Int16 nsSuperTypeIdx = NodeManagerRoot::getTypeNamespace();
        NodeManagerConfig* pTypeNodeConfig = pNodeManagerRoot->getNodeManagerByNamespace(nsTypeIdx)->getNodeManagerConfig();

        OpcUa::GenericObjectType* pObjectType;
        pObjectType = new OpcUa::GenericObjectType(
            UaNodeId(OpcUaClassBnmId_ISrClassType, nsTypeIdx),
            UaQualifiedName("ISrClassType", nsTypeIdx),
            UaLocalizedText("", "ISrClassType"),
            UaLocalizedText("", ""),
            OpcUa_True,
            &ISrClassType::clearStaticMembers);
        addStatus = pTypeNodeConfig->addNodeAndReference(UaNodeId(OpcUaId_BaseInterfaceType, nsSuperTypeIdx), pObjectType, OpcUaId_HasSubtype);
        UA_ASSERT(addStatus.isGood());

        // Mandatory variable Id
        defaultValue.setByte(0);
        s_pId = new OpcUa::BaseDataVariableType(UaNodeId(OpcUaClassBnmId_ISrClassType_Id, nsTypeIdx), "Id", OpcUaClassBnm::NodeManagerOpcUaClassBnmNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pId->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pId->setValueRank(-1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pId, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

        // Mandatory variable Priority
        defaultValue.setByte(0);
        s_pPriority = new OpcUa::BaseDataVariableType(UaNodeId(OpcUaClassBnmId_ISrClassType_Priority, nsTypeIdx), "Priority", OpcUaClassBnm::NodeManagerOpcUaClassBnmNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pPriority->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pPriority->setValueRank(-1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pPriority, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

        // Mandatory variable Vid
        defaultValue.setUInt16(0);
        s_pVid = new OpcUa::BaseDataVariableType(UaNodeId(OpcUaClassBnmId_ISrClassType_Vid, nsTypeIdx), "Vid", OpcUaClassBnm::NodeManagerOpcUaClassBnmNS::getTypeNamespace(), defaultValue, 3, pTypeNodeConfig);
        s_pVid->setModellingRuleId(OpcUaId_ModellingRule_Mandatory);
        s_pVid->setValueRank(-1);
        addStatus = pTypeNodeConfig->addNodeAndReference(pObjectType, s_pVid, OpcUaId_HasComponent);
        UA_ASSERT(addStatus.isGood());

    }
}

/** Clear the static members of the class
*/
void ISrClassTypeBase::clearStaticMembers()
{
    s_typeNodesCreated = false;

    s_pId = NULL;
    s_pPriority = NULL;
    s_pVid = NULL;
}

/** Returns the type definition NodeId for the ISrClassType
*/
UaNodeId ISrClassTypeBase::typeDefinitionId() const
{
    UaNodeId ret(OpcUaClassBnmId_ISrClassType, NodeManagerOpcUaClassBnmNS::getTypeNamespace());
    return ret;
}

/**
 *  Sets the Id value
 */
void ISrClassTypeBase::setId(OpcUa_Byte Id)
{
    UaVariant value;
    value.setByte(Id);
    UaDataValue dataValue;
    dataValue.setValue(value, OpcUa_True, OpcUa_True);
    m_pId->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Returns the value of Id
 */
OpcUa_Byte ISrClassTypeBase::getId() const
{
    UaVariant defaultValue;
    OpcUa_Byte ret = 0;
    UaDataValue dataValue(m_pId->value(NULL));
    defaultValue = *dataValue.value();
    defaultValue.toByte(ret);
    return ret;
}

/**
 *  Sets the Priority value
 */
void ISrClassTypeBase::setPriority(OpcUa_Byte Priority)
{
    UaVariant value;
    value.setByte(Priority);
    UaDataValue dataValue;
    dataValue.setValue(value, OpcUa_True, OpcUa_True);
    m_pPriority->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Returns the value of Priority
 */
OpcUa_Byte ISrClassTypeBase::getPriority() const
{
    UaVariant defaultValue;
    OpcUa_Byte ret = 0;
    UaDataValue dataValue(m_pPriority->value(NULL));
    defaultValue = *dataValue.value();
    defaultValue.toByte(ret);
    return ret;
}

/**
 *  Sets the Vid value
 */
void ISrClassTypeBase::setVid(OpcUa_UInt16 Vid)
{
    UaVariant value;
    value.setUInt16(Vid);
    UaDataValue dataValue;
    dataValue.setValue(value, OpcUa_True, OpcUa_True);
    m_pVid->setValue(NULL, dataValue, OpcUa_False);
}

/**
 *  Returns the value of Vid
 */
OpcUa_UInt16 ISrClassTypeBase::getVid() const
{
    UaVariant defaultValue;
    OpcUa_UInt16 ret = 0;
    UaDataValue dataValue(m_pVid->value(NULL));
    defaultValue = *dataValue.value();
    defaultValue.toUInt16(ret);
    return ret;
}

/** Returns the Id node.
 */
OpcUa::BaseDataVariableType* ISrClassTypeBase::getIdNode()
{
    return m_pId;
}

/** Returns the Id node.
 */
const OpcUa::BaseDataVariableType* ISrClassTypeBase::getIdNode() const
{
    return m_pId;
}

/** Returns the Priority node.
 */
OpcUa::BaseDataVariableType* ISrClassTypeBase::getPriorityNode()
{
    return m_pPriority;
}

/** Returns the Priority node.
 */
const OpcUa::BaseDataVariableType* ISrClassTypeBase::getPriorityNode() const
{
    return m_pPriority;
}

/** Returns the Vid node.
 */
OpcUa::BaseDataVariableType* ISrClassTypeBase::getVidNode()
{
    return m_pVid;
}

/** Returns the Vid node.
 */
const OpcUa::BaseDataVariableType* ISrClassTypeBase::getVidNode() const
{
    return m_pVid;
}


/** Uses the NodeAccessInfo of pOther and its children. */
void ISrClassTypeBase::useAccessInfoFromInstance(ISrClassTypeBase *pOther)
{
    OpcUa::BaseInterfaceType::useAccessInfoFromInstance(pOther);

    // children
    m_pId->useAccessInfoFromInstance(pOther->m_pId);
    m_pPriority->useAccessInfoFromInstance(pOther->m_pPriority);
    m_pVid->useAccessInfoFromInstance(pOther->m_pVid);
}

/** Set the NodeAccessInfo for this node and all of its children. */
void ISrClassTypeBase::setAccessInfoWithChildren(NodeAccessInfo* pNodeAccessInfo)
{
    OpcUa::BaseInterfaceType::setAccessInfoWithChildren(pNodeAccessInfo);

    // children
    m_pId->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pPriority->setAccessInfoWithChildren(pNodeAccessInfo);
    m_pVid->setAccessInfoWithChildren(pNodeAccessInfo);
}


} // End namespace for the UA information model http://opcfoundation.org/UA/BNM/


