/******************************************************************************
** moxaclassbased_deviceaccounttypebase.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#ifndef __MOXACLASSBASED_DEVICEACCOUNTTYPEBASE_H__
#define __MOXACLASSBASED_DEVICEACCOUNTTYPEBASE_H__

#include "opcua_baseobjecttype.h"
#include "moxaclassbased_datatypes.h"
#include "basenodes.h"
#include "moxaclassbased_identifiers.h"
#include "moxaclassbased_instancefactory_moxaclassbasedns.h"
#include "opcua_basedatavariabletype.h"

// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {


/** Generated base class for a DeviceAccountType.
 *
 *  This class contains the generated base code for the object type DeviceAccountType
 *  representing an OPC UA ObjectType. This class is used to create the object type and to
 *  create and represent instances of the object type in the server address space.
 *
 *  **Variable members of the DeviceAccountType:**
 *
 *  Browse Name             | DataType          | TypeDefinition       | Modelling Rule | See Also
 *  ------------------------|-------------------|----------------------|----------------|-----------------------------------------------------------------
 *  Authority               | AuthorityEnumType | BaseDataVariableType | Mandatory      | \ref getAuthority, \ref setAuthority
 *  Email                   | String            | BaseDataVariableType | Mandatory      | \ref getEmail, \ref setEmail
 *  SyncToConnectionAccount | Boolean           | BaseDataVariableType | Mandatory      | \ref getSyncToConnectionAccount, \ref setSyncToConnectionAccount
 *  UserName                | String            | BaseDataVariableType | Mandatory      | \ref getUserName, \ref setUserName
 *
 */
class MoxaClassBased_EXPORT DeviceAccountTypeBase:
    public OpcUa::BaseObjectType
{
    UA_DISABLE_COPY(DeviceAccountTypeBase);
protected:
    virtual ~DeviceAccountTypeBase();
public:
    // construction / destruction
    DeviceAccountTypeBase(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    DeviceAccountTypeBase(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    DeviceAccountTypeBase(
        UaBase::Object*    pBaseNode,
        XmlUaNodeFactoryManager*   pFactory,
        NodeManagerConfig* pNodeConfig,
        UaMutexRefCounted* pSharedMutex = NULL);
    static void createTypes();
    static void clearStaticMembers();

    virtual UaNodeId       typeDefinitionId() const;


    virtual void setAuthority(MoxaClassBased::AuthorityEnumType Authority);
    virtual MoxaClassBased::AuthorityEnumType getAuthority() const;

    virtual void setEmail(const UaString& Email);
    virtual UaString getEmail() const;

    virtual void setSyncToConnectionAccount(OpcUa_Boolean SyncToConnectionAccount);
    virtual OpcUa_Boolean getSyncToConnectionAccount() const;

    virtual void setUserName(const UaString& UserName);
    virtual UaString getUserName() const;

    virtual OpcUa::BaseDataVariableType* getAuthorityNode();
    virtual const OpcUa::BaseDataVariableType* getAuthorityNode() const;
    virtual OpcUa::BaseDataVariableType* getEmailNode();
    virtual const OpcUa::BaseDataVariableType* getEmailNode() const;
    virtual OpcUa::BaseDataVariableType* getSyncToConnectionAccountNode();
    virtual const OpcUa::BaseDataVariableType* getSyncToConnectionAccountNode() const;
    virtual OpcUa::BaseDataVariableType* getUserNameNode();
    virtual const OpcUa::BaseDataVariableType* getUserNameNode() const;

    // NodeAccessInfo management
    void useAccessInfoFromInstance(DeviceAccountTypeBase *pInstance);
    virtual void setAccessInfoWithChildren(NodeAccessInfo* pNodeAccessInfo);

protected:
    // Variable nodes
    // Variable Authority
    static OpcUa::BaseDataVariableType*  s_pAuthority;
    OpcUa::BaseDataVariableType*  m_pAuthority;
    // Variable Email
    static OpcUa::BaseDataVariableType*  s_pEmail;
    OpcUa::BaseDataVariableType*  m_pEmail;
    // Variable SyncToConnectionAccount
    static OpcUa::BaseDataVariableType*  s_pSyncToConnectionAccount;
    OpcUa::BaseDataVariableType*  m_pSyncToConnectionAccount;
    // Variable UserName
    static OpcUa::BaseDataVariableType*  s_pUserName;
    OpcUa::BaseDataVariableType*  m_pUserName;



private:
    void initialize();

private:
    static bool s_typeNodesCreated;
};

} // End namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/

#endif // #ifndef __MOXACLASSBASEDDEVICEACCOUNTTYPEBASE_H__


