/******************************************************************************
** moxaclassbased_ethernetinterfacedatatype.cpp
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#include "moxaclassbased_ethernetinterfacedatatype.h"

#include <opcua_datetime.h>

#include "uavariant.h"
#include "uadatavalue.h"
#include "uaextensionobject.h"
#include "uaatomic.h"

// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

/******************************************************************************
** Class EthernetInterfaceDataTypePrivate
******************************************************************************/
class EthernetInterfaceDataTypePrivate : private MoxaClassBased_EthernetInterfaceDataType
{
    EthernetInterfaceDataTypePrivate(const EthernetInterfaceDataTypePrivate &other);
    EthernetInterfaceDataTypePrivate& operator=(const EthernetInterfaceDataTypePrivate&);
public:
    EthernetInterfaceDataTypePrivate();
    explicit EthernetInterfaceDataTypePrivate(bool bStatic);
    explicit EthernetInterfaceDataTypePrivate(const MoxaClassBased_EthernetInterfaceDataType &other);
    ~EthernetInterfaceDataTypePrivate();

    int addRef();
    int release();
    inline int refCount() { return m_iRefCnt; }

private:
    int m_iRefCnt;
    friend class EthernetInterfaceDataType;
};

/* construction */
EthernetInterfaceDataTypePrivate::EthernetInterfaceDataTypePrivate()
 : m_iRefCnt(0)
{
    MoxaClassBased_EthernetInterfaceDataType_Initialize(this);
}

/*  Static initializer.
 *  This is used internaly to initialize the static shared_emtpy variable.
 *  RefCnt is set to 1 so it will never be deleted.
 */
EthernetInterfaceDataTypePrivate::EthernetInterfaceDataTypePrivate(bool)
 : m_iRefCnt(1)
{
    MoxaClassBased_EthernetInterfaceDataType_Initialize(this);
}


/*  construction
 */
EthernetInterfaceDataTypePrivate::EthernetInterfaceDataTypePrivate(const MoxaClassBased_EthernetInterfaceDataType &other) // [in] the other MoxaClassBased_EthernetInterfaceDataType.
 : m_iRefCnt(0)
{
    MoxaClassBased_EthernetInterfaceDataType_CopyTo(&other, this);
}

/* destruction */
EthernetInterfaceDataTypePrivate::~EthernetInterfaceDataTypePrivate()
{
    MoxaClassBased_EthernetInterfaceDataType_Clear(this);
}

/*  Add a reference to a EthernetInterfaceDataTypePrivate
 *  @return 0 if the object was deleted - otherwise a value bigger than 0.
 *  This method is not thread save regarding the return value. The returned counter is only reliable when it is 0.
 *  Other values are not reliable and should not be used for any logic.
 */
int EthernetInterfaceDataTypePrivate::addRef()
{
    return ua_atomic_increment(&m_iRefCnt);
}

/*  Release a EthernetInterfaceDataTypePrivate.
 *  @return the reference count.
 */
int EthernetInterfaceDataTypePrivate::release()
{
    int currentCount = ua_atomic_decrement(&m_iRefCnt);
    if (currentCount == 0)
    {
        delete this;
    }
    return currentCount;
}

EthernetInterfaceDataTypePrivate* shared_empty_EthernetInterfaceDataType()
{
    static EthernetInterfaceDataTypePrivate shared_static(true);
    return &shared_static;
}


/******************************************************************************
** Class EthernetInterfaceDataType
******************************************************************************/

/** Constructs an instance of the class EthernetInterfaceDataType with empty default values
*/
EthernetInterfaceDataType::EthernetInterfaceDataType()
{
    d_ptr = shared_empty_EthernetInterfaceDataType();
    d_ptr->addRef();
}

/** Constructs an instance of the class EthernetInterfaceDataType with values from another EthernetInterfaceDataType object
 *  @param other the other UaEthernetInterfaceDataType used to initialize the object
 */
EthernetInterfaceDataType::EthernetInterfaceDataType(const EthernetInterfaceDataType &other)
{
    d_ptr = other.d_ptr;
    d_ptr->addRef();
}

/** Constructs an instance of the class EthernetInterfaceDataType with values from another MoxaClassBased_EthernetInterfaceDataType structure
 *  @param other the other MoxaClassBased_EthernetInterfaceDataType used to initialize the object
 */
EthernetInterfaceDataType::EthernetInterfaceDataType(const MoxaClassBased_EthernetInterfaceDataType &other)
{
    d_ptr = new EthernetInterfaceDataTypePrivate(other);
    d_ptr->addRef();
}

/** Constructs an instance of the class EthernetInterfaceDataType with values provided in the constructor
 */
EthernetInterfaceDataType::EthernetInterfaceDataType(
        const UaString& InterfaceName
        )
{
    d_ptr = new EthernetInterfaceDataTypePrivate();
    d_ptr->addRef();
    setInterfaceName(InterfaceName);
}

/** Constructs an instance of the class EthernetInterfaceDataType initialized with value from a UaExtensionObject
 *  @param extensionObject the extension object containing the EthernetInterfaceDataType
 */
EthernetInterfaceDataType::EthernetInterfaceDataType(const UaExtensionObject &extensionObject)
{
    d_ptr = new EthernetInterfaceDataTypePrivate();
    d_ptr->addRef();

    const OpcUa_ExtensionObject *pExtensionObject = (const OpcUa_ExtensionObject*)extensionObject;
    MoxaClassBased_EthernetInterfaceDataType *pEthernetInterfaceDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(EthernetInterfaceDataType, pExtensionObject);

    if (pEthernetInterfaceDataType)
    {
        MoxaClassBased_EthernetInterfaceDataType_CopyTo(pEthernetInterfaceDataType, d_ptr);
    }
}

/** Constructs an instance of the class EthernetInterfaceDataType initialized with value from an OpcUa_ExtensionObject structure
 *  @param extensionObject the extension object containing the EthernetInterfaceDataType
 */
EthernetInterfaceDataType::EthernetInterfaceDataType(const OpcUa_ExtensionObject &extensionObject)
{
    d_ptr = new EthernetInterfaceDataTypePrivate();
    d_ptr->addRef();

    MoxaClassBased_EthernetInterfaceDataType *pEthernetInterfaceDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(EthernetInterfaceDataType, &extensionObject);

    if (pEthernetInterfaceDataType)
    {
        MoxaClassBased_EthernetInterfaceDataType_CopyTo(pEthernetInterfaceDataType, d_ptr);
    }
}

EthernetInterfaceDataType::EthernetInterfaceDataType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    d_ptr = new EthernetInterfaceDataTypePrivate();
    d_ptr->addRef();

    const OpcUa_ExtensionObject *pExtensionObject = (const OpcUa_ExtensionObject*)extensionObject;
    MoxaClassBased_EthernetInterfaceDataType *pEthernetInterfaceDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(EthernetInterfaceDataType, pExtensionObject);
    if (pEthernetInterfaceDataType)
    {
        if (bDetach == OpcUa_False)
        {
            MoxaClassBased_EthernetInterfaceDataType_CopyTo(pEthernetInterfaceDataType, d_ptr);
        }
        else
        {
            (*(MoxaClassBased_EthernetInterfaceDataType*)d_ptr) = *pEthernetInterfaceDataType;
            MoxaClassBased_EthernetInterfaceDataType_Initialize(pEthernetInterfaceDataType);
            extensionObject.clear();
        }
    }
}

EthernetInterfaceDataType::EthernetInterfaceDataType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    d_ptr = new EthernetInterfaceDataTypePrivate();
    d_ptr->addRef();

    MoxaClassBased_EthernetInterfaceDataType *pEthernetInterfaceDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(EthernetInterfaceDataType, &extensionObject);

    if (pEthernetInterfaceDataType)
    {
        if (bDetach == OpcUa_False)
        {
            MoxaClassBased_EthernetInterfaceDataType_CopyTo(pEthernetInterfaceDataType, d_ptr);
        }
        else
        {
            (*(MoxaClassBased_EthernetInterfaceDataType*)d_ptr) = *pEthernetInterfaceDataType;
            MoxaClassBased_EthernetInterfaceDataType_Initialize(pEthernetInterfaceDataType);
            OpcUa_ExtensionObject_Clear(&extensionObject);
        }
    }
}

/** Destroys the EthernetInterfaceDataType object
*/
EthernetInterfaceDataType::~EthernetInterfaceDataType()
{
    MOXACLASSBASED_D(EthernetInterfaceDataType);
    d->release();
}

/** Clear the data of the EthernetInterfaceDataType.
*/
void EthernetInterfaceDataType::clear()
{
    d_ptr->release();
    d_ptr = shared_empty_EthernetInterfaceDataType();
    d_ptr->addRef();
}

/** Compare two EthernetInterfaceDataType if they are similar.
 *  @param other the EthernetInterfaceDataType to compare.
 *  @return true if similar, false if not.
 */
bool EthernetInterfaceDataType::operator==(const EthernetInterfaceDataType &other) const
{
    return (MoxaClassBased_EthernetInterfaceDataType_Compare(d_ptr, other.d_ptr) == 0);
}

/** Returns true if the other EthernetInterfaceDataType is not equal to this.
 *  @see operator==
 *  @param other the EthernetInterfaceDataType to compare.
 *  @return true if other is not equal to this.
 */
bool EthernetInterfaceDataType::operator!=(const EthernetInterfaceDataType &other) const
{
    return !(operator==(other));
}

/** Assignment operator.
 *  @param other the EthernetInterfaceDataType to assign.
 *  @return Assignment operator.
 */
EthernetInterfaceDataType& EthernetInterfaceDataType::operator=(const EthernetInterfaceDataType &other)
{
    other.d_ptr->addRef();
    d_ptr->release();
    d_ptr = other.d_ptr;
    return *this;
}

/** Copy EthernetInterfaceDataType data to a newly allocated MoxaClassBased_EthernetInterfaceDataType.
 *  @return data to a newly allocated MoxaClassBased_EthernetInterfaceDataType.
 */
MoxaClassBased_EthernetInterfaceDataType* EthernetInterfaceDataType::copy() const
{
    return clone(*d_ptr);
}

/** Copy EthernetInterfaceDataType data to an existing MoxaClassBased_EthernetInterfaceDataType structure.
 *  @param pDst the destination of this copy operation.
 */
void EthernetInterfaceDataType::copyTo(MoxaClassBased_EthernetInterfaceDataType *pDst) const
{
    if (pDst == OpcUa_Null) return;
    cloneTo(*d_ptr, *pDst);
}

/** Copy MoxaClassBased_EthernetInterfaceDataType data to a newly allocated MoxaClassBased_EthernetInterfaceDataType.
 *  @param source Source to clone.
 *  @return new copy.
 */
MoxaClassBased_EthernetInterfaceDataType* EthernetInterfaceDataType::clone(const MoxaClassBased_EthernetInterfaceDataType& source)
{
    MoxaClassBased_EthernetInterfaceDataType* pEthernetInterfaceDataType = OpcUa_Null;
    MoxaClassBased_EthernetInterfaceDataType_Copy(&source, &pEthernetInterfaceDataType);
    return pEthernetInterfaceDataType;
}

/** Copy MoxaClassBased_EthernetInterfaceDataType data to an existing MoxaClassBased_EthernetInterfaceDataType structure.
 *  @param source the source of the clone operation.
 *  @param copy the destination of the clone operation.
 */
void EthernetInterfaceDataType::cloneTo(const MoxaClassBased_EthernetInterfaceDataType& source, MoxaClassBased_EthernetInterfaceDataType& copy)
{
    MoxaClassBased_EthernetInterfaceDataType_CopyTo(&source, &copy);
}

/** Attaches the data of the parameter pValue.
 * Don't clear the data of pValue afterwards manually, because EthernetInterfaceDataType is responsible for it now.
 */
void EthernetInterfaceDataType::attach(const MoxaClassBased_EthernetInterfaceDataType *pValue) //!< [in] Parameter to attach to.
{
    if (pValue == OpcUa_Null) return;
    if (d_ptr->refCount() == 1)
    {
        MoxaClassBased_EthernetInterfaceDataType_Clear(d_ptr);
    }
    else
    {
        d_ptr->release();
        d_ptr = new EthernetInterfaceDataTypePrivate();
        d_ptr->addRef();
    }
    // copy data value structure (no deep copy)
    OpcUa_MemCpy(d_ptr, sizeof(MoxaClassBased_EthernetInterfaceDataType), (void*)pValue, sizeof(MoxaClassBased_EthernetInterfaceDataType));
}

/** Detaches the internal EthernetInterfaceDataType structure from this class.
 *  This way you take over the control of releasing the EthernetInterfaceDataType data.
 *  If more than one references exist, the data is copied to pDst instead of being detached.
 *  @return If the functions succeeds pDst is returned, otherwise 0 is returned.
 */
MoxaClassBased_EthernetInterfaceDataType* EthernetInterfaceDataType::detach(MoxaClassBased_EthernetInterfaceDataType* pDst) //!< [out] Pointer to MoxaClassBased_EthernetInterfaceDataType structure that receives the EthernetInterfaceDataType data.
{
    if (pDst == OpcUa_Null) return OpcUa_Null;
    if (d_ptr->refCount() == 1)
    {
        OpcUa_MemCpy(pDst, sizeof(MoxaClassBased_EthernetInterfaceDataType), d_ptr, sizeof(MoxaClassBased_EthernetInterfaceDataType));
        // clear internal data without releasing deeper memory
        MoxaClassBased_EthernetInterfaceDataType_Initialize(d_ptr);
    }
    else
    {
        MoxaClassBased_EthernetInterfaceDataType_CopyTo(d_ptr, pDst);
    }
    d_ptr->release();
    d_ptr = shared_empty_EthernetInterfaceDataType();
    d_ptr->addRef();
    return pDst;
}

void EthernetInterfaceDataType::toVariant(UaVariant &variant) const
{
    UaExtensionObject extensionObject;
    toExtensionObject(extensionObject);
    variant.setExtensionObject(extensionObject, OpcUa_True);
}

void EthernetInterfaceDataType::toVariant(OpcUa_Variant &variant) const
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Scalar;
    variant.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(variant.Value.ExtensionObject);
    toExtensionObject(*variant.Value.ExtensionObject);
}

void EthernetInterfaceDataType::toVariant(UaVariant &variant, OpcUa_Boolean bDetach)
{
    UaExtensionObject extensionObject;
    toExtensionObject(extensionObject, bDetach);
    variant.setExtensionObject(extensionObject, OpcUa_True);
}

void EthernetInterfaceDataType::toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Scalar;
    variant.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(variant.Value.ExtensionObject);
    toExtensionObject(*variant.Value.ExtensionObject, bDetach);
}

void EthernetInterfaceDataType::toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    UaVariant variant;
    toVariant(variant);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void EthernetInterfaceDataType::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    OpcUa_Variant_Clear(&dataValue.Value);
    dataValue.Value.Datatype = OpcUaType_ExtensionObject;
    dataValue.Value.ArrayType = OpcUa_VariantArrayType_Scalar;
    dataValue.Value.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(dataValue.Value.Value.ExtensionObject);
    toExtensionObject(*dataValue.Value.Value.ExtensionObject);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

void EthernetInterfaceDataType::toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    UaVariant variant;
    toVariant(variant, bDetach);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void EthernetInterfaceDataType::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    OpcUa_Variant_Clear(&dataValue.Value);
    dataValue.Value.Datatype = OpcUaType_ExtensionObject;
    dataValue.Value.ArrayType = OpcUa_VariantArrayType_Scalar;
    dataValue.Value.Value.ExtensionObject = (OpcUa_ExtensionObject*)OpcUa_Alloc(sizeof(OpcUa_ExtensionObject));
    OpcUa_ExtensionObject_Initialize(dataValue.Value.Value.ExtensionObject);
    toExtensionObject(*dataValue.Value.Value.ExtensionObject, bDetach);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

void EthernetInterfaceDataType::toExtensionObject(UaExtensionObject &extensionObject) const
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    toExtensionObject(*pExtensionObject);
}

void EthernetInterfaceDataType::toExtensionObject(OpcUa_ExtensionObject &extensionObject) const
{
    OpcUa_ExtensionObject_Clear(&extensionObject);
    MoxaClassBased_EthernetInterfaceDataType *pEthernetInterfaceDataType = OpcUa_Null;
    if (OpcUa_IsGood(OpcUa_EncodeableObject_CreateExtension(&MoxaClassBased_EthernetInterfaceDataType_EncodeableType,
                                                            &extensionObject,
                                                            (OpcUa_Void**)&pEthernetInterfaceDataType)))
    {
        MoxaClassBased_EthernetInterfaceDataType_CopyTo(d_ptr, pEthernetInterfaceDataType);
    }
}

void EthernetInterfaceDataType::toExtensionObject(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    toExtensionObject(*pExtensionObject, bDetach);
}

void EthernetInterfaceDataType::toExtensionObject(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject_Clear(&extensionObject);
    MoxaClassBased_EthernetInterfaceDataType *pEthernetInterfaceDataType = OpcUa_Null;
    if (OpcUa_IsGood(OpcUa_EncodeableObject_CreateExtension(&MoxaClassBased_EthernetInterfaceDataType_EncodeableType,
                                                            &extensionObject,
                                                            (OpcUa_Void**)&pEthernetInterfaceDataType)))
    {
        MoxaClassBased_EthernetInterfaceDataType_Initialize(pEthernetInterfaceDataType);
        if (bDetach != OpcUa_False && d_ptr->refCount() == 1)
        {
            *pEthernetInterfaceDataType = *d_ptr;
            // clear internal data without releasing deeper memory
            MoxaClassBased_EthernetInterfaceDataType_Initialize(d_ptr);
        }
        else
        {
            MoxaClassBased_EthernetInterfaceDataType_CopyTo(d_ptr, pEthernetInterfaceDataType);
        }
        if (bDetach != OpcUa_False)
        {
            d_ptr->release();
            d_ptr = shared_empty_EthernetInterfaceDataType();
            d_ptr->addRef();
        }
    }
}

OpcUa_StatusCode EthernetInterfaceDataType::setEthernetInterfaceDataType(const UaExtensionObject &extensionObject)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    return setEthernetInterfaceDataType(*pExtensionObject);
}

OpcUa_StatusCode EthernetInterfaceDataType::setEthernetInterfaceDataType(const OpcUa_ExtensionObject &extensionObject)
{
    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    MoxaClassBased_EthernetInterfaceDataType *pEthernetInterfaceDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(EthernetInterfaceDataType, &extensionObject);

    if (pEthernetInterfaceDataType)
    {
        ret = OpcUa_Good;

        if (d_ptr->refCount() == 1)
        {
            MoxaClassBased_EthernetInterfaceDataType_Clear(d_ptr);
        }
        else
        {
            d_ptr->release();
            d_ptr = new EthernetInterfaceDataTypePrivate();
            d_ptr->addRef();
        }

        MoxaClassBased_EthernetInterfaceDataType_CopyTo(pEthernetInterfaceDataType, d_ptr);
    }
    return ret;
}

OpcUa_StatusCode EthernetInterfaceDataType::setEthernetInterfaceDataType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_ExtensionObject *pExtensionObject = (OpcUa_ExtensionObject*)(const OpcUa_ExtensionObject*)extensionObject;
    return setEthernetInterfaceDataType(*pExtensionObject, bDetach);
}

OpcUa_StatusCode EthernetInterfaceDataType::setEthernetInterfaceDataType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach)
{
    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    MoxaClassBased_EthernetInterfaceDataType *pEthernetInterfaceDataType = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(EthernetInterfaceDataType, &extensionObject);

    if (pEthernetInterfaceDataType != OpcUa_Null)
    {
        ret = OpcUa_Good;

        if (d_ptr->refCount() == 1)
        {
            MoxaClassBased_EthernetInterfaceDataType_Clear(d_ptr);
        }
        else
        {
            d_ptr->release();
            d_ptr = new EthernetInterfaceDataTypePrivate();
            d_ptr->addRef();
        }

        if (bDetach == OpcUa_False)
        {
            MoxaClassBased_EthernetInterfaceDataType_CopyTo(pEthernetInterfaceDataType, d_ptr);
        }
        else
        {
            (*(MoxaClassBased_EthernetInterfaceDataType*)d_ptr) = *pEthernetInterfaceDataType;
            MoxaClassBased_EthernetInterfaceDataType_Initialize(pEthernetInterfaceDataType);
            OpcUa_ExtensionObject_Clear(&extensionObject);
        }
    }
    return ret;
}

void EthernetInterfaceDataType::setEthernetInterfaceDataType(
        const UaString& InterfaceName
        )
{
    if (d_ptr->refCount() == 1)
    {
        MoxaClassBased_EthernetInterfaceDataType_Clear(d_ptr);
    }
    else
    {
        d_ptr->release();
        d_ptr = new EthernetInterfaceDataTypePrivate();
        d_ptr->addRef();
    }
    setInterfaceName(InterfaceName);
}

bool EthernetInterfaceDataType::isPhysAddressSet() const
{
    return (d_ptr->EncodingMask & MoxaClassBased_EthernetInterfaceDataType_OptionalFields_PhysAddress) != 0;
}

UaString EthernetInterfaceDataType::getPhysAddress(bool *ok) const
{
    if (ok)
    {
        *ok = isPhysAddressSet();
    }
    return d_ptr->PhysAddress;
}

UaString EthernetInterfaceDataType::getInterfaceName() const
{
    return d_ptr->InterfaceName;
}

void EthernetInterfaceDataType::unsetPhysAddress()
{
    if (d_ptr->refCount() > 1)
    {
        EthernetInterfaceDataTypePrivate *pNew = new EthernetInterfaceDataTypePrivate((const MoxaClassBased_EthernetInterfaceDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }
    OpcUa_String_Clear(&d_ptr->PhysAddress);
    d_ptr->EncodingMask &= (~MoxaClassBased_EthernetInterfaceDataType_OptionalFields_PhysAddress);
}

void EthernetInterfaceDataType::setPhysAddress(const UaString& PhysAddress)
{
    if (d_ptr->refCount() > 1)
    {
        EthernetInterfaceDataTypePrivate *pNew = new EthernetInterfaceDataTypePrivate((const MoxaClassBased_EthernetInterfaceDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }

    d_ptr->EncodingMask |= MoxaClassBased_EthernetInterfaceDataType_OptionalFields_PhysAddress;

    OpcUa_String_Clear(&d_ptr->PhysAddress);
    PhysAddress.copyTo(&d_ptr->PhysAddress);
}

void EthernetInterfaceDataType::setInterfaceName(const UaString& InterfaceName)
{
    if (d_ptr->refCount() > 1)
    {
        EthernetInterfaceDataTypePrivate *pNew = new EthernetInterfaceDataTypePrivate((const MoxaClassBased_EthernetInterfaceDataType)*d_ptr);
        d_ptr->release();
        d_ptr = pNew;
        d_ptr->addRef();
    }

    OpcUa_String_Clear(&d_ptr->InterfaceName);
    InterfaceName.copyTo(&d_ptr->InterfaceName);
}


/******************************************************************************
** Class EthernetInterfaceDataTypes
******************************************************************************/
EthernetInterfaceDataTypes EthernetInterfaceDataTypes::empty;

EthernetInterfaceDataTypes::EthernetInterfaceDataTypes()
: m_noOfElements(0),
  m_data((MoxaClassBased_EthernetInterfaceDataType*)OpcUa_Null)
{
}

EthernetInterfaceDataTypes::EthernetInterfaceDataTypes(const EthernetInterfaceDataTypes &other)
: m_noOfElements(0),
  m_data((MoxaClassBased_EthernetInterfaceDataType*)OpcUa_Null)
{
    operator=(other);
}

EthernetInterfaceDataTypes::EthernetInterfaceDataTypes(OpcUa_Int32 length, MoxaClassBased_EthernetInterfaceDataType* data)
: m_noOfElements(0),
  m_data((MoxaClassBased_EthernetInterfaceDataType*)OpcUa_Null)
{
    if (length > 0 && data != OpcUa_Null)
    {
        m_noOfElements = length;
        m_data = (MoxaClassBased_EthernetInterfaceDataType*)OpcUa_Alloc(m_noOfElements * sizeof(MoxaClassBased_EthernetInterfaceDataType));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            MoxaClassBased_EthernetInterfaceDataType_CopyTo(&(data[i]), &(m_data[i]));
        }
    }
}

EthernetInterfaceDataTypes::~EthernetInterfaceDataTypes()
{
    clear();
}

EthernetInterfaceDataTypes& EthernetInterfaceDataTypes::operator=(const EthernetInterfaceDataTypes &other)
{
    if (this == &other) {return *this;}

    clear();
    if (other.m_noOfElements > 0)
    {
        m_noOfElements = other.m_noOfElements;
        m_data = (MoxaClassBased_EthernetInterfaceDataType*)OpcUa_Alloc(m_noOfElements * sizeof(MoxaClassBased_EthernetInterfaceDataType));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            MoxaClassBased_EthernetInterfaceDataType_CopyTo(&(other.m_data[i]), &(m_data[i]));
        }
    }
    return *this;
}

/** Returns the MoxaClassBased_EthernetInterfaceDataType at index position index as a modifiable reference.
 *
 *  index must be valid index position in the array.
 */
MoxaClassBased_EthernetInterfaceDataType& EthernetInterfaceDataTypes::operator[](OpcUa_UInt32 index)
{
    assert(index<m_noOfElements);
    return m_data[index];
}

/** Returns the MoxaClassBased_EthernetInterfaceDataType at index position index.
 *
 *  index must be valid index position in the array.
 */
const MoxaClassBased_EthernetInterfaceDataType& EthernetInterfaceDataTypes::operator[](OpcUa_UInt32 index) const
{
    assert(index<m_noOfElements);
    return m_data[index];
}

/** Attaches the raw data.
 *
 *  Clears the array and takes the ownership of data.
 *  Don't clear the data afterwards manually, because EthernetInterfaceDataTypes is responsible for it now.
 */
void EthernetInterfaceDataTypes::attach(OpcUa_UInt32 length, MoxaClassBased_EthernetInterfaceDataType* data)
{
    clear();
    m_data = data;
    m_noOfElements = length;
}

/** Attaches the raw data.
 *
 *  Clears the array and takes the ownership of data.
 *  Don't clear the data afterwards manually, because EthernetInterfaceDataTypes is responsible for it now.
 */
void EthernetInterfaceDataTypes::attach(OpcUa_Int32 length, MoxaClassBased_EthernetInterfaceDataType* data)
{
    clear();
    if (length >= 0)
    {
        m_data = data;
        m_noOfElements = length;
    }
}

bool EthernetInterfaceDataTypes::operator==(const EthernetInterfaceDataTypes &other) const
{
    if (m_noOfElements != other.m_noOfElements) {return false;}

    if (m_noOfElements > 0)
    {
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            if (MoxaClassBased_EthernetInterfaceDataType_Compare(&(m_data[i]), &(other.m_data[i])) != OPCUA_EQUAL) {return false;};
        }
    }
    return true;
}

bool EthernetInterfaceDataTypes::operator!=(const EthernetInterfaceDataTypes &other) const
{
    return !(operator==(other));
}

/** Detaches the raw data from this class.
 *
 *  The caller takes ownership of the raw data and is responsible for deleting it
 *  by calling OpcUa_Free.
 *  @return The raw data.
 */
MoxaClassBased_EthernetInterfaceDataType* EthernetInterfaceDataTypes::detach()
{
    MoxaClassBased_EthernetInterfaceDataType* pRet = m_data;
    m_noOfElements = 0;
    m_data = (MoxaClassBased_EthernetInterfaceDataType*)OpcUa_Null;
    return pRet;
}

void EthernetInterfaceDataTypes::create(OpcUa_UInt32 length)
{
    clear();
    if (length > 0)
    {
        m_data = (MoxaClassBased_EthernetInterfaceDataType*)OpcUa_Alloc(length * sizeof(MoxaClassBased_EthernetInterfaceDataType));
        for (OpcUa_UInt32 i = 0; i < length; i++)
        {
            MoxaClassBased_EthernetInterfaceDataType_Initialize(&(m_data[i]));
        }
        m_noOfElements = length;
    }
}

void EthernetInterfaceDataTypes::resize(OpcUa_UInt32 length)
{
    if (length < m_noOfElements)
    {
        if (length != 0)
        {
            for (OpcUa_UInt32 i = length; i < m_noOfElements; i++)
            {
                MoxaClassBased_EthernetInterfaceDataType_Clear(&(m_data[i]));
            }

            MoxaClassBased_EthernetInterfaceDataType* newData = (MoxaClassBased_EthernetInterfaceDataType*)OpcUa_ReAlloc(m_data, length * sizeof(MoxaClassBased_EthernetInterfaceDataType));
            if (newData)
            {
                m_data = newData;
                m_noOfElements = length;
            }
        }
        else
        {
            clear();
        }
    }
    else if (length > m_noOfElements)
    {
        MoxaClassBased_EthernetInterfaceDataType* newData = (MoxaClassBased_EthernetInterfaceDataType*)OpcUa_ReAlloc(m_data, length * sizeof(MoxaClassBased_EthernetInterfaceDataType));
        if (newData)
        {
            for (OpcUa_UInt32 i = m_noOfElements; i < length; i++)
            {
                MoxaClassBased_EthernetInterfaceDataType_Initialize(&(newData[i]));
            }
            m_data = newData;
            m_noOfElements = length;
        }
    }
}

void EthernetInterfaceDataTypes::clear()
{
    if (m_data)
    {
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            MoxaClassBased_EthernetInterfaceDataType_Clear(&(m_data[i]));
        }
        OpcUa_Free(m_data);
        m_data = (MoxaClassBased_EthernetInterfaceDataType*)OpcUa_Null;
    }
    m_noOfElements = 0;
}

void EthernetInterfaceDataTypes::toVariant(UaVariant &variant) const
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    toVariant(*pVariant);
}

void EthernetInterfaceDataTypes::toVariant(OpcUa_Variant &variant) const
{
    OpcUa_Variant_Clear(&variant);

    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Array;
    variant.Value.Array.Length = m_noOfElements;
    variant.Value.Array.Value.ExtensionObjectArray = (OpcUa_ExtensionObject*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUa_ExtensionObject));
    for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
    {
        MoxaClassBased_EthernetInterfaceDataType *pValue = OpcUa_Null;
        OpcUa_ExtensionObject_Initialize(&variant.Value.Array.Value.ExtensionObjectArray[i]);
        OpcUa_EncodeableObject_CreateExtension(&MoxaClassBased_EthernetInterfaceDataType_EncodeableType,
                                               &variant.Value.Array.Value.ExtensionObjectArray[i],
                                               (OpcUa_Void**)&pValue);
        MoxaClassBased_EthernetInterfaceDataType_CopyTo(&m_data[i], pValue);
    }
}

void EthernetInterfaceDataTypes::toVariant(UaVariant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    toVariant(*pVariant, bDetach);
}

void EthernetInterfaceDataTypes::toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant_Clear(&variant);
    variant.Datatype = OpcUaType_ExtensionObject;
    variant.ArrayType = OpcUa_VariantArrayType_Array;
    variant.Value.Array.Length = m_noOfElements;
    variant.Value.Array.Value.ExtensionObjectArray = (OpcUa_ExtensionObject*)OpcUa_Alloc(m_noOfElements * sizeof(OpcUa_ExtensionObject));
    for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
    {
        MoxaClassBased_EthernetInterfaceDataType *pValue = OpcUa_Null;
        OpcUa_ExtensionObject_Initialize(&variant.Value.Array.Value.ExtensionObjectArray[i]);
        OpcUa_EncodeableObject_CreateExtension(&MoxaClassBased_EthernetInterfaceDataType_EncodeableType,
                                               &variant.Value.Array.Value.ExtensionObjectArray[i],
                                               (OpcUa_Void**)&pValue);
        if (bDetach != OpcUa_False)
        {
            *pValue = m_data[i];
        }
        else
        {
            MoxaClassBased_EthernetInterfaceDataType_CopyTo(&m_data[i], pValue);
        }
    }
    if (bDetach != OpcUa_False)
    {
        OpcUa_Free(m_data);
        m_data = (MoxaClassBased_EthernetInterfaceDataType*)OpcUa_Null;
        m_noOfElements = 0;
    }
}

void EthernetInterfaceDataTypes::toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    UaVariant variant;
    toVariant(variant);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void EthernetInterfaceDataTypes::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const
{
    toVariant(dataValue.Value);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

void EthernetInterfaceDataTypes::toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    UaVariant variant;
    toVariant(variant, bDetach);
    dataValue.setValue(variant, OpcUa_True, updateTimeStamps);
}

void EthernetInterfaceDataTypes::toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps)
{
    toVariant(dataValue.Value, bDetach);

    if (updateTimeStamps != OpcUa_False)
    {
        dataValue.SourceTimestamp = OpcUa_DateTime_UtcNow();
        dataValue.ServerTimestamp = dataValue.SourceTimestamp;
    }
}

OpcUa_StatusCode EthernetInterfaceDataTypes::setEthernetInterfaceDataTypes(const UaVariant &variant)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    return setEthernetInterfaceDataTypes(*pVariant);
}

OpcUa_StatusCode EthernetInterfaceDataTypes::setEthernetInterfaceDataTypes(const OpcUa_Variant &variant)
{
    return setEthernetInterfaceDataTypes((OpcUa_Variant&)variant, OpcUa_False);
}

OpcUa_StatusCode EthernetInterfaceDataTypes::setEthernetInterfaceDataTypes(UaVariant &variant, OpcUa_Boolean bDetach)
{
    OpcUa_Variant *pVariant = (OpcUa_Variant*)(const OpcUa_Variant*)variant;
    return setEthernetInterfaceDataTypes(*pVariant, bDetach);
}

OpcUa_StatusCode EthernetInterfaceDataTypes::setEthernetInterfaceDataTypes(OpcUa_Variant &variant, OpcUa_Boolean bDetach)
{
    clear();

    OpcUa_StatusCode ret = OpcUa_BadTypeMismatch;
    if (variant.Datatype == OpcUaType_ExtensionObject &&
        variant.ArrayType == OpcUa_VariantArrayType_Array)
    {
        ret = OpcUa_Good;
        m_noOfElements = variant.Value.Array.Length >= 0 ? variant.Value.Array.Length : 0;
        if (m_noOfElements > 0 && variant.Value.Array.Value.ExtensionObjectArray != OpcUa_Null)
        {
            m_data = (MoxaClassBased_EthernetInterfaceDataType*)OpcUa_Alloc(m_noOfElements * sizeof(MoxaClassBased_EthernetInterfaceDataType));

            OpcUa_UInt32 i = 0;
            for (i = 0; i < m_noOfElements; i++)
            {
                MoxaClassBased_EthernetInterfaceDataType_Initialize(&m_data[i]);

                MoxaClassBased_EthernetInterfaceDataType *pValue = MOXACLASSBASED_EXTENSIONOBJECT_GET_ENCODEABLE(EthernetInterfaceDataType, &variant.Value.Array.Value.ExtensionObjectArray[i]);
                if (pValue)
                {
                    if (bDetach != OpcUa_False)
                    {
                        m_data[i] = *pValue;
                        MoxaClassBased_EthernetInterfaceDataType_Initialize(pValue);
                    }
                    else
                    {
                        MoxaClassBased_EthernetInterfaceDataType_CopyTo(pValue, &m_data[i]);
                    }
                }
                else
                {
                    ret = OpcUa_BadTypeMismatch;
                    break;
                }
            }
            if (OpcUa_IsNotGood(ret))
            {
                for (OpcUa_UInt32 j = 0; j < i; j++)
                {
                    MoxaClassBased_EthernetInterfaceDataType_Clear(&m_data[j]);
                }
                OpcUa_Free(m_data);
                m_data = (MoxaClassBased_EthernetInterfaceDataType*)OpcUa_Null;
                m_noOfElements = 0;
            }
        }
        else
        {
            m_noOfElements = 0;
        }
    }
    return ret;
}

OpcUa_StatusCode EthernetInterfaceDataTypes::setEthernetInterfaceDataTypes(OpcUa_Int32 length, MoxaClassBased_EthernetInterfaceDataType* data)
{
    clear();

    if (length > 0 && data != OpcUa_Null)
    {
        m_noOfElements = length;
        m_data = (MoxaClassBased_EthernetInterfaceDataType*)OpcUa_Alloc(m_noOfElements * sizeof(MoxaClassBased_EthernetInterfaceDataType));
        for (OpcUa_UInt32 i = 0; i < m_noOfElements; i++)
        {
            MoxaClassBased_EthernetInterfaceDataType_CopyTo(&(data[i]), &(m_data[i]));
        }
    }
    return OpcUa_Good;
}

} // namespace MoxaClassBased

