/******************************************************************************
** moxaclassbased_scantopologystatemachinetype.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     This is a template file that was generated for your convenience.
**     This file will not be overwritten when generating code again.
**     ADD YOUR IMPLEMTATION HERE!
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace
*http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#ifndef __MOXACLASSBASED_SCANTOPOLOGYSTATEMACHINETYPE_H__
#define __MOXACLASSBASED_SCANTOPOLOGYSTATEMACHINETYPE_H__

#include <future>

#include "act_core.hpp"
#include "moxaclassbased_scantopologystatemachinetypebase.h"

// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

/** @brief Class implementing the UaObject interface for the ScanTopologyStateMachineType.
 *
 * OPC UA Objects are used to represent systems, system components, real-world objects and software
 * objects. They have the NodeClass Object. The detailed description of Objects and their attributes
 * can be found in the general description of the Object node class.
 *
 *  **Method members of the ScanTopologyStateMachineType:**
 *
 *  Browse Name | Modelling Rule
 *  ------------|---------------
 *  \ref Start  | Mandatory
 *  \ref Stop   | Mandatory
 *
 */
class MoxaClassBased_EXPORT ScanTopologyStateMachineType : public ScanTopologyStateMachineTypeBase, public UaThread {
  UA_DISABLE_COPY(ScanTopologyStateMachineType);

 protected:
  // destruction
  virtual ~ScanTopologyStateMachineType();

 public:
  // construction
  ScanTopologyStateMachineType(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject,
                               NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
  ScanTopologyStateMachineType(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex,
                               NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
  ScanTopologyStateMachineType(UaBase::Object* pBaseNode, XmlUaNodeFactoryManager* pFactory,
                               NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
  static void createTypes();
  static void clearStaticMembers();

  // UaScanTopologyStateMachineType method Start
  virtual UaStatus Start(const ServiceContext& serviceContext, const MoxaClassBased::AutoScanDataTypes& NetworkIpRange);
  // UaScanTopologyStateMachineType method Stop
  virtual UaStatus Stop(const ServiceContext& serviceContext);

  // user add
  virtual void run();
  UaStatus setProgramState(ProgramState state);

 protected:
 private:
};

}  // namespace MoxaClassBased

#endif  // #ifndef __MOXACLASSBASEDSCANTOPOLOGYSTATEMACHINETYPE_H__
