/******************************************************************************
** moxaclassbased_ipsettingtype.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     This is a template file that was generated for your convenience.
**     This file will not be overwritten when generating code again.
**     ADD YOUR IMPLEMTATION HERE!
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#ifndef __MOXACLASSBASED_IPSETTINGTYPE_H__
#define __MOXACLASSBASED_IPSETTINGTYPE_H__

#include "moxaclassbased_ipsettingtypebase.h"

// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

/** @brief Class implementing the UaObject interface for the IpSettingType.
 *
 * OPC UA Objects are used to represent systems, system components, real-world objects and software
 * objects. They have the NodeClass Object. The detailed description of Objects and their attributes
 * can be found in the general description of the Object node class.
 *
 *  **Variable members of the IpSettingType:**
 *
 *  Browse Name | DataType | TypeDefinition       | Modelling Rule | See Also
 *  ------------|----------|----------------------|----------------|-------------------------------------------------------------------------------------------------------------
 *  DNS1        | String   | BaseDataVariableType | Mandatory      | \ref IpSettingTypeBase::getDNS1 "getDNS1", \ref IpSettingTypeBase::setDNS1 "setDNS1"
 *  DNS2        | String   | BaseDataVariableType | Mandatory      | \ref IpSettingTypeBase::getDNS2 "getDNS2", \ref IpSettingTypeBase::setDNS2 "setDNS2"
 *  Gateway     | String   | BaseDataVariableType | Mandatory      | \ref IpSettingTypeBase::getGateway "getGateway", \ref IpSettingTypeBase::setGateway "setGateway"
 *  IpAddress   | String   | BaseDataVariableType | Mandatory      | \ref IpSettingTypeBase::getIpAddress "getIpAddress", \ref IpSettingTypeBase::setIpAddress "setIpAddress"
 *  SubnetMask  | String   | BaseDataVariableType | Mandatory      | \ref IpSettingTypeBase::getSubnetMask "getSubnetMask", \ref IpSettingTypeBase::setSubnetMask "setSubnetMask"
 *
 */
class MoxaClassBased_EXPORT IpSettingType:
    public IpSettingTypeBase
{
    UA_DISABLE_COPY(IpSettingType);
protected:
    // destruction
    virtual ~IpSettingType();
public:
    // construction
    IpSettingType(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    IpSettingType(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    IpSettingType(
        UaBase::Object*    pBaseNode,
        XmlUaNodeFactoryManager*   pFactory,
        NodeManagerConfig* pNodeConfig,
        UaMutexRefCounted* pSharedMutex = NULL);
    static void createTypes();
    static void clearStaticMembers();


protected:

private:
};

} // End namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/

#endif // #ifndef __MOXACLASSBASEDIPSETTINGTYPE_H__

