/******************************************************************************
** moxaclassbased_tsnstreamapplicationdatatype.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/


#ifndef __MOXACLASSBASED_TSNSTREAMAPPLICATIONDATATYPE_H__
#define __MOXACLASSBASED_TSNSTREAMAPPLICATIONDATATYPE_H__

#include <opcua_proxystub.h>

#include "uabase.h"
#include "uastring.h"
#include "uaarraytemplates.h"
#include "moxaclassbased_identifiers.h"
#include "moxaclassbased_datatypes.h"
#include "moxaclassbased_ieeetsnvlantagdatatype.h"
#include "moxaclassbased_perstreamprioritydatatype.h"
#include "moxaclassbased_tsntrafficspecificationdatatype.h"

class UaExtensionObject;
class UaVariant;
class UaDataValue;

// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

class MoxaClassBased_EXPORT TsnStreamApplicationDataTypePrivate;

/**
 *  @brief Wrapper class for the UA stack structure MoxaClassBased_TsnStreamApplicationDataType.
 *
 *  This class encapsulates the native MoxaClassBased_TsnStreamApplicationDataType structure
 *  and handles memory allocation and cleanup for you.
 *  TsnStreamApplicationDataType uses implicit sharing to avoid needless copying and to boost the performance.
 *  Only if you modify a shared TsnStreamApplicationDataType it creates a copy for that (copy-on-write).
 *  So assigning another TsnStreamApplicationDataType or passing it as parameter needs constant time and is nearly as fast as assigning a pointer.
 */
class MoxaClassBased_EXPORT TsnStreamApplicationDataType
{
    MOXACLASSBASED_DECLARE_PRIVATE(TsnStreamApplicationDataType)
public:
    TsnStreamApplicationDataType();
    TsnStreamApplicationDataType(const TsnStreamApplicationDataType &other);
    TsnStreamApplicationDataType(const MoxaClassBased_TsnStreamApplicationDataType &other);
    TsnStreamApplicationDataType(const UaExtensionObject &extensionObject);
    TsnStreamApplicationDataType(const OpcUa_ExtensionObject &extensionObject);
    TsnStreamApplicationDataType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach);
    TsnStreamApplicationDataType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach);
    ~TsnStreamApplicationDataType();

    void clear();

    bool operator==(const TsnStreamApplicationDataType &other) const;
    bool operator!=(const TsnStreamApplicationDataType &other) const;

    TsnStreamApplicationDataType& operator=(const TsnStreamApplicationDataType &other);

    MoxaClassBased_TsnStreamApplicationDataType* copy() const;
    void copyTo(MoxaClassBased_TsnStreamApplicationDataType *pDst) const;

    static MoxaClassBased_TsnStreamApplicationDataType* clone(const MoxaClassBased_TsnStreamApplicationDataType& source);
    static void cloneTo(const MoxaClassBased_TsnStreamApplicationDataType& source, MoxaClassBased_TsnStreamApplicationDataType& copy);

    void attach(const MoxaClassBased_TsnStreamApplicationDataType *pValue);
    MoxaClassBased_TsnStreamApplicationDataType* detach(MoxaClassBased_TsnStreamApplicationDataType* pDst);

    void toVariant(UaVariant &variant) const;
    void toVariant(OpcUa_Variant &variant) const;
    void toVariant(UaVariant &variant, OpcUa_Boolean bDetach);
    void toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach);

    void toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const;
    void toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const;
    void toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps);
    void toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps);

    void toExtensionObject(UaExtensionObject &extensionObject) const;
    void toExtensionObject(OpcUa_ExtensionObject &extensionObject) const;
    void toExtensionObject(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach);
    void toExtensionObject(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach);

    OpcUa_StatusCode setTsnStreamApplicationDataType(const UaExtensionObject &extensionObject);
    OpcUa_StatusCode setTsnStreamApplicationDataType(const OpcUa_ExtensionObject &extensionObject);
    OpcUa_StatusCode setTsnStreamApplicationDataType(UaExtensionObject &extensionObject, OpcUa_Boolean bDetach);
    OpcUa_StatusCode setTsnStreamApplicationDataType(OpcUa_ExtensionObject &extensionObject, OpcUa_Boolean bDetach);

    bool isApplicationNameSet() const;
    UaString getApplicationName(bool *ok = 0) const;
    bool isFRERModeSet() const;
    OpcUa_Boolean getFRERMode(bool *ok = 0) const;
    bool isTrafficTypeSet() const;
    UaString getTrafficType(bool *ok = 0) const;
    bool isQoSTypeSet() const;
    MoxaClassBased::QoSEnumType getQoSType(bool *ok = 0) const;
    bool isReceiveOffsetMinSet() const;
    OpcUa_Double getReceiveOffsetMin(bool *ok = 0) const;
    bool isReceiveOffsetMaxSet() const;
    OpcUa_Double getReceiveOffsetMax(bool *ok = 0) const;
    bool isLatencyMaxSet() const;
    OpcUa_Double getLatencyMax(bool *ok = 0) const;
    bool isTagStreamSet() const;
    OpcUa_Boolean getTagStream(bool *ok = 0) const;
    bool isTagStreamVlanTagSet() const;
    MoxaClassBased::IeeeTsnVlanTagDataType getTagStreamVlanTag(bool *ok = 0) const;
    bool isTagMethodSet() const;
    MoxaClassBased::TagMethodEnumType getTagMethod(bool *ok = 0) const;
    bool isPerStreamPrioritySet() const;
    MoxaClassBased::PerStreamPriorityDataType getPerStreamPriority(bool *ok = 0) const;
    bool isTsnTrafficSpecificationSet() const;
    MoxaClassBased::TsnTrafficSpecificationDataType getTsnTrafficSpecification(bool *ok = 0) const;
    bool isTransmissionOffsetMinSet() const;
    OpcUa_Double getTransmissionOffsetMin(bool *ok = 0) const;
    bool isTransmissionOffsetMaxSet() const;
    OpcUa_Double getTransmissionOffsetMax(bool *ok = 0) const;
    bool isTransmissionJitterSet() const;
    OpcUa_Double getTransmissionJitter(bool *ok = 0) const;

    void setApplicationName(const UaString& ApplicationName);
    void unsetApplicationName();
    void setFRERMode(OpcUa_Boolean FRERMode);
    void unsetFRERMode();
    void setTrafficType(const UaString& TrafficType);
    void unsetTrafficType();
    void setQoSType(MoxaClassBased::QoSEnumType QoSType);
    void unsetQoSType();
    void setReceiveOffsetMin(OpcUa_Double ReceiveOffsetMin);
    void unsetReceiveOffsetMin();
    void setReceiveOffsetMax(OpcUa_Double ReceiveOffsetMax);
    void unsetReceiveOffsetMax();
    void setLatencyMax(OpcUa_Double LatencyMax);
    void unsetLatencyMax();
    void setTagStream(OpcUa_Boolean TagStream);
    void unsetTagStream();
    void setTagStreamVlanTag(const MoxaClassBased::IeeeTsnVlanTagDataType& TagStreamVlanTag);
    void unsetTagStreamVlanTag();
    void setTagMethod(MoxaClassBased::TagMethodEnumType TagMethod);
    void unsetTagMethod();
    void setPerStreamPriority(const MoxaClassBased::PerStreamPriorityDataType& PerStreamPriority);
    void unsetPerStreamPriority();
    void setTsnTrafficSpecification(const MoxaClassBased::TsnTrafficSpecificationDataType& TsnTrafficSpecification);
    void unsetTsnTrafficSpecification();
    void setTransmissionOffsetMin(OpcUa_Double TransmissionOffsetMin);
    void unsetTransmissionOffsetMin();
    void setTransmissionOffsetMax(OpcUa_Double TransmissionOffsetMax);
    void unsetTransmissionOffsetMax();
    void setTransmissionJitter(OpcUa_Double TransmissionJitter);
    void unsetTransmissionJitter();
};

class MoxaClassBased_EXPORT TsnStreamApplicationDataTypes
{
public:
    TsnStreamApplicationDataTypes();
    TsnStreamApplicationDataTypes(const TsnStreamApplicationDataTypes &other);
    TsnStreamApplicationDataTypes(OpcUa_Int32 length, MoxaClassBased_TsnStreamApplicationDataType* data);
    virtual ~TsnStreamApplicationDataTypes();

    TsnStreamApplicationDataTypes& operator=(const TsnStreamApplicationDataTypes &other);
    MoxaClassBased_TsnStreamApplicationDataType& operator[](OpcUa_UInt32 index);
    const MoxaClassBased_TsnStreamApplicationDataType& operator[](OpcUa_UInt32 index) const;

    void attach(OpcUa_UInt32 length, MoxaClassBased_TsnStreamApplicationDataType* data);
    void attach(OpcUa_Int32 length, MoxaClassBased_TsnStreamApplicationDataType* data);
    MoxaClassBased_TsnStreamApplicationDataType* detach();

    bool operator==(const TsnStreamApplicationDataTypes &other) const;
    bool operator!=(const TsnStreamApplicationDataTypes &other) const;

    void create(OpcUa_UInt32 length);
    void resize(OpcUa_UInt32 length);
    void clear();

    inline OpcUa_UInt32 length() const {return m_noOfElements;}
    inline const MoxaClassBased_TsnStreamApplicationDataType* rawData() const {return m_data;}
    inline MoxaClassBased_TsnStreamApplicationDataType* rawData() {return m_data;}
    void toVariant(UaVariant &variant) const;
    void toVariant(OpcUa_Variant &variant) const;
    void toVariant(UaVariant &variant, OpcUa_Boolean bDetach);
    void toVariant(OpcUa_Variant &variant, OpcUa_Boolean bDetach);

    void toDataValue(UaDataValue &dataValue, OpcUa_Boolean updateTimeStamps) const;
    void toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean updateTimeStamps) const;
    void toDataValue(UaDataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps);
    void toDataValue(OpcUa_DataValue &dataValue, OpcUa_Boolean bDetach, OpcUa_Boolean updateTimeStamps);

    OpcUa_StatusCode setTsnStreamApplicationDataTypes(const UaVariant &variant);
    OpcUa_StatusCode setTsnStreamApplicationDataTypes(const OpcUa_Variant &variant);
    OpcUa_StatusCode setTsnStreamApplicationDataTypes(UaVariant &variant, OpcUa_Boolean bDetach);
    OpcUa_StatusCode setTsnStreamApplicationDataTypes(OpcUa_Variant &variant, OpcUa_Boolean bDetach);
    OpcUa_StatusCode setTsnStreamApplicationDataTypes(OpcUa_Int32 length, MoxaClassBased_TsnStreamApplicationDataType* data);

    static TsnStreamApplicationDataTypes empty;
private:
    OpcUa_UInt32 m_noOfElements;
    MoxaClassBased_TsnStreamApplicationDataType* m_data;
};

} // namespace MoxaClassBased

#endif // __MOXACLASSBASED_TSNSTREAMAPPLICATIONDATATYPE_H__

