/******************************************************************************
** moxaclassbased_snmptype.h
**
**   **************************** auto-generated ****************************
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.8.0, using C++ OPC UA SDK 1.8.2 template (version 4)
**
**     This is a template file that was generated for your convenience.
**     This file will not be overwritten when generating code again.
**     ADD YOUR IMPLEMTATION HERE!
**   **************************** auto-generated ****************************
**
** Copyright (c) 2006-2025 Unified Automation GmbH. All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Project: C++ OPC Server SDK information model for namespace http://www.moxa.com/auto-configuration-tool-class-based-model/
**
** Description: OPC Unified Architecture Software Development Kit.
**
******************************************************************************/

#ifndef __MOXACLASSBASED_SNMPTYPE_H__
#define __MOXACLASSBASED_SNMPTYPE_H__

#include "moxaclassbased_snmptypebase.h"

// Namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/
namespace MoxaClassBased {

/** @brief Class implementing the UaObject interface for the SNMPType.
 *
 * OPC UA Objects are used to represent systems, system components, real-world objects and software
 * objects. They have the NodeClass Object. The detailed description of Objects and their attributes
 * can be found in the general description of the Object node class.
 *
 *  **Variable members of the SNMPType:**
 *
 *  Browse Name | DataType    | TypeDefinition       | Modelling Rule | See Also
 *  ------------|-------------|----------------------|----------------|---------------------------------------------------------------------------------------
 *  Port        | UInt16      | BaseDataVariableType | Mandatory      | \ref SNMPTypeBase::getPort "getPort", \ref SNMPTypeBase::setPort "setPort"
 *  Status      | Boolean     | BaseDataVariableType | Mandatory      | \ref SNMPTypeBase::getStatus "getStatus", \ref SNMPTypeBase::setStatus "setStatus"
 *  Version     | SNMPVersion | BaseDataVariableType | Mandatory      | \ref SNMPTypeBase::getVersion "getVersion", \ref SNMPTypeBase::setVersion "setVersion"
 *
 */
class MoxaClassBased_EXPORT SNMPType:
    public SNMPTypeBase
{
    UA_DISABLE_COPY(SNMPType);
protected:
    // destruction
    virtual ~SNMPType();
public:
    // construction
    SNMPType(const UaNodeId& nodeId, UaObject* pInstanceDeclarationObject, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    SNMPType(const UaNodeId& nodeId, const UaString& name, OpcUa_UInt16 browseNameNameSpaceIndex, NodeManagerConfig* pNodeConfig, UaMutexRefCounted* pSharedMutex = NULL);
    SNMPType(
        UaBase::Object*    pBaseNode,
        XmlUaNodeFactoryManager*   pFactory,
        NodeManagerConfig* pNodeConfig,
        UaMutexRefCounted* pSharedMutex = NULL);
    static void createTypes();
    static void clearStaticMembers();


protected:

private:
};

} // End namespace for the UA information model http://www.moxa.com/auto-configuration-tool-class-based-model/

#endif // #ifndef __MOXACLASSBASEDSNMPTYPE_H__

